WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_envs', 8),
             ('n_timesteps', 1000000.0),
             ('policy', 'MlpPolicy')])
Using 8 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:190: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:198: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:206: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:240: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:242: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_2
--------------------------------------
| approxkl           | 0.0005332869  |
| clipfrac           | 0.00024414062 |
| explained_variance | 0.0014        |
| fps                | 1556          |
| n_updates          | 1             |
| policy_entropy     | 2.836543      |
| policy_loss        | -0.0013060448 |
| serial_timesteps   | 128           |
| time_elapsed       | 1.38e-05      |
| total_timesteps    | 1024          |
| value_loss         | 13.059367     |
--------------------------------------
---------------------------------------
| approxkl           | 0.00020008814  |
| clipfrac           | 0.0            |
| ep_len_mean        | 150            |
| ep_reward_mean     | -18.3          |
| explained_variance | 0.00163        |
| fps                | 3569           |
| n_updates          | 2              |
| policy_entropy     | 2.8349273      |
| policy_loss        | -0.00062733766 |
| serial_timesteps   | 256            |
| time_elapsed       | 0.658          |
| total_timesteps    | 2048           |
| value_loss         | 22.925072      |
---------------------------------------
---------------------------------------
| approxkl           | 2.235718e-05   |
| clipfrac           | 0.0            |
| ep_len_mean        | 150            |
| ep_reward_mean     | -20.2          |
| explained_variance | -0.00514       |
| fps                | 3630           |
| n_updates          | 3              |
| policy_entropy     | 2.8338132      |
| policy_loss        | -0.00038411285 |
| serial_timesteps   | 384            |
| time_elapsed       | 0.945          |
| total_timesteps    | 3072           |
| value_loss         | 20.07924       |
---------------------------------------
---------------------------------------
| approxkl           | 0.00011863341  |
| clipfrac           | 0.0            |
| ep_len_mean        | 150            |
| ep_reward_mean     | -17            |
| explained_variance | 0.000841       |
| fps                | 3531           |
| n_updates          | 4              |
| policy_entropy     | 2.8339958      |
| policy_loss        | -0.00038871463 |
| serial_timesteps   | 512            |
| time_elapsed       | 1.23           |
| total_timesteps    | 4096           |
| value_loss         | 28.741076      |
---------------------------------------
--------------------------------------
| approxkl           | 0.00020405976 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16           |
| explained_variance | -0.00769      |
| fps                | 3581          |
| n_updates          | 5             |
| policy_entropy     | 2.8331199     |
| policy_loss        | -0.0005308181 |
| serial_timesteps   | 640           |
| time_elapsed       | 1.52          |
| total_timesteps    | 5120          |
| value_loss         | 19.780891     |
--------------------------------------
--------------------------------------
| approxkl           | 0.00023710064 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16.3         |
| explained_variance | 0.0089        |
| fps                | 3592          |
| n_updates          | 6             |
| policy_entropy     | 2.83036       |
| policy_loss        | -0.0010166119 |
| serial_timesteps   | 768           |
| time_elapsed       | 1.8           |
| total_timesteps    | 6144          |
| value_loss         | 22.79794      |
--------------------------------------
--------------------------------------
| approxkl           | 0.0013413873  |
| clipfrac           | 0.0056152344  |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16.3         |
| explained_variance | -0.00664      |
| fps                | 3622          |
| n_updates          | 7             |
| policy_entropy     | 2.8265738     |
| policy_loss        | -0.0023803236 |
| serial_timesteps   | 896           |
| time_elapsed       | 2.09          |
| total_timesteps    | 7168          |
| value_loss         | 19.69456      |
--------------------------------------
--------------------------------------
| approxkl           | 0.00047166477 |
| clipfrac           | 0.00048828125 |
| ep_len_mean        | 150           |
| ep_reward_mean     | -17           |
| explained_variance | -0.00127      |
| fps                | 3522          |
| n_updates          | 8             |
| policy_entropy     | 2.826334      |
| policy_loss        | -0.000981715  |
| serial_timesteps   | 1024          |
| time_elapsed       | 2.37          |
| total_timesteps    | 8192          |
| value_loss         | 18.450039     |
--------------------------------------
--------------------------------------
| approxkl           | 0.0015606887  |
| clipfrac           | 0.0087890625  |
| ep_len_mean        | 150           |
| ep_reward_mean     | -17           |
| explained_variance | -0.00133      |
| fps                | 3612          |
| n_updates          | 9             |
| policy_entropy     | 2.8256428     |
| policy_loss        | -0.0021269533 |
| serial_timesteps   | 1152          |
| time_elapsed       | 2.66          |
| total_timesteps    | 9216          |
| value_loss         | 10.299643     |
--------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
