WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 0
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:407: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:241: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:242: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_1
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f9ca8f36518> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f9ca8f36208>
  "{} != {}".format(self.training_env, self.eval_env))
********** Iteration 0 ************
Optimizing Policy...
sampling
done in 0.659 seconds
computegrad
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:364: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

done in 0.102 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0474          0
         1    0.00646     0.0224
         2    0.00424      0.103
         3    0.00269      0.194
         4    0.00138      0.351
         5    0.00462      0.372
         6     0.0021      0.409
         7   0.000466      0.568
         8   0.000146      0.602
         9   7.15e-05      0.804
        10   0.000115      0.806
done in 0.168 seconds
Expected: 0.026 Actual: 0.025
Stepsize OK!
vf
done in 0.056 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -15.8      |
| EpThisIter              | 6          |
| EpisodesSoFar           | 6          |
| TimeElapsed             | 1.07       |
| TimestepsSoFar          | 1024       |
| entloss                 | 0.0        |
| entropy                 | 2.8233364  |
| explained_variance_t... | 0.00446    |
| meankl                  | 0.00813175 |
| optimgain               | 0.02532129 |
| surrgain                | 0.02532129 |
----------------------------------------
********** Iteration 1 ************
Optimizing Policy...
sampling
done in 0.569 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0222          0
         1     0.0161     0.0138
         2     0.0062     0.0736
         3    0.00305     0.0782
         4    0.00243      0.147
         5    0.00119      0.277
         6   0.000853      0.338
         7    0.00141       0.43
         8     0.0206      0.485
         9   0.000598      0.709
        10    0.00324      0.722
done in 0.013 seconds
Expected: 0.023 Actual: 0.016
violated KL constraint. shrinking step.
Expected: 0.023 Actual: 0.011
Stepsize OK!
vf
done in 0.018 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -14.8        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 13           |
| TimeElapsed             | 1.68         |
| TimestepsSoFar          | 2048         |
| entloss                 | 0.0          |
| entropy                 | 2.8391197    |
| explained_variance_t... | -0.0141      |
| meankl                  | 0.0037769137 |
| optimgain               | 0.010577433  |
| surrgain                | 0.010577433  |
------------------------------------------
********** Iteration 2 ************
Optimizing Policy...
sampling
done in 0.586 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0357          0
         1    0.00421     0.0138
         2    0.00355     0.0454
         3    0.00179      0.052
         4    0.00234      0.153
         5    0.00223      0.348
         6    0.00291      0.511
         7   0.000711      0.663
         8   0.000674      0.725
         9     0.0107      0.812
        10   0.000473      0.877
done in 0.014 seconds
Expected: 0.023 Actual: 0.016
Stepsize OK!
vf
done in 0.022 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -16.3        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 20           |
| TimeElapsed             | 2.31         |
| TimestepsSoFar          | 3072         |
| entloss                 | 0.0          |
| entropy                 | 2.8367338    |
| explained_variance_t... | 0.000719     |
| meankl                  | 0.0095322495 |
| optimgain               | 0.016417235  |
| surrgain                | 0.016417235  |
------------------------------------------
********** Iteration 3 ************
Optimizing Policy...
sampling
done in 0.643 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0264          0
         1     0.0286     0.0172
         2    0.00926     0.0883
         3    0.00371      0.094
         4    0.00323       0.18
         5    0.00229       0.29
         6    0.00115      0.413
         7    0.00128      0.527
         8     0.0146      0.573
         9    0.00114      0.638
        10    0.00456      0.656
done in 0.013 seconds
Expected: 0.026 Actual: 0.022
violated KL constraint. shrinking step.
Expected: 0.026 Actual: 0.013
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -17.9        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 27           |
| TimeElapsed             | 3            |
| TimestepsSoFar          | 4096         |
| entloss                 | 0.0          |
| entropy                 | 2.8247879    |
| explained_variance_t... | 0.0647       |
| meankl                  | 0.0033790646 |
| optimgain               | 0.012519591  |
| surrgain                | 0.012519591  |
------------------------------------------
********** Iteration 4 ************
Optimizing Policy...
sampling
done in 0.629 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0679          0
         1     0.0156     0.0128
         2     0.0338     0.0587
         3    0.00279     0.0786
         4    0.00733       0.32
         5    0.00192      0.507
         6    0.00273      0.604
         7      0.021      0.759
         8    0.00194      0.792
         9     0.0149      0.825
        10    0.00163      0.909
done in 0.013 seconds
Expected: 0.030 Actual: 0.019
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -18.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 34          |
| TimeElapsed             | 3.67        |
| TimestepsSoFar          | 5120        |
| entloss                 | 0.0         |
| entropy                 | 2.8103135   |
| explained_variance_t... | -0.0717     |
| meankl                  | 0.010108348 |
| optimgain               | 0.01932763  |
| surrgain                | 0.01932763  |
-----------------------------------------
********** Iteration 5 ************
Optimizing Policy...
sampling
done in 0.580 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0441          0
         1     0.0158     0.0137
         2     0.0318     0.0761
         3    0.00541      0.095
         4    0.00404      0.208
         5    0.00587      0.331
         6    0.00382      0.542
         7    0.00228      0.643
         8    0.00879      0.657
         9    0.00562      0.795
        10    0.00159      0.807
done in 0.013 seconds
Expected: 0.030 Actual: 0.015
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -18.4        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 40           |
| TimeElapsed             | 4.3          |
| TimestepsSoFar          | 6144         |
| entloss                 | 0.0          |
| entropy                 | 2.801078     |
| explained_variance_t... | -0.161       |
| meankl                  | 0.0061830217 |
| optimgain               | 0.015428129  |
| surrgain                | 0.015428129  |
------------------------------------------
********** Iteration 6 ************
Optimizing Policy...
sampling
done in 0.578 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0631          0
         1     0.0284     0.0185
         2     0.0197     0.0954
         3    0.00432      0.105
         4    0.00305      0.179
         5    0.00329      0.288
         6    0.00248      0.425
         7    0.00167        0.5
         8     0.0233       0.55
         9    0.00378      0.749
        10    0.00352      0.764
done in 0.013 seconds
Expected: 0.030 Actual: 0.027
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -18.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 47          |
| TimeElapsed             | 4.92        |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 2.7666023   |
| explained_variance_t... | 0.00637     |
| meankl                  | 0.009818051 |
| optimgain               | 0.027373299 |
| surrgain                | 0.027373299 |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
sampling
done in 0.581 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.114          0
         1     0.0188     0.0132
         2     0.0851     0.0615
         3     0.0077      0.128
         4    0.00528      0.283
         5    0.00312      0.401
         6    0.00387      0.569
         7     0.0165      0.586
         8    0.00583      0.678
         9    0.00338      0.688
        10    0.00191      0.901
done in 0.013 seconds
Expected: 0.035 Actual: 0.042
Stepsize OK!
vf
done in 0.020 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -18        |
| EpThisIter              | 7          |
| EpisodesSoFar           | 54         |
| TimeElapsed             | 5.54       |
| TimestepsSoFar          | 8192       |
| entloss                 | 0.0        |
| entropy                 | 2.7870486  |
| explained_variance_t... | 0.0348     |
| meankl                  | 0.01195472 |
| optimgain               | 0.04218958 |
| surrgain                | 0.04218958 |
----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
sampling
done in 0.581 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0232          0
         1     0.0278    0.00951
         2    0.00965     0.0918
         3    0.00593      0.096
         4    0.00293      0.177
         5    0.00219      0.295
         6    0.00192      0.508
         7     0.0402      0.574
         8    0.00074      0.654
         9     0.0069      0.694
        10   0.000568      0.704
done in 0.013 seconds
Expected: 0.027 Actual: 0.026
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 6.17        |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 2.765076    |
| explained_variance_t... | 0.133       |
| meankl                  | 0.012753719 |
| optimgain               | 0.02584111  |
| surrgain                | 0.02584111  |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
sampling
Eval num_timesteps=9216, episode_reward=-2.60 +/- 14.22
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.079 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0309          0
         1     0.0349     0.0284
         2    0.00472     0.0861
         3     0.0119     0.0966
         4     0.0111      0.215
         5    0.00429      0.361
         6    0.00236      0.457
         7    0.00263       0.53
         8    0.00159      0.604
         9    0.00281      0.641
        10    0.00159      0.651
done in 0.013 seconds
Expected: 0.029 Actual: 0.028
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 68          |
| TimeElapsed             | 7.29        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 2.7490435   |
| explained_variance_t... | 0.173       |
| meankl                  | 0.009570653 |
| optimgain               | 0.028139919 |
| surrgain                | 0.028139919 |
-----------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_1
pybullet build time: Sep  9 2020 17:03:46
