WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 0
OrderedDict([('n_envs', 8),
             ('n_timesteps', 1000000.0),
             ('policy', 'MlpPolicy')])
Using 8 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:190: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:198: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:206: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:240: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:242: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_1
--------------------------------------
| approxkl           | 0.00068533246 |
| clipfrac           | 0.0014648438  |
| explained_variance | 0.00391       |
| fps                | 1550          |
| n_updates          | 1             |
| policy_entropy     | 2.8384452     |
| policy_loss        | -0.0023765531 |
| serial_timesteps   | 128           |
| time_elapsed       | 1.26e-05      |
| total_timesteps    | 1024          |
| value_loss         | 23.212032     |
--------------------------------------
--------------------------------------
| approxkl           | 0.00012184939 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -18.6         |
| explained_variance | -0.0018       |
| fps                | 3611          |
| n_updates          | 2             |
| policy_entropy     | 2.8409858     |
| policy_loss        | -0.0003298915 |
| serial_timesteps   | 256           |
| time_elapsed       | 0.661         |
| total_timesteps    | 2048          |
| value_loss         | 16.522417     |
--------------------------------------
--------------------------------------
| approxkl           | 6.26357e-05   |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16           |
| explained_variance | -0.0121       |
| fps                | 3322          |
| n_updates          | 3             |
| policy_entropy     | 2.8448834     |
| policy_loss        | -0.0008082809 |
| serial_timesteps   | 384           |
| time_elapsed       | 0.944         |
| total_timesteps    | 3072          |
| value_loss         | 17.74072      |
--------------------------------------
--------------------------------------
| approxkl           | 0.00026361435 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -18.7         |
| explained_variance | -0.0127       |
| fps                | 3321          |
| n_updates          | 4             |
| policy_entropy     | 2.8476164     |
| policy_loss        | -0.0004656238 |
| serial_timesteps   | 512           |
| time_elapsed       | 1.25          |
| total_timesteps    | 4096          |
| value_loss         | 28.368782     |
--------------------------------------
--------------------------------------
| approxkl           | 0.00034636568 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -17.8         |
| explained_variance | 0.0014        |
| fps                | 3531          |
| n_updates          | 5             |
| policy_entropy     | 2.8476808     |
| policy_loss        | -0.0018731916 |
| serial_timesteps   | 640           |
| time_elapsed       | 1.56          |
| total_timesteps    | 5120          |
| value_loss         | 15.820247     |
--------------------------------------
---------------------------------------
| approxkl           | 0.00014987214  |
| clipfrac           | 0.0            |
| ep_len_mean        | 150            |
| ep_reward_mean     | -16.6          |
| explained_variance | 0.0084         |
| fps                | 3525           |
| n_updates          | 6              |
| policy_entropy     | 2.847725       |
| policy_loss        | -0.00035173396 |
| serial_timesteps   | 768            |
| time_elapsed       | 1.85           |
| total_timesteps    | 6144           |
| value_loss         | 16.425106      |
---------------------------------------
--------------------------------------
| approxkl           | 0.0005022277  |
| clipfrac           | 0.00048828125 |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16.6         |
| explained_variance | 0.0111        |
| fps                | 3684          |
| n_updates          | 7             |
| policy_entropy     | 2.849578      |
| policy_loss        | -0.0018280587 |
| serial_timesteps   | 896           |
| time_elapsed       | 2.14          |
| total_timesteps    | 7168          |
| value_loss         | 15.791361     |
--------------------------------------
--------------------------------------
| approxkl           | 0.0004718653  |
| clipfrac           | 0.0007324219  |
| ep_len_mean        | 150           |
| ep_reward_mean     | -16.3         |
| explained_variance | -0.00556      |
| fps                | 3462          |
| n_updates          | 8             |
| policy_entropy     | 2.8532238     |
| policy_loss        | -0.0015341984 |
| serial_timesteps   | 1024          |
| time_elapsed       | 2.42          |
| total_timesteps    | 8192          |
| value_loss         | 12.892912     |
--------------------------------------
--------------------------------------
| approxkl           | 0.0013896368  |
| clipfrac           | 0.008300781   |
| ep_len_mean        | 150           |
| ep_reward_mean     | -15.8         |
| explained_variance | -0.00477      |
| fps                | 3701          |
| n_updates          | 9             |
| policy_entropy     | 2.8558593     |
| policy_loss        | -0.0027283733 |
| serial_timesteps   | 1152          |
| time_elapsed       | 2.72          |
| total_timesteps    | 9216          |
| value_loss         | 12.964327     |
--------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_1
pybullet build time: Sep  9 2020 17:03:46
