WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=100000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:131: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/policies.py:124: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:57: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:164: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:194: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:209: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1375: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:226: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:237: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/td3/td3.py:240: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_0.1M_Reacher2Dof-v0/td3/Reacher2Dof-v0_2
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f64524526d8> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f6452452320>
  "{} != {}".format(self.training_env, self.eval_env))
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -67       |
| episodes                | 4         |
| eplenmean               | 150       |
| fps                     | 411       |
| mean 100 episode reward | -67       |
| n_updates               | 500       |
| qf1_loss                | 31.664497 |
| qf2_loss                | 30.536003 |
| success rate            | 0         |
| time_elapsed            | 1         |
| total timesteps         | 600       |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -79.6     |
| episodes                | 8         |
| eplenmean               | 150       |
| fps                     | 440       |
| mean 100 episode reward | -79.6     |
| n_updates               | 1100      |
| qf1_loss                | 29.013836 |
| qf2_loss                | 29.15933  |
| success rate            | 0         |
| time_elapsed            | 2         |
| total timesteps         | 1200      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -93.9     |
| episodes                | 12        |
| eplenmean               | 150       |
| fps                     | 468       |
| mean 100 episode reward | -93.9     |
| n_updates               | 1700      |
| qf1_loss                | 37.974045 |
| qf2_loss                | 38.223034 |
| success rate            | 0         |
| time_elapsed            | 3         |
| total timesteps         | 1800      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -103      |
| episodes                | 16        |
| eplenmean               | 150       |
| fps                     | 482       |
| mean 100 episode reward | -103      |
| n_updates               | 2300      |
| qf1_loss                | 48.148636 |
| qf2_loss                | 48.823483 |
| success rate            | 0         |
| time_elapsed            | 4         |
| total timesteps         | 2400      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -105      |
| episodes                | 20        |
| eplenmean               | 150       |
| fps                     | 491       |
| mean 100 episode reward | -105      |
| n_updates               | 2900      |
| qf1_loss                | 52.670998 |
| qf2_loss                | 53.601707 |
| success rate            | 0         |
| time_elapsed            | 6         |
| total timesteps         | 3000      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -99.7     |
| episodes                | 24        |
| eplenmean               | 150       |
| fps                     | 500       |
| mean 100 episode reward | -99.7     |
| n_updates               | 3500      |
| qf1_loss                | 45.781654 |
| qf2_loss                | 46.08609  |
| success rate            | 0         |
| time_elapsed            | 7         |
| total timesteps         | 3600      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -104      |
| episodes                | 28        |
| eplenmean               | 150       |
| fps                     | 507       |
| mean 100 episode reward | -104      |
| n_updates               | 4100      |
| qf1_loss                | 50.068893 |
| qf2_loss                | 50.016823 |
| success rate            | 0         |
| time_elapsed            | 8         |
| total timesteps         | 4200      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -108      |
| episodes                | 32        |
| eplenmean               | 150       |
| fps                     | 515       |
| mean 100 episode reward | -108      |
| n_updates               | 4700      |
| qf1_loss                | 53.315353 |
| qf2_loss                | 53.141083 |
| success rate            | 0         |
| time_elapsed            | 9         |
| total timesteps         | 4800      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -106      |
| episodes                | 36        |
| eplenmean               | 150       |
| fps                     | 520       |
| mean 100 episode reward | -106      |
| n_updates               | 5300      |
| qf1_loss                | 54.208065 |
| qf2_loss                | 53.976463 |
| success rate            | 0         |
| time_elapsed            | 10        |
| total timesteps         | 5400      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -101      |
| episodes                | 40        |
| eplenmean               | 150       |
| fps                     | 524       |
| mean 100 episode reward | -101      |
| n_updates               | 5900      |
| qf1_loss                | 50.597027 |
| qf2_loss                | 50.1601   |
| success rate            | 0         |
| time_elapsed            | 11        |
| total timesteps         | 6000      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -96.5     |
| episodes                | 44        |
| eplenmean               | 150       |
| fps                     | 527       |
| mean 100 episode reward | -96.5     |
| n_updates               | 6500      |
| qf1_loss                | 47.35881  |
| qf2_loss                | 46.818703 |
| success rate            | 0         |
| time_elapsed            | 12        |
| total timesteps         | 6600      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -94.2     |
| episodes                | 48        |
| eplenmean               | 150       |
| fps                     | 529       |
| mean 100 episode reward | -94.2     |
| n_updates               | 7100      |
| qf1_loss                | 45.478626 |
| qf2_loss                | 44.894928 |
| success rate            | 0         |
| time_elapsed            | 13        |
| total timesteps         | 7200      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -91.7     |
| episodes                | 52        |
| eplenmean               | 150       |
| fps                     | 532       |
| mean 100 episode reward | -91.7     |
| n_updates               | 7700      |
| qf1_loss                | 43.68123  |
| qf2_loss                | 42.753887 |
| success rate            | 0         |
| time_elapsed            | 14        |
| total timesteps         | 7800      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -88       |
| episodes                | 56        |
| eplenmean               | 150       |
| fps                     | 535       |
| mean 100 episode reward | -88       |
| n_updates               | 8300      |
| qf1_loss                | 40.076576 |
| qf2_loss                | 39.57123  |
| success rate            | 0         |
| time_elapsed            | 15        |
| total timesteps         | 8400      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -86.2     |
| episodes                | 60        |
| eplenmean               | 150       |
| fps                     | 537       |
| mean 100 episode reward | -86.2     |
| n_updates               | 8900      |
| qf1_loss                | 39.071426 |
| qf2_loss                | 38.610325 |
| success rate            | 0         |
| time_elapsed            | 16        |
| total timesteps         | 9000      |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -84.5     |
| episodes                | 64        |
| eplenmean               | 150       |
| fps                     | 540       |
| mean 100 episode reward | -84.5     |
| n_updates               | 9500      |
| qf1_loss                | 38.44332  |
| qf2_loss                | 38.624035 |
| success rate            | 0         |
| time_elapsed            | 17        |
| total timesteps         | 9600      |
---------------------------------------
Eval num_timesteps=10000, episode_reward=-71.94 +/- 17.43
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -83.6     |
| episodes                | 68        |
| eplenmean               | 150       |
| fps                     | 531       |
| mean 100 episode reward | -83.6     |
| n_updates               | 10100     |
| qf1_loss                | 37.15132  |
| qf2_loss                | 37.557423 |
| success rate            | 0         |
| time_elapsed            | 19        |
| total timesteps         | 10200     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -82.1    |
| episodes                | 72       |
| eplenmean               | 150      |
| fps                     | 533      |
| mean 100 episode reward | -82.1    |
| n_updates               | 10700    |
| qf1_loss                | 35.11943 |
| qf2_loss                | 36.87931 |
| success rate            | 0        |
| time_elapsed            | 20       |
| total timesteps         | 10800    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -77.7     |
| episodes                | 76        |
| eplenmean               | 150       |
| fps                     | 535       |
| mean 100 episode reward | -77.7     |
| n_updates               | 11300     |
| qf1_loss                | 30.871286 |
| qf2_loss                | 33.278465 |
| success rate            | 0         |
| time_elapsed            | 21        |
| total timesteps         | 11400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -74       |
| episodes                | 80        |
| eplenmean               | 150       |
| fps                     | 536       |
| mean 100 episode reward | -74       |
| n_updates               | 11900     |
| qf1_loss                | 30.096977 |
| qf2_loss                | 32.838814 |
| success rate            | 0         |
| time_elapsed            | 22        |
| total timesteps         | 12000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -71.5     |
| episodes                | 84        |
| eplenmean               | 150       |
| fps                     | 537       |
| mean 100 episode reward | -71.5     |
| n_updates               | 12500     |
| qf1_loss                | 27.636894 |
| qf2_loss                | 30.437588 |
| success rate            | 0         |
| time_elapsed            | 23        |
| total timesteps         | 12600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -68.6     |
| episodes                | 88        |
| eplenmean               | 150       |
| fps                     | 538       |
| mean 100 episode reward | -68.6     |
| n_updates               | 13100     |
| qf1_loss                | 25.789158 |
| qf2_loss                | 28.851957 |
| success rate            | 0         |
| time_elapsed            | 24        |
| total timesteps         | 13200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -65.9     |
| episodes                | 92        |
| eplenmean               | 150       |
| fps                     | 540       |
| mean 100 episode reward | -65.9     |
| n_updates               | 13700     |
| qf1_loss                | 25.216415 |
| qf2_loss                | 28.184702 |
| success rate            | 0         |
| time_elapsed            | 25        |
| total timesteps         | 13800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -63.3     |
| episodes                | 96        |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -63.3     |
| n_updates               | 14300     |
| qf1_loss                | 23.676203 |
| qf2_loss                | 26.267117 |
| success rate            | 0         |
| time_elapsed            | 26        |
| total timesteps         | 14400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -61       |
| episodes                | 100       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -61       |
| n_updates               | 14900     |
| qf1_loss                | 22.208786 |
| qf2_loss                | 24.262835 |
| success rate            | 0         |
| time_elapsed            | 27        |
| total timesteps         | 15000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -58.4     |
| episodes                | 104       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -58.4     |
| n_updates               | 15500     |
| qf1_loss                | 20.015722 |
| qf2_loss                | 21.756136 |
| success rate            | 0         |
| time_elapsed            | 28        |
| total timesteps         | 15600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -55.2     |
| episodes                | 108       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -55.2     |
| n_updates               | 16100     |
| qf1_loss                | 19.79274  |
| qf2_loss                | 20.804916 |
| success rate            | 0         |
| time_elapsed            | 29        |
| total timesteps         | 16200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -51.3     |
| episodes                | 112       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -51.3     |
| n_updates               | 16700     |
| qf1_loss                | 17.35944  |
| qf2_loss                | 18.503426 |
| success rate            | 0         |
| time_elapsed            | 30        |
| total timesteps         | 16800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -46.9     |
| episodes                | 116       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -46.9     |
| n_updates               | 17300     |
| qf1_loss                | 17.484758 |
| qf2_loss                | 18.463108 |
| success rate            | 0         |
| time_elapsed            | 31        |
| total timesteps         | 17400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -44.1     |
| episodes                | 120       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -44.1     |
| n_updates               | 17900     |
| qf1_loss                | 17.320679 |
| qf2_loss                | 17.263134 |
| success rate            | 0         |
| time_elapsed            | 32        |
| total timesteps         | 18000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -41.6     |
| episodes                | 124       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -41.6     |
| n_updates               | 18500     |
| qf1_loss                | 14.673354 |
| qf2_loss                | 14.873407 |
| success rate            | 0         |
| time_elapsed            | 33        |
| total timesteps         | 18600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -36.7      |
| episodes                | 128        |
| eplenmean               | 150        |
| fps                     | 549        |
| mean 100 episode reward | -36.7      |
| n_updates               | 19100      |
| qf1_loss                | 15.2676735 |
| qf2_loss                | 15.398834  |
| success rate            | 0          |
| time_elapsed            | 34         |
| total timesteps         | 19200      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -32.8     |
| episodes                | 132       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -32.8     |
| n_updates               | 19700     |
| qf1_loss                | 14.398908 |
| qf2_loss                | 14.631009 |
| success rate            | 0         |
| time_elapsed            | 36        |
| total timesteps         | 19800     |
---------------------------------------
Eval num_timesteps=20000, episode_reward=-18.32 +/- 19.23
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -29.2     |
| episodes                | 136       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -29.2     |
| n_updates               | 20300     |
| qf1_loss                | 12.452409 |
| qf2_loss                | 12.19267  |
| success rate            | 0         |
| time_elapsed            | 37        |
| total timesteps         | 20400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -27.6     |
| episodes                | 140       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -27.6     |
| n_updates               | 20900     |
| qf1_loss                | 12.353494 |
| qf2_loss                | 11.680037 |
| success rate            | 0         |
| time_elapsed            | 38        |
| total timesteps         | 21000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -25.7     |
| episodes                | 144       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -25.7     |
| n_updates               | 21500     |
| qf1_loss                | 11.181902 |
| qf2_loss                | 10.446302 |
| success rate            | 0         |
| time_elapsed            | 39        |
| total timesteps         | 21600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -23.1      |
| episodes                | 148        |
| eplenmean               | 150        |
| fps                     | 546        |
| mean 100 episode reward | -23.1      |
| n_updates               | 22100      |
| qf1_loss                | 10.5434885 |
| qf2_loss                | 10.095681  |
| success rate            | 0          |
| time_elapsed            | 40         |
| total timesteps         | 22200      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -20.3     |
| episodes                | 152       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -20.3     |
| n_updates               | 22700     |
| qf1_loss                | 11.498919 |
| qf2_loss                | 10.720869 |
| success rate            | 0         |
| time_elapsed            | 41        |
| total timesteps         | 22800     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -18.6    |
| episodes                | 156      |
| eplenmean               | 150      |
| fps                     | 547      |
| mean 100 episode reward | -18.6    |
| n_updates               | 23300    |
| qf1_loss                | 9.169783 |
| qf2_loss                | 8.886289 |
| success rate            | 0        |
| time_elapsed            | 42       |
| total timesteps         | 23400    |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -15.8    |
| episodes                | 160      |
| eplenmean               | 150      |
| fps                     | 548      |
| mean 100 episode reward | -15.8    |
| n_updates               | 23900    |
| qf1_loss                | 8.756574 |
| qf2_loss                | 8.54123  |
| success rate            | 0        |
| time_elapsed            | 43       |
| total timesteps         | 24000    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -13.4     |
| episodes                | 164       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -13.4     |
| n_updates               | 24500     |
| qf1_loss                | 7.36313   |
| qf2_loss                | 7.1439123 |
| success rate            | 0         |
| time_elapsed            | 44        |
| total timesteps         | 24600     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -10.6    |
| episodes                | 168      |
| eplenmean               | 150      |
| fps                     | 548      |
| mean 100 episode reward | -10.6    |
| n_updates               | 25100    |
| qf1_loss                | 7.496704 |
| qf2_loss                | 7.554886 |
| success rate            | 0        |
| time_elapsed            | 45       |
| total timesteps         | 25200    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.31     |
| episodes                | 172       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -8.3      |
| n_updates               | 25700     |
| qf1_loss                | 7.5984035 |
| qf2_loss                | 7.623804  |
| success rate            | 0         |
| time_elapsed            | 46        |
| total timesteps         | 25800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.7      |
| episodes                | 176       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -8.7      |
| n_updates               | 26300     |
| qf1_loss                | 6.0444045 |
| qf2_loss                | 5.988174  |
| success rate            | 0         |
| time_elapsed            | 48        |
| total timesteps         | 26400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.62     |
| episodes                | 180       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -8.6      |
| n_updates               | 26900     |
| qf1_loss                | 6.706702  |
| qf2_loss                | 6.7143764 |
| success rate            | 0         |
| time_elapsed            | 49        |
| total timesteps         | 27000     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -7.92    |
| episodes                | 184      |
| eplenmean               | 150      |
| fps                     | 549      |
| mean 100 episode reward | -7.9     |
| n_updates               | 27500    |
| qf1_loss                | 6.338003 |
| qf2_loss                | 6.383537 |
| success rate            | 0        |
| time_elapsed            | 50       |
| total timesteps         | 27600    |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -7.72    |
| episodes                | 188      |
| eplenmean               | 150      |
| fps                     | 548      |
| mean 100 episode reward | -7.7     |
| n_updates               | 28100    |
| qf1_loss                | 5.802578 |
| qf2_loss                | 5.880761 |
| success rate            | 0        |
| time_elapsed            | 51       |
| total timesteps         | 28200    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.63     |
| episodes                | 192       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -7.6      |
| n_updates               | 28700     |
| qf1_loss                | 5.4606075 |
| qf2_loss                | 5.5160494 |
| success rate            | 0         |
| time_elapsed            | 52        |
| total timesteps         | 28800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.66     |
| episodes                | 196       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -7.7      |
| n_updates               | 29300     |
| qf1_loss                | 4.726091  |
| qf2_loss                | 4.7413545 |
| success rate            | 0         |
| time_elapsed            | 53        |
| total timesteps         | 29400     |
---------------------------------------
Eval num_timesteps=30000, episode_reward=-12.37 +/- 6.18
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.29     |
| episodes                | 200       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -7.3      |
| n_updates               | 29900     |
| qf1_loss                | 4.551977  |
| qf2_loss                | 4.3925753 |
| success rate            | 0         |
| time_elapsed            | 54        |
| total timesteps         | 30000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.58     |
| episodes                | 204       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -7.6      |
| n_updates               | 30500     |
| qf1_loss                | 3.9908128 |
| qf2_loss                | 4.0639462 |
| success rate            | 0         |
| time_elapsed            | 56        |
| total timesteps         | 30600     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -7.38    |
| episodes                | 208      |
| eplenmean               | 150      |
| fps                     | 546      |
| mean 100 episode reward | -7.4     |
| n_updates               | 31100    |
| qf1_loss                | 4.146829 |
| qf2_loss                | 4.238937 |
| success rate            | 0        |
| time_elapsed            | 57       |
| total timesteps         | 31200    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.29     |
| episodes                | 212       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -6.3      |
| n_updates               | 31700     |
| qf1_loss                | 3.9385307 |
| qf2_loss                | 3.8990057 |
| success rate            | 0         |
| time_elapsed            | 58        |
| total timesteps         | 31800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.02     |
| episodes                | 216       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -6        |
| n_updates               | 32300     |
| qf1_loss                | 5.1507373 |
| qf2_loss                | 5.0153317 |
| success rate            | 0         |
| time_elapsed            | 59        |
| total timesteps         | 32400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.57     |
| episodes                | 220       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -4.6      |
| n_updates               | 32900     |
| qf1_loss                | 4.7227755 |
| qf2_loss                | 4.5117555 |
| success rate            | 0         |
| time_elapsed            | 60        |
| total timesteps         | 33000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.21     |
| episodes                | 224       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -4.2      |
| n_updates               | 33500     |
| qf1_loss                | 4.6040454 |
| qf2_loss                | 4.575868  |
| success rate            | 0         |
| time_elapsed            | 61        |
| total timesteps         | 33600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.01     |
| episodes                | 228       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -4        |
| n_updates               | 34100     |
| qf1_loss                | 3.7606661 |
| qf2_loss                | 3.6914115 |
| success rate            | 0         |
| time_elapsed            | 62        |
| total timesteps         | 34200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.75     |
| episodes                | 232       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -2.7      |
| n_updates               | 34700     |
| qf1_loss                | 4.0795903 |
| qf2_loss                | 4.0492764 |
| success rate            | 0         |
| time_elapsed            | 63        |
| total timesteps         | 34800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.95     |
| episodes                | 236       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -2.9      |
| n_updates               | 35300     |
| qf1_loss                | 4.0625243 |
| qf2_loss                | 4.0865445 |
| success rate            | 0         |
| time_elapsed            | 64        |
| total timesteps         | 35400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.48     |
| episodes                | 240       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -2.5      |
| n_updates               | 35900     |
| qf1_loss                | 4.3607554 |
| qf2_loss                | 4.279122  |
| success rate            | 0         |
| time_elapsed            | 65        |
| total timesteps         | 36000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.68     |
| episodes                | 244       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -2.7      |
| n_updates               | 36500     |
| qf1_loss                | 3.9282484 |
| qf2_loss                | 3.9381845 |
| success rate            | 0         |
| time_elapsed            | 66        |
| total timesteps         | 36600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -3.19     |
| episodes                | 248       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -3.2      |
| n_updates               | 37100     |
| qf1_loss                | 4.2742877 |
| qf2_loss                | 4.290841  |
| success rate            | 0         |
| time_elapsed            | 67        |
| total timesteps         | 37200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -3.65     |
| episodes                | 252       |
| eplenmean               | 150       |
| fps                     | 548       |
| mean 100 episode reward | -3.7      |
| n_updates               | 37700     |
| qf1_loss                | 5.037992  |
| qf2_loss                | 4.9411225 |
| success rate            | 0         |
| time_elapsed            | 68        |
| total timesteps         | 37800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.03     |
| episodes                | 256       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -4        |
| n_updates               | 38300     |
| qf1_loss                | 4.5392995 |
| qf2_loss                | 4.49426   |
| success rate            | 0         |
| time_elapsed            | 69        |
| total timesteps         | 38400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.67     |
| episodes                | 260       |
| eplenmean               | 150       |
| fps                     | 549       |
| mean 100 episode reward | -4.7      |
| n_updates               | 38900     |
| qf1_loss                | 4.179324  |
| qf2_loss                | 4.1933155 |
| success rate            | 0         |
| time_elapsed            | 70        |
| total timesteps         | 39000     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -4.69    |
| episodes                | 264      |
| eplenmean               | 150      |
| fps                     | 549      |
| mean 100 episode reward | -4.7     |
| n_updates               | 39500    |
| qf1_loss                | 4.801335 |
| qf2_loss                | 4.788044 |
| success rate            | 0        |
| time_elapsed            | 72       |
| total timesteps         | 39600    |
--------------------------------------
Eval num_timesteps=40000, episode_reward=-8.35 +/- 4.98
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -5.28     |
| episodes                | 268       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -5.3      |
| n_updates               | 40100     |
| qf1_loss                | 3.8888967 |
| qf2_loss                | 3.8950686 |
| success rate            | 0         |
| time_elapsed            | 73        |
| total timesteps         | 40200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.01     |
| episodes                | 272       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6        |
| n_updates               | 40700     |
| qf1_loss                | 5.099088  |
| qf2_loss                | 5.0665455 |
| success rate            | 0         |
| time_elapsed            | 74        |
| total timesteps         | 40800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.21     |
| episodes                | 276       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6.2      |
| n_updates               | 41300     |
| qf1_loss                | 3.4073672 |
| qf2_loss                | 3.4151304 |
| success rate            | 0         |
| time_elapsed            | 75        |
| total timesteps         | 41400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.55     |
| episodes                | 280       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6.5      |
| n_updates               | 41900     |
| qf1_loss                | 3.471905  |
| qf2_loss                | 3.4305122 |
| success rate            | 0         |
| time_elapsed            | 76        |
| total timesteps         | 42000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.34     |
| episodes                | 284       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6.3      |
| n_updates               | 42500     |
| qf1_loss                | 3.3985367 |
| qf2_loss                | 3.3179455 |
| success rate            | 0         |
| time_elapsed            | 77        |
| total timesteps         | 42600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.46     |
| episodes                | 288       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6.5      |
| n_updates               | 43100     |
| qf1_loss                | 3.9880207 |
| qf2_loss                | 4.0622063 |
| success rate            | 0         |
| time_elapsed            | 78        |
| total timesteps         | 43200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.61     |
| episodes                | 292       |
| eplenmean               | 150       |
| fps                     | 547       |
| mean 100 episode reward | -6.6      |
| n_updates               | 43700     |
| qf1_loss                | 3.5446043 |
| qf2_loss                | 3.6393836 |
| success rate            | 0         |
| time_elapsed            | 80        |
| total timesteps         | 43800     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -7.18    |
| episodes                | 296      |
| eplenmean               | 150      |
| fps                     | 546      |
| mean 100 episode reward | -7.2     |
| n_updates               | 44300    |
| qf1_loss                | 4.48611  |
| qf2_loss                | 4.562781 |
| success rate            | 0        |
| time_elapsed            | 81       |
| total timesteps         | 44400    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.45     |
| episodes                | 300       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -7.4      |
| n_updates               | 44900     |
| qf1_loss                | 4.0797486 |
| qf2_loss                | 4.138661  |
| success rate            | 0         |
| time_elapsed            | 82        |
| total timesteps         | 45000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.67     |
| episodes                | 304       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -7.7      |
| n_updates               | 45500     |
| qf1_loss                | 3.4779227 |
| qf2_loss                | 3.4685502 |
| success rate            | 0         |
| time_elapsed            | 83        |
| total timesteps         | 45600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.85     |
| episodes                | 308       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -7.9      |
| n_updates               | 46100     |
| qf1_loss                | 3.5588942 |
| qf2_loss                | 3.4584064 |
| success rate            | 0         |
| time_elapsed            | 84        |
| total timesteps         | 46200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.4      |
| episodes                | 312       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -8.4      |
| n_updates               | 46700     |
| qf1_loss                | 3.4418383 |
| qf2_loss                | 3.3356586 |
| success rate            | 0         |
| time_elapsed            | 85        |
| total timesteps         | 46800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.45     |
| episodes                | 316       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -8.4      |
| n_updates               | 47300     |
| qf1_loss                | 3.7725043 |
| qf2_loss                | 3.6736207 |
| success rate            | 0         |
| time_elapsed            | 86        |
| total timesteps         | 47400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.26     |
| episodes                | 320       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -8.3      |
| n_updates               | 47900     |
| qf1_loss                | 4.0591707 |
| qf2_loss                | 4.0051503 |
| success rate            | 0         |
| time_elapsed            | 87        |
| total timesteps         | 48000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.06     |
| episodes                | 324       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -8.1      |
| n_updates               | 48500     |
| qf1_loss                | 4.353123  |
| qf2_loss                | 4.2203584 |
| success rate            | 0         |
| time_elapsed            | 89        |
| total timesteps         | 48600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.95     |
| episodes                | 328       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -8        |
| n_updates               | 49100     |
| qf1_loss                | 3.2596316 |
| qf2_loss                | 3.133531  |
| success rate            | 0         |
| time_elapsed            | 90        |
| total timesteps         | 49200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.85     |
| episodes                | 332       |
| eplenmean               | 150       |
| fps                     | 546       |
| mean 100 episode reward | -7.8      |
| n_updates               | 49700     |
| qf1_loss                | 4.3721113 |
| qf2_loss                | 4.189329  |
| success rate            | 0         |
| time_elapsed            | 91        |
| total timesteps         | 49800     |
---------------------------------------
Eval num_timesteps=50000, episode_reward=-0.92 +/- 13.25
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.93     |
| episodes                | 336       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -7.9      |
| n_updates               | 50300     |
| qf1_loss                | 3.3982346 |
| qf2_loss                | 3.4087644 |
| success rate            | 0         |
| time_elapsed            | 92        |
| total timesteps         | 50400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.69     |
| episodes                | 340       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -8.7      |
| n_updates               | 50900     |
| qf1_loss                | 4.1793447 |
| qf2_loss                | 4.266407  |
| success rate            | 0         |
| time_elapsed            | 93        |
| total timesteps         | 51000     |
---------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -8.89    |
| episodes                | 344      |
| eplenmean               | 150      |
| fps                     | 544      |
| mean 100 episode reward | -8.9     |
| n_updates               | 51500    |
| qf1_loss                | 4.108248 |
| qf2_loss                | 4.071272 |
| success rate            | 0        |
| time_elapsed            | 94       |
| total timesteps         | 51600    |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -9.13    |
| episodes                | 348      |
| eplenmean               | 150      |
| fps                     | 544      |
| mean 100 episode reward | -9.1     |
| n_updates               | 52100    |
| qf1_loss                | 3.067497 |
| qf2_loss                | 3.070039 |
| success rate            | 0        |
| time_elapsed            | 95       |
| total timesteps         | 52200    |
--------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -9.66    |
| episodes                | 352      |
| eplenmean               | 150      |
| fps                     | 544      |
| mean 100 episode reward | -9.7     |
| n_updates               | 52700    |
| qf1_loss                | 3.979723 |
| qf2_loss                | 3.863192 |
| success rate            | 0        |
| time_elapsed            | 96       |
| total timesteps         | 52800    |
--------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.74     |
| episodes                | 356       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -9.7      |
| n_updates               | 53300     |
| qf1_loss                | 3.082214  |
| qf2_loss                | 3.0226858 |
| success rate            | 0         |
| time_elapsed            | 98        |
| total timesteps         | 53400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.96     |
| episodes                | 360       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -10       |
| n_updates               | 53900     |
| qf1_loss                | 3.3118126 |
| qf2_loss                | 3.3500204 |
| success rate            | 0         |
| time_elapsed            | 99        |
| total timesteps         | 54000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -10.2     |
| episodes                | 364       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -10.2     |
| n_updates               | 54500     |
| qf1_loss                | 3.4837332 |
| qf2_loss                | 3.3165858 |
| success rate            | 0         |
| time_elapsed            | 100       |
| total timesteps         | 54600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -10.2     |
| episodes                | 368       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -10.2     |
| n_updates               | 55100     |
| qf1_loss                | 2.5473793 |
| qf2_loss                | 2.5300531 |
| success rate            | 0         |
| time_elapsed            | 101       |
| total timesteps         | 55200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -10       |
| episodes                | 372       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -10       |
| n_updates               | 55700     |
| qf1_loss                | 2.0055966 |
| qf2_loss                | 1.9386121 |
| success rate            | 0         |
| time_elapsed            | 102       |
| total timesteps         | 55800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.54     |
| episodes                | 376       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -9.5      |
| n_updates               | 56300     |
| qf1_loss                | 2.4733527 |
| qf2_loss                | 2.4029663 |
| success rate            | 0         |
| time_elapsed            | 103       |
| total timesteps         | 56400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.93     |
| episodes                | 380       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -9.9      |
| n_updates               | 56900     |
| qf1_loss                | 1.8973988 |
| qf2_loss                | 1.8999791 |
| success rate            | 0         |
| time_elapsed            | 104       |
| total timesteps         | 57000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -10.1     |
| episodes                | 384       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -10.1     |
| n_updates               | 57500     |
| qf1_loss                | 2.7683117 |
| qf2_loss                | 2.663367  |
| success rate            | 0         |
| time_elapsed            | 105       |
| total timesteps         | 57600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.57     |
| episodes                | 388       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -9.6      |
| n_updates               | 58100     |
| qf1_loss                | 2.0256174 |
| qf2_loss                | 1.9602658 |
| success rate            | 0         |
| time_elapsed            | 106       |
| total timesteps         | 58200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.34     |
| episodes                | 392       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -9.3      |
| n_updates               | 58700     |
| qf1_loss                | 2.2099423 |
| qf2_loss                | 2.1523428 |
| success rate            | 0         |
| time_elapsed            | 107       |
| total timesteps         | 58800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.7      |
| episodes                | 396       |
| eplenmean               | 150       |
| fps                     | 545       |
| mean 100 episode reward | -8.7      |
| n_updates               | 59300     |
| qf1_loss                | 1.829572  |
| qf2_loss                | 1.7651815 |
| success rate            | 0         |
| time_elapsed            | 108       |
| total timesteps         | 59400     |
---------------------------------------
Eval num_timesteps=60000, episode_reward=-9.17 +/- 6.22
Episode length: 150.00 +/- 0.00
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -9.05     |
| episodes                | 400       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -9.1      |
| n_updates               | 59900     |
| qf1_loss                | 1.9470766 |
| qf2_loss                | 1.9007089 |
| success rate            | 0         |
| time_elapsed            | 110       |
| total timesteps         | 60000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.71     |
| episodes                | 404       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -8.7      |
| n_updates               | 60500     |
| qf1_loss                | 1.9093754 |
| qf2_loss                | 1.8527646 |
| success rate            | 0         |
| time_elapsed            | 111       |
| total timesteps         | 60600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.33     |
| episodes                | 408       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -8.3      |
| n_updates               | 61100     |
| qf1_loss                | 1.3482671 |
| qf2_loss                | 1.271397  |
| success rate            | 0         |
| time_elapsed            | 112       |
| total timesteps         | 61200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.05     |
| episodes                | 412       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -8.1      |
| n_updates               | 61700     |
| qf1_loss                | 1.349885  |
| qf2_loss                | 1.3028826 |
| success rate            | 0         |
| time_elapsed            | 113       |
| total timesteps         | 61800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.42     |
| episodes                | 416       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -7.4      |
| n_updates               | 62300     |
| qf1_loss                | 1.4299048 |
| qf2_loss                | 1.3764663 |
| success rate            | 0         |
| time_elapsed            | 114       |
| total timesteps         | 62400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.6      |
| episodes                | 420       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -7.6      |
| n_updates               | 62900     |
| qf1_loss                | 1.0876019 |
| qf2_loss                | 1.0258723 |
| success rate            | 0         |
| time_elapsed            | 116       |
| total timesteps         | 63000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.76     |
| episodes                | 424       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -7.8      |
| n_updates               | 63500     |
| qf1_loss                | 1.3185375 |
| qf2_loss                | 1.2321824 |
| success rate            | 0         |
| time_elapsed            | 117       |
| total timesteps         | 63600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.12     |
| episodes                | 428       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -8.1      |
| n_updates               | 64100     |
| qf1_loss                | 1.2653911 |
| qf2_loss                | 1.2544875 |
| success rate            | 0         |
| time_elapsed            | 118       |
| total timesteps         | 64200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -8.04     |
| episodes                | 432       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -8        |
| n_updates               | 64700     |
| qf1_loss                | 1.363684  |
| qf2_loss                | 1.2926152 |
| success rate            | 0         |
| time_elapsed            | 119       |
| total timesteps         | 64800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -7.5      |
| episodes                | 436       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -7.5      |
| n_updates               | 65300     |
| qf1_loss                | 1.2387909 |
| qf2_loss                | 1.1788261 |
| success rate            | 0         |
| time_elapsed            | 120       |
| total timesteps         | 65400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -6.72     |
| episodes                | 440       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -6.7      |
| n_updates               | 65900     |
| qf1_loss                | 1.336059  |
| qf2_loss                | 1.3184761 |
| success rate            | 0         |
| time_elapsed            | 121       |
| total timesteps         | 66000     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -5.65     |
| episodes                | 444       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -5.6      |
| n_updates               | 66500     |
| qf1_loss                | 1.0932641 |
| qf2_loss                | 1.0412705 |
| success rate            | 0         |
| time_elapsed            | 122       |
| total timesteps         | 66600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -4.7      |
| episodes                | 448       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -4.7      |
| n_updates               | 67100     |
| qf1_loss                | 1.3259882 |
| qf2_loss                | 1.267847  |
| success rate            | 0         |
| time_elapsed            | 123       |
| total timesteps         | 67200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -3.7      |
| episodes                | 452       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -3.7      |
| n_updates               | 67700     |
| qf1_loss                | 1.50374   |
| qf2_loss                | 1.4616531 |
| success rate            | 0         |
| time_elapsed            | 124       |
| total timesteps         | 67800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -3.55     |
| episodes                | 456       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -3.5      |
| n_updates               | 68300     |
| qf1_loss                | 1.12424   |
| qf2_loss                | 1.0698491 |
| success rate            | 0         |
| time_elapsed            | 126       |
| total timesteps         | 68400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -3.2      |
| episodes                | 460       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -3.2      |
| n_updates               | 68900     |
| qf1_loss                | 1.1118697 |
| qf2_loss                | 1.0699356 |
| success rate            | 0         |
| time_elapsed            | 127       |
| total timesteps         | 69000     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -3.02      |
| episodes                | 464        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -3         |
| n_updates               | 69500      |
| qf1_loss                | 0.80559427 |
| qf2_loss                | 0.7682287  |
| success rate            | 0          |
| time_elapsed            | 128        |
| total timesteps         | 69600      |
----------------------------------------
Eval num_timesteps=70000, episode_reward=3.27 +/- 3.92
Episode length: 150.00 +/- 0.00
New best mean reward!
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.11     |
| episodes                | 468       |
| eplenmean               | 150       |
| fps                     | 541       |
| mean 100 episode reward | -2.1      |
| n_updates               | 70100     |
| qf1_loss                | 1.0167941 |
| qf2_loss                | 0.9845128 |
| success rate            | 0         |
| time_elapsed            | 129       |
| total timesteps         | 70200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.71     |
| episodes                | 472       |
| eplenmean               | 150       |
| fps                     | 541       |
| mean 100 episode reward | -1.7      |
| n_updates               | 70700     |
| qf1_loss                | 1.0953927 |
| qf2_loss                | 1.0610397 |
| success rate            | 0         |
| time_elapsed            | 130       |
| total timesteps         | 70800     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.68      |
| episodes                | 476        |
| eplenmean               | 150        |
| fps                     | 541        |
| mean 100 episode reward | -1.7       |
| n_updates               | 71300      |
| qf1_loss                | 0.9535007  |
| qf2_loss                | 0.89490944 |
| success rate            | 0          |
| time_elapsed            | 131        |
| total timesteps         | 71400      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.2      |
| episodes                | 480       |
| eplenmean               | 150       |
| fps                     | 541       |
| mean 100 episode reward | -1.2      |
| n_updates               | 71900     |
| qf1_loss                | 1.0899541 |
| qf2_loss                | 1.0314243 |
| success rate            | 0         |
| time_elapsed            | 132       |
| total timesteps         | 72000     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.25      |
| episodes                | 484        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.2       |
| n_updates               | 72500      |
| qf1_loss                | 1.027122   |
| qf2_loss                | 0.97184473 |
| success rate            | 0          |
| time_elapsed            | 133        |
| total timesteps         | 72600      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.47     |
| episodes                | 488       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.5      |
| n_updates               | 73100     |
| qf1_loss                | 1.0856003 |
| qf2_loss                | 1.0564029 |
| success rate            | 0         |
| time_elapsed            | 135       |
| total timesteps         | 73200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.6      |
| episodes                | 492       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.6      |
| n_updates               | 73700     |
| qf1_loss                | 0.8829637 |
| qf2_loss                | 0.838002  |
| success rate            | 0         |
| time_elapsed            | 136       |
| total timesteps         | 73800     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.66      |
| episodes                | 496        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.7       |
| n_updates               | 74300      |
| qf1_loss                | 0.93618613 |
| qf2_loss                | 0.90271705 |
| success rate            | 0          |
| time_elapsed            | 137        |
| total timesteps         | 74400      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.22      |
| episodes                | 500        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.2       |
| n_updates               | 74900      |
| qf1_loss                | 0.67999285 |
| qf2_loss                | 0.6442701  |
| success rate            | 0          |
| time_elapsed            | 138        |
| total timesteps         | 75000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.31     |
| episodes                | 504       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.3      |
| n_updates               | 75500     |
| qf1_loss                | 0.8876729 |
| qf2_loss                | 0.8718113 |
| success rate            | 0         |
| time_elapsed            | 139       |
| total timesteps         | 75600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.21     |
| episodes                | 508       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -1.2      |
| n_updates               | 76100     |
| qf1_loss                | 0.8319621 |
| qf2_loss                | 0.7672589 |
| success rate            | 0         |
| time_elapsed            | 140       |
| total timesteps         | 76200     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -0.985    |
| episodes                | 512       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -1        |
| n_updates               | 76700     |
| qf1_loss                | 0.788654  |
| qf2_loss                | 0.7340282 |
| success rate            | 0         |
| time_elapsed            | 141       |
| total timesteps         | 76800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.25     |
| episodes                | 516       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -1.2      |
| n_updates               | 77300     |
| qf1_loss                | 0.8621507 |
| qf2_loss                | 0.8164077 |
| success rate            | 0         |
| time_elapsed            | 142       |
| total timesteps         | 77400     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.02      |
| episodes                | 520        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -1         |
| n_updates               | 77900      |
| qf1_loss                | 0.7624495  |
| qf2_loss                | 0.71969223 |
| success rate            | 0          |
| time_elapsed            | 143        |
| total timesteps         | 78000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -0.755    |
| episodes                | 524       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -0.8      |
| n_updates               | 78500     |
| qf1_loss                | 0.6313011 |
| qf2_loss                | 0.6085894 |
| success rate            | 0         |
| time_elapsed            | 144       |
| total timesteps         | 78600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -0.198     |
| episodes                | 528        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -0.2       |
| n_updates               | 79100      |
| qf1_loss                | 0.59865886 |
| qf2_loss                | 0.5750165  |
| success rate            | 0          |
| time_elapsed            | 145        |
| total timesteps         | 79200      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | 0.0937     |
| episodes                | 532        |
| eplenmean               | 150        |
| fps                     | 544        |
| mean 100 episode reward | 0.1        |
| n_updates               | 79700      |
| qf1_loss                | 0.7465755  |
| qf2_loss                | 0.72082984 |
| success rate            | 0          |
| time_elapsed            | 146        |
| total timesteps         | 79800      |
----------------------------------------
Eval num_timesteps=80000, episode_reward=-2.90 +/- 10.65
Episode length: 150.00 +/- 0.00
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -0.8      |
| episodes                | 536       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -0.8      |
| n_updates               | 80300     |
| qf1_loss                | 0.7023537 |
| qf2_loss                | 0.6711717 |
| success rate            | 0         |
| time_elapsed            | 148       |
| total timesteps         | 80400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -0.731    |
| episodes                | 540       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -0.7      |
| n_updates               | 80900     |
| qf1_loss                | 0.7224751 |
| qf2_loss                | 0.6788462 |
| success rate            | 0         |
| time_elapsed            | 149       |
| total timesteps         | 81000     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.18      |
| episodes                | 544        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -1.2       |
| n_updates               | 81500      |
| qf1_loss                | 0.795377   |
| qf2_loss                | 0.77207476 |
| success rate            | 0          |
| time_elapsed            | 150        |
| total timesteps         | 81600      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.09      |
| episodes                | 548        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -1.1       |
| n_updates               | 82100      |
| qf1_loss                | 0.6436197  |
| qf2_loss                | 0.62761676 |
| success rate            | 0          |
| time_elapsed            | 151        |
| total timesteps         | 82200      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.18     |
| episodes                | 552       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -1.2      |
| n_updates               | 82700     |
| qf1_loss                | 0.6435448 |
| qf2_loss                | 0.6167118 |
| success rate            | 0         |
| time_elapsed            | 152       |
| total timesteps         | 82800     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.3      |
| episodes                | 556       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -1.3      |
| n_updates               | 83300     |
| qf1_loss                | 0.6423301 |
| qf2_loss                | 0.6116651 |
| success rate            | 0         |
| time_elapsed            | 153       |
| total timesteps         | 83400     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -0.843    |
| episodes                | 560       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -0.8      |
| n_updates               | 83900     |
| qf1_loss                | 0.5751184 |
| qf2_loss                | 0.5569616 |
| success rate            | 0         |
| time_elapsed            | 154       |
| total timesteps         | 84000     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -0.896     |
| episodes                | 564        |
| eplenmean               | 150        |
| fps                     | 544        |
| mean 100 episode reward | -0.9       |
| n_updates               | 84500      |
| qf1_loss                | 0.7019779  |
| qf2_loss                | 0.69938475 |
| success rate            | 0          |
| time_elapsed            | 155        |
| total timesteps         | 84600      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.63     |
| episodes                | 568       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -1.6      |
| n_updates               | 85100     |
| qf1_loss                | 0.5770493 |
| qf2_loss                | 0.5487009 |
| success rate            | 0         |
| time_elapsed            | 156       |
| total timesteps         | 85200     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.74      |
| episodes                | 572        |
| eplenmean               | 150        |
| fps                     | 544        |
| mean 100 episode reward | -1.7       |
| n_updates               | 85700      |
| qf1_loss                | 0.6185027  |
| qf2_loss                | 0.59778094 |
| success rate            | 0          |
| time_elapsed            | 157        |
| total timesteps         | 85800      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.79     |
| episodes                | 576       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -1.8      |
| n_updates               | 86300     |
| qf1_loss                | 0.6317737 |
| qf2_loss                | 0.611114  |
| success rate            | 0         |
| time_elapsed            | 158       |
| total timesteps         | 86400     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.58      |
| episodes                | 580        |
| eplenmean               | 150        |
| fps                     | 544        |
| mean 100 episode reward | -1.6       |
| n_updates               | 86900      |
| qf1_loss                | 0.5103344  |
| qf2_loss                | 0.49564004 |
| success rate            | 0          |
| time_elapsed            | 159        |
| total timesteps         | 87000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.69     |
| episodes                | 584       |
| eplenmean               | 150       |
| fps                     | 544       |
| mean 100 episode reward | -1.7      |
| n_updates               | 87500     |
| qf1_loss                | 0.5911987 |
| qf2_loss                | 0.5763958 |
| success rate            | 0         |
| time_elapsed            | 160       |
| total timesteps         | 87600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.7       |
| episodes                | 588        |
| eplenmean               | 150        |
| fps                     | 544        |
| mean 100 episode reward | -1.7       |
| n_updates               | 88100      |
| qf1_loss                | 0.5060862  |
| qf2_loss                | 0.48383975 |
| success rate            | 0          |
| time_elapsed            | 161        |
| total timesteps         | 88200      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.51      |
| episodes                | 592        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -1.5       |
| n_updates               | 88700      |
| qf1_loss                | 0.68818617 |
| qf2_loss                | 0.65199137 |
| success rate            | 0          |
| time_elapsed            | 163        |
| total timesteps         | 88800      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.46      |
| episodes                | 596        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -1.5       |
| n_updates               | 89300      |
| qf1_loss                | 0.59694016 |
| qf2_loss                | 0.59268665 |
| success rate            | 0          |
| time_elapsed            | 164        |
| total timesteps         | 89400      |
----------------------------------------
Eval num_timesteps=90000, episode_reward=4.30 +/- 6.14
Episode length: 150.00 +/- 0.00
New best mean reward!
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.54      |
| episodes                | 600        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.5       |
| n_updates               | 89900      |
| qf1_loss                | 0.5482147  |
| qf2_loss                | 0.52958655 |
| success rate            | 0          |
| time_elapsed            | 165        |
| total timesteps         | 90000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.33     |
| episodes                | 604       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.3      |
| n_updates               | 90500     |
| qf1_loss                | 0.7036596 |
| qf2_loss                | 0.6881511 |
| success rate            | 0         |
| time_elapsed            | 167       |
| total timesteps         | 90600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.29      |
| episodes                | 608        |
| eplenmean               | 150        |
| fps                     | 541        |
| mean 100 episode reward | -1.3       |
| n_updates               | 91100      |
| qf1_loss                | 0.6873495  |
| qf2_loss                | 0.66018397 |
| success rate            | 0          |
| time_elapsed            | 168        |
| total timesteps         | 91200      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.55      |
| episodes                | 612        |
| eplenmean               | 150        |
| fps                     | 541        |
| mean 100 episode reward | -1.6       |
| n_updates               | 91700      |
| qf1_loss                | 0.7148876  |
| qf2_loss                | 0.68272585 |
| success rate            | 0          |
| time_elapsed            | 169        |
| total timesteps         | 91800      |
----------------------------------------
--------------------------------------
| current_lr              | 0.0003   |
| ep_rewmean              | -1.42    |
| episodes                | 616      |
| eplenmean               | 150      |
| fps                     | 542      |
| mean 100 episode reward | -1.4     |
| n_updates               | 92300    |
| qf1_loss                | 0.731099 |
| qf2_loss                | 0.717019 |
| success rate            | 0        |
| time_elapsed            | 170      |
| total timesteps         | 92400    |
--------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.22      |
| episodes                | 620        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.2       |
| n_updates               | 92900      |
| qf1_loss                | 0.58903074 |
| qf2_loss                | 0.5586402  |
| success rate            | 0          |
| time_elapsed            | 171        |
| total timesteps         | 93000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.49     |
| episodes                | 624       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.5      |
| n_updates               | 93500     |
| qf1_loss                | 0.7143051 |
| qf2_loss                | 0.6989416 |
| success rate            | 0         |
| time_elapsed            | 172       |
| total timesteps         | 93600     |
---------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.83     |
| episodes                | 628       |
| eplenmean               | 150       |
| fps                     | 542       |
| mean 100 episode reward | -1.8      |
| n_updates               | 94100     |
| qf1_loss                | 0.5314683 |
| qf2_loss                | 0.5070248 |
| success rate            | 0         |
| time_elapsed            | 173       |
| total timesteps         | 94200     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -2.24      |
| episodes                | 632        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -2.2       |
| n_updates               | 94700      |
| qf1_loss                | 0.5340209  |
| qf2_loss                | 0.50905687 |
| success rate            | 0          |
| time_elapsed            | 174        |
| total timesteps         | 94800      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -1.69      |
| episodes                | 636        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -1.7       |
| n_updates               | 95300      |
| qf1_loss                | 0.64210546 |
| qf2_loss                | 0.6102227  |
| success rate            | 0          |
| time_elapsed            | 175        |
| total timesteps         | 95400      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -2.13      |
| episodes                | 640        |
| eplenmean               | 150        |
| fps                     | 542        |
| mean 100 episode reward | -2.1       |
| n_updates               | 95900      |
| qf1_loss                | 0.51426905 |
| qf2_loss                | 0.48049432 |
| success rate            | 0          |
| time_elapsed            | 176        |
| total timesteps         | 96000      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -1.97     |
| episodes                | 644       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -2        |
| n_updates               | 96500     |
| qf1_loss                | 0.5955061 |
| qf2_loss                | 0.562791  |
| success rate            | 0         |
| time_elapsed            | 177       |
| total timesteps         | 96600     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -2.47      |
| episodes                | 648        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -2.5       |
| n_updates               | 97100      |
| qf1_loss                | 0.71825606 |
| qf2_loss                | 0.682757   |
| success rate            | 0          |
| time_elapsed            | 178        |
| total timesteps         | 97200      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -2.65      |
| episodes                | 652        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -2.7       |
| n_updates               | 97700      |
| qf1_loss                | 0.63342196 |
| qf2_loss                | 0.5992026  |
| success rate            | 0          |
| time_elapsed            | 180        |
| total timesteps         | 97800      |
----------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -2.55      |
| episodes                | 656        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -2.6       |
| n_updates               | 98300      |
| qf1_loss                | 0.59715545 |
| qf2_loss                | 0.5770208  |
| success rate            | 0          |
| time_elapsed            | 181        |
| total timesteps         | 98400      |
----------------------------------------
---------------------------------------
| current_lr              | 0.0003    |
| ep_rewmean              | -2.97     |
| episodes                | 660       |
| eplenmean               | 150       |
| fps                     | 543       |
| mean 100 episode reward | -3        |
| n_updates               | 98900     |
| qf1_loss                | 0.6985136 |
| qf2_loss                | 0.674821  |
| success rate            | 0         |
| time_elapsed            | 182       |
| total timesteps         | 99000     |
---------------------------------------
----------------------------------------
| current_lr              | 0.0003     |
| ep_rewmean              | -3.01      |
| episodes                | 664        |
| eplenmean               | 150        |
| fps                     | 543        |
| mean 100 episode reward | -3         |
| n_updates               | 99500      |
| qf1_loss                | 0.76491797 |
| qf2_loss                | 0.8358749  |
| success rate            | 0          |
| time_elapsed            | 183        |
| total timesteps         | 99600      |
----------------------------------------
Eval num_timesteps=100000, episode_reward=-1.83 +/- 8.93
Episode length: 150.00 +/- 0.00
Saving to logs/train_0.1M_Reacher2Dof-v0/td3/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
