WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_envs', 8),
             ('n_timesteps', 1000000.0),
             ('policy', 'MlpPolicy')])
Using 8 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:190: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:198: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:206: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:240: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:242: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_2
--------------------------------------
| approxkl           | 0.001210888   |
| clipfrac           | 0.0078125     |
| explained_variance | -0.00112      |
| fps                | 1502          |
| n_updates          | 1             |
| policy_entropy     | 2.8366683     |
| policy_loss        | -0.0035386954 |
| serial_timesteps   | 128           |
| time_elapsed       | 1.26e-05      |
| total_timesteps    | 1024          |
| value_loss         | 15.055985     |
--------------------------------------
--------------------------------------
| approxkl           | 0.0006409327  |
| clipfrac           | 0.0009765625  |
| ep_len_mean        | 150           |
| ep_reward_mean     | -8.94         |
| explained_variance | -0.00403      |
| fps                | 3604          |
| n_updates          | 2             |
| policy_entropy     | 2.834007      |
| policy_loss        | -0.0024009626 |
| serial_timesteps   | 256           |
| time_elapsed       | 0.682         |
| total_timesteps    | 2048          |
| value_loss         | 18.30521      |
--------------------------------------
--------------------------------------
| approxkl           | 0.000657052   |
| clipfrac           | 0.0014648438  |
| ep_len_mean        | 150           |
| ep_reward_mean     | -12.3         |
| explained_variance | -0.00702      |
| fps                | 3661          |
| n_updates          | 3             |
| policy_entropy     | 2.8331094     |
| policy_loss        | -0.0014829086 |
| serial_timesteps   | 384           |
| time_elapsed       | 0.966         |
| total_timesteps    | 3072          |
| value_loss         | 18.03469      |
--------------------------------------
--------------------------------------
| approxkl           | 0.0005094321  |
| clipfrac           | 0.00048828125 |
| ep_len_mean        | 150           |
| ep_reward_mean     | -12.2         |
| explained_variance | 0.0119        |
| fps                | 3591          |
| n_updates          | 4             |
| policy_entropy     | 2.8328152     |
| policy_loss        | -0.0015056214 |
| serial_timesteps   | 512           |
| time_elapsed       | 1.25          |
| total_timesteps    | 4096          |
| value_loss         | 12.320984     |
--------------------------------------
--------------------------------------
| approxkl           | 5.1633822e-05 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -11.2         |
| explained_variance | 0.00259       |
| fps                | 3609          |
| n_updates          | 5             |
| policy_entropy     | 2.8328586     |
| policy_loss        | 0.00012740746 |
| serial_timesteps   | 640           |
| time_elapsed       | 1.53          |
| total_timesteps    | 5120          |
| value_loss         | 15.873835     |
--------------------------------------
---------------------------------------
| approxkl           | 2.2982462e-05  |
| clipfrac           | 0.0            |
| ep_len_mean        | 150            |
| ep_reward_mean     | -11.5          |
| explained_variance | 0.0102         |
| fps                | 3683           |
| n_updates          | 6              |
| policy_entropy     | 2.8334768      |
| policy_loss        | -0.00051100395 |
| serial_timesteps   | 768            |
| time_elapsed       | 1.81           |
| total_timesteps    | 6144           |
| value_loss         | 14.922783      |
---------------------------------------
--------------------------------------
| approxkl           | 0.0001391067  |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -11.5         |
| explained_variance | -0.0118       |
| fps                | 3686          |
| n_updates          | 7             |
| policy_entropy     | 2.8350627     |
| policy_loss        | -0.0006030461 |
| serial_timesteps   | 896           |
| time_elapsed       | 2.09          |
| total_timesteps    | 7168          |
| value_loss         | 13.024832     |
--------------------------------------
--------------------------------------
| approxkl           | 5.0261646e-05 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -10.9         |
| explained_variance | -0.00358      |
| fps                | 3560          |
| n_updates          | 8             |
| policy_entropy     | 2.8374965     |
| policy_loss        | 2.751901e-05  |
| serial_timesteps   | 1024          |
| time_elapsed       | 2.37          |
| total_timesteps    | 8192          |
| value_loss         | 15.161277     |
--------------------------------------
--------------------------------------
| approxkl           | 0.00017738379 |
| clipfrac           | 0.0           |
| ep_len_mean        | 150           |
| ep_reward_mean     | -11.7         |
| explained_variance | -0.000658     |
| fps                | 3589          |
| n_updates          | 9             |
| policy_entropy     | 2.836759      |
| policy_loss        | -0.0011531226 |
| serial_timesteps   | 1152          |
| time_elapsed       | 2.66          |
| total_timesteps    | 9216          |
| value_loss         | 14.37396      |
--------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/ppo2/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
