WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=100000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:407: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:241: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:242: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_0.1M_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f1f2a004630> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f1f2a004518>
  "{} != {}".format(self.training_env, self.eval_env))
********** Iteration 0 ************
Optimizing Policy...
sampling
done in 0.628 seconds
computegrad
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:364: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

done in 0.101 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0199          0
         1    0.00876     0.0762
         2    0.00389     0.0852
         3    0.00186      0.264
         4    0.00129      0.357
         5    0.00277      0.442
         6    0.00377      0.464
         7   0.000498      0.516
         8   0.000297      0.587
         9   0.000166      0.796
        10   0.000556       0.87
done in 0.162 seconds
Expected: 0.028 Actual: 0.027
Stepsize OK!
vf
done in 0.053 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.4       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 6           |
| TimeElapsed             | 1.02        |
| TimestepsSoFar          | 1024        |
| entloss                 | 0.0         |
| entropy                 | 2.8131082   |
| explained_variance_t... | 0.000682    |
| meankl                  | 0.008412986 |
| optimgain               | 0.026783172 |
| surrgain                | 0.026783172 |
-----------------------------------------
********** Iteration 1 ************
Optimizing Policy...
sampling
done in 0.567 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.192          0
         1     0.0349     0.0263
         2     0.0131      0.118
         3    0.00778      0.126
         4    0.00185      0.219
         5    0.00272      0.282
         6    0.00262      0.455
         7     0.0238      0.577
         8    0.00241      0.641
         9    0.00105      0.749
        10    0.00821      0.775
done in 0.013 seconds
Expected: 0.034 Actual: 0.035
Stepsize OK!
vf
done in 0.020 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -17.2      |
| EpThisIter              | 7          |
| EpisodesSoFar           | 13         |
| TimeElapsed             | 1.63       |
| TimestepsSoFar          | 2048       |
| entloss                 | 0.0        |
| entropy                 | 2.840604   |
| explained_variance_t... | 0.0275     |
| meankl                  | 0.01088435 |
| optimgain               | 0.03517913 |
| surrgain                | 0.03517913 |
----------------------------------------
********** Iteration 2 ************
Optimizing Policy...
sampling
done in 0.580 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0485          0
         1     0.0438     0.0282
         2     0.0147      0.155
         3     0.0339       0.19
         4    0.00407      0.254
         5    0.00503       0.33
         6    0.00231      0.448
         7    0.00161      0.518
         8    0.00358      0.595
         9    0.00768      0.618
        10    0.00263      0.749
done in 0.014 seconds
Expected: 0.035 Actual: 0.020
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 2.25        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 2.8381855   |
| explained_variance_t... | -0.00594    |
| meankl                  | 0.010138901 |
| optimgain               | 0.019722765 |
| surrgain                | 0.019722765 |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0595          0
         1     0.0289     0.0294
         2    0.00725      0.101
         3     0.0149      0.113
         4    0.00437      0.251
         5    0.00429      0.358
         6    0.00151      0.491
         7    0.00297      0.688
         8    0.00669      0.757
         9    0.00114      0.778
        10     0.0065      0.824
done in 0.017 seconds
Expected: 0.033 Actual: 0.032
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 27          |
| TimeElapsed             | 2.88        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 2.8388755   |
| explained_variance_t... | -0.0774     |
| meankl                  | 0.008196581 |
| optimgain               | 0.032154784 |
| surrgain                | 0.032154784 |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
sampling
done in 0.623 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0302          0
         1     0.0253     0.0186
         2     0.0119      0.096
         3    0.00576      0.106
         4    0.00263      0.176
         5     0.0082      0.437
         6    0.00249      0.651
         7    0.00217      0.737
         8    0.00895      0.817
         9    0.00179      0.838
        10    0.00341      0.986
done in 0.014 seconds
Expected: 0.031 Actual: 0.033
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 34          |
| TimeElapsed             | 3.55        |
| TimestepsSoFar          | 5120        |
| entloss                 | 0.0         |
| entropy                 | 2.8017294   |
| explained_variance_t... | 0.0238      |
| meankl                  | 0.009933328 |
| optimgain               | 0.033393174 |
| surrgain                | 0.033393174 |
-----------------------------------------
********** Iteration 5 ************
Optimizing Policy...
sampling
done in 0.574 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0217          0
         1     0.0485     0.0334
         2     0.0041     0.0817
         3     0.0154      0.101
         4    0.00355      0.138
         5    0.00738      0.252
         6    0.00437      0.452
         7    0.00287      0.619
         8    0.00253      0.728
         9      0.002      0.736
        10   0.000903      0.774
done in 0.014 seconds
Expected: 0.028 Actual: 0.025
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.5       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 4.16        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 2.8020353   |
| explained_variance_t... | 0.0291      |
| meankl                  | 0.010975767 |
| optimgain               | 0.025317544 |
| surrgain                | 0.025317544 |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
sampling
done in 0.632 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0678          0
         1     0.0441     0.0174
         2     0.0602     0.0698
         3     0.0042     0.0974
         4    0.00676      0.171
         5    0.00412      0.259
         6    0.00373      0.322
         7    0.00374      0.478
         8    0.00618      0.489
         9     0.0122      0.546
        10    0.00231      0.574
done in 0.013 seconds
Expected: 0.029 Actual: 0.026
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 47          |
| TimeElapsed             | 4.84        |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 2.751016    |
| explained_variance_t... | 0.0118      |
| meankl                  | 0.009831356 |
| optimgain               | 0.026479151 |
| surrgain                | 0.026479151 |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
sampling
done in 0.612 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0337          0
         1     0.0234     0.0113
         2     0.0324     0.0385
         3    0.00424     0.0772
         4    0.00505      0.207
         5    0.00377      0.284
         6    0.00428      0.397
         7     0.0608      0.521
         8    0.00259      0.614
         9     0.0039      0.717
        10    0.00227      0.729
done in 0.014 seconds
Expected: 0.028 Actual: 0.031
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 54          |
| TimeElapsed             | 5.5         |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 2.7503467   |
| explained_variance_t... | -0.0116     |
| meankl                  | 0.01164085  |
| optimgain               | 0.031032896 |
| surrgain                | 0.031032896 |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
sampling
done in 0.612 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0955          0
         1     0.0795     0.0115
         2      0.221     0.0656
         3     0.0057      0.151
         4    0.00457        0.2
         5    0.00523      0.303
         6    0.00676      0.415
         7    0.00517      0.419
         8    0.00361      0.506
         9     0.0192      0.528
        10    0.00543       0.65
done in 0.012 seconds
Expected: 0.035 Actual: 0.034
Stepsize OK!
vf
done in 0.018 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.8        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 61           |
| TimeElapsed             | 6.15         |
| TimestepsSoFar          | 9216         |
| entloss                 | 0.0          |
| entropy                 | 2.741152     |
| explained_variance_t... | 0.032        |
| meankl                  | 0.0074062515 |
| optimgain               | 0.033790573  |
| surrgain                | 0.033790573  |
------------------------------------------
********** Iteration 9 ************
Optimizing Policy...
sampling
Eval num_timesteps=9216, episode_reward=-4.97 +/- 8.40
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.071 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.116          0
         1     0.0679     0.0783
         2     0.0275     0.0906
         3     0.0262     0.0971
         4    0.00645      0.137
         5    0.00613      0.219
         6    0.00629      0.294
         7    0.00696      0.466
         8     0.0296      0.628
         9    0.00479       0.65
        10     0.0148      0.713
done in 0.014 seconds
Expected: 0.037 Actual: 0.038
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 68          |
| TimeElapsed             | 7.26        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 2.7226875   |
| explained_variance_t... | -0.0664     |
| meankl                  | 0.009705221 |
| optimgain               | 0.037632406 |
| surrgain                | 0.037632406 |
-----------------------------------------
********** Iteration 10 ************
Optimizing Policy...
sampling
done in 0.585 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0351          0
         1     0.0571     0.0194
         2      0.126     0.0571
         3    0.00569     0.0941
         4    0.00606       0.13
         5    0.00554       0.26
         6    0.00709      0.384
         7     0.0187      0.499
         8    0.00529       0.51
         9      0.031      0.699
        10    0.00483      0.745
done in 0.013 seconds
Expected: 0.031 Actual: 0.023
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 75          |
| TimeElapsed             | 7.89        |
| TimestepsSoFar          | 11264       |
| entloss                 | 0.0         |
| entropy                 | 2.6931179   |
| explained_variance_t... | -0.0497     |
| meankl                  | 0.009362694 |
| optimgain               | 0.023152342 |
| surrgain                | 0.023152342 |
-----------------------------------------
********** Iteration 11 ************
Optimizing Policy...
sampling
done in 0.587 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.378          0
         1     0.0399      0.016
         2     0.0881     0.0709
         3    0.00783     0.0987
         4    0.00771      0.141
         5    0.00738      0.204
         6    0.00522      0.358
         7     0.0373      0.394
         8    0.00276      0.431
         9     0.0138      0.592
        10     0.0121      0.621
done in 0.013 seconds
Expected: 0.034 Actual: 0.029
Stepsize OK!
vf
done in 0.019 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -13.1      |
| EpThisIter              | 6          |
| EpisodesSoFar           | 81         |
| TimeElapsed             | 8.52       |
| TimestepsSoFar          | 12288      |
| entloss                 | 0.0        |
| entropy                 | 2.6780982  |
| explained_variance_t... | -0.00956   |
| meankl                  | 0.00786973 |
| optimgain               | 0.02945829 |
| surrgain                | 0.02945829 |
----------------------------------------
********** Iteration 12 ************
Optimizing Policy...
sampling
done in 0.578 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.222          0
         1     0.0234     0.0142
         2     0.0242     0.0217
         3    0.00902     0.0775
         4    0.00644       0.16
         5    0.00828      0.301
         6    0.00664      0.475
         7    0.00345      0.546
         8     0.0218      0.568
         9    0.00211      0.599
        10    0.00851      0.646
done in 0.012 seconds
Expected: 0.031 Actual: 0.031
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 88          |
| TimeElapsed             | 9.14        |
| TimestepsSoFar          | 13312       |
| entloss                 | 0.0         |
| entropy                 | 2.6772985   |
| explained_variance_t... | 0.0111      |
| meankl                  | 0.011364594 |
| optimgain               | 0.030522328 |
| surrgain                | 0.030522328 |
-----------------------------------------
********** Iteration 13 ************
Optimizing Policy...
sampling
done in 0.590 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.286          0
         1     0.0397     0.0188
         2       0.15     0.0314
         3      0.024     0.0811
         4     0.0108      0.176
         5    0.00474      0.265
         6    0.00614      0.361
         7     0.0675      0.386
         8     0.0129       0.45
         9    0.00573      0.461
        10    0.00211       0.54
done in 0.016 seconds
Expected: 0.035 Actual: 0.036
Stepsize OK!
vf
done in 0.027 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.4       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 95          |
| TimeElapsed             | 9.79        |
| TimestepsSoFar          | 14336       |
| entloss                 | 0.0         |
| entropy                 | 2.675204    |
| explained_variance_t... | 0.0342      |
| meankl                  | 0.013117464 |
| optimgain               | 0.036245402 |
| surrgain                | 0.036245402 |
-----------------------------------------
********** Iteration 14 ************
Optimizing Policy...
sampling
done in 0.616 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0557          0
         1     0.0583     0.0141
         2     0.0594     0.0369
         3     0.0133     0.0709
         4    0.00778      0.138
         5    0.00877      0.232
         6    0.00459      0.323
         7     0.0301       0.44
         8     0.0124       0.46
         9    0.00771      0.609
        10     0.0222      0.715
done in 0.016 seconds
Expected: 0.032 Actual: 0.021
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 102         |
| TimeElapsed             | 10.5        |
| TimestepsSoFar          | 15360       |
| entloss                 | 0.0         |
| entropy                 | 2.664287    |
| explained_variance_t... | 0.0045      |
| meankl                  | 0.00854994  |
| optimgain               | 0.021234011 |
| surrgain                | 0.021234011 |
-----------------------------------------
********** Iteration 15 ************
Optimizing Policy...
sampling
done in 0.567 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0723          0
         1      0.112     0.0159
         2     0.0821      0.123
         3     0.0218      0.147
         4     0.0114      0.236
         5     0.0117      0.334
         6    0.00701      0.397
         7      0.018      0.552
         8     0.0157      0.565
         9    0.00776      0.681
        10    0.00654      0.809
done in 0.013 seconds
Expected: 0.041 Actual: 0.028
Stepsize OK!
vf
done in 0.017 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13.4        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 109          |
| TimeElapsed             | 11.1         |
| TimestepsSoFar          | 16384        |
| entloss                 | 0.0          |
| entropy                 | 2.6590579    |
| explained_variance_t... | -0.181       |
| meankl                  | 0.0070919036 |
| optimgain               | 0.027878743  |
| surrgain                | 0.027878743  |
------------------------------------------
********** Iteration 16 ************
Optimizing Policy...
sampling
done in 0.559 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.112          0
         1     0.0545    0.00802
         2     0.0581     0.0185
         3    0.00663     0.0695
         4    0.00445      0.126
         5    0.00347       0.27
         6     0.0129      0.385
         7     0.0118      0.393
         8    0.00674      0.476
         9     0.0122      0.491
        10    0.00255        0.6
done in 0.013 seconds
Expected: 0.029 Actual: 0.022
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 116         |
| TimeElapsed             | 11.7        |
| TimestepsSoFar          | 17408       |
| entloss                 | 0.0         |
| entropy                 | 2.660922    |
| explained_variance_t... | 0.0699      |
| meankl                  | 0.014200591 |
| optimgain               | 0.02193301  |
| surrgain                | 0.02193301  |
-----------------------------------------
********** Iteration 17 ************
Optimizing Policy...
sampling
done in 0.561 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.128          0
         1     0.0386     0.0114
         2     0.0636     0.0184
         3    0.00415     0.0825
         4    0.00564      0.118
         5    0.00641      0.232
         6    0.00963      0.368
         7     0.0442      0.388
         8    0.00451      0.495
         9     0.0304      0.537
        10    0.00392      0.596
done in 0.013 seconds
Expected: 0.029 Actual: 0.022
violated KL constraint. shrinking step.
Expected: 0.029 Actual: 0.012
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -14.4        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 122          |
| TimeElapsed             | 12.3         |
| TimestepsSoFar          | 18432        |
| entloss                 | 0.0          |
| entropy                 | 2.6531348    |
| explained_variance_t... | 0.00753      |
| meankl                  | 0.0035642374 |
| optimgain               | 0.012331668  |
| surrgain                | 0.012331668  |
------------------------------------------
********** Iteration 18 ************
Optimizing Policy...
sampling
done in 0.559 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0717          0
         1     0.0749     0.0117
         2     0.0574     0.0591
         3     0.0179     0.0773
         4    0.00751      0.156
         5    0.00776      0.206
         6    0.00553      0.312
         7     0.0128       0.42
         8    0.00279      0.426
         9    0.00682      0.582
        10      0.018      0.611
done in 0.013 seconds
Expected: 0.032 Actual: 0.031
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 129         |
| TimeElapsed             | 12.9        |
| TimestepsSoFar          | 19456       |
| entloss                 | 0.0         |
| entropy                 | 2.6415825   |
| explained_variance_t... | 0.0123      |
| meankl                  | 0.009508433 |
| optimgain               | 0.031034462 |
| surrgain                | 0.031034462 |
-----------------------------------------
********** Iteration 19 ************
Optimizing Policy...
sampling
Eval num_timesteps=19456, episode_reward=-2.09 +/- 9.91
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 0.978 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.112          0
         1     0.0525     0.0116
         2     0.0324     0.0702
         3     0.0212     0.0821
         4    0.00661       0.12
         5    0.00428      0.165
         6    0.00711      0.267
         7    0.00551      0.471
         8    0.00287      0.564
         9     0.0212       0.58
        10     0.0088      0.675
done in 0.013 seconds
Expected: 0.032 Actual: 0.028
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 136         |
| TimeElapsed             | 13.9        |
| TimestepsSoFar          | 20480       |
| entloss                 | 0.0         |
| entropy                 | 2.6175544   |
| explained_variance_t... | 0.0292      |
| meankl                  | 0.008348693 |
| optimgain               | 0.028170357 |
| surrgain                | 0.028170357 |
-----------------------------------------
********** Iteration 20 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0534          0
         1       0.15     0.0262
         2     0.0879     0.0756
         3     0.0138     0.0938
         4    0.00784      0.126
         5    0.00882      0.226
         6    0.00918      0.364
         7    0.00522      0.533
         8     0.0201      0.543
         9    0.00421      0.659
        10    0.00357      0.665
done in 0.013 seconds
Expected: 0.034 Actual: 0.036
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 143         |
| TimeElapsed             | 14.5        |
| TimestepsSoFar          | 21504       |
| entloss                 | 0.0         |
| entropy                 | 2.5938227   |
| explained_variance_t... | 0.0306      |
| meankl                  | 0.009041162 |
| optimgain               | 0.035592217 |
| surrgain                | 0.035592217 |
-----------------------------------------
********** Iteration 21 ************
Optimizing Policy...
sampling
done in 0.568 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0333          0
         1     0.0845     0.0294
         2    0.00968      0.055
         3     0.0372     0.0896
         4    0.00584      0.122
         5     0.0035      0.197
         6    0.00658      0.282
         7    0.00566      0.429
         8     0.0241      0.455
         9    0.00243      0.511
        10    0.00297      0.633
done in 0.013 seconds
Expected: 0.028 Actual: 0.031
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 150         |
| TimeElapsed             | 15.1        |
| TimestepsSoFar          | 22528       |
| entloss                 | 0.0         |
| entropy                 | 2.5636098   |
| explained_variance_t... | 0.00429     |
| meankl                  | 0.008725538 |
| optimgain               | 0.030763526 |
| surrgain                | 0.030763526 |
-----------------------------------------
********** Iteration 22 ************
Optimizing Policy...
sampling
done in 0.562 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0906          0
         1     0.0412     0.0189
         2     0.0241     0.0522
         3    0.00309     0.0657
         4    0.00166     0.0819
         5    0.00528      0.182
         6    0.00374      0.287
         7     0.0019      0.331
         8    0.00422      0.367
         9    0.00802      0.387
        10    0.00125      0.478
done in 0.013 seconds
Expected: 0.024 Actual: 0.024
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.66       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 157         |
| TimeElapsed             | 15.7        |
| TimestepsSoFar          | 23552       |
| entloss                 | 0.0         |
| entropy                 | 2.5490732   |
| explained_variance_t... | 0.0317      |
| meankl                  | 0.010618247 |
| optimgain               | 0.024024365 |
| surrgain                | 0.024024365 |
-----------------------------------------
********** Iteration 23 ************
Optimizing Policy...
sampling
done in 0.572 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0792          0
         1     0.0161    0.00978
         2     0.0524     0.0177
         3    0.00524      0.066
         4     0.0044     0.0875
         5    0.00806      0.167
         6    0.00381      0.293
         7     0.0575      0.324
         8    0.00317      0.424
         9     0.0145       0.44
        10    0.00276       0.59
done in 0.013 seconds
Expected: 0.025 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.48       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 163         |
| TimeElapsed             | 16.3        |
| TimestepsSoFar          | 24576       |
| entloss                 | 0.0         |
| entropy                 | 2.5156558   |
| explained_variance_t... | -0.0835     |
| meankl                  | 0.01329361  |
| optimgain               | 0.026930986 |
| surrgain                | 0.026930986 |
-----------------------------------------
********** Iteration 24 ************
Optimizing Policy...
sampling
done in 0.561 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.125          0
         1     0.0258    0.00598
         2     0.0118     0.0552
         3     0.0505     0.0959
         4     0.0216      0.122
         5     0.0108      0.251
         6     0.0143      0.378
         7     0.0612      0.397
         8     0.0066      0.477
         9    0.00523       0.65
        10    0.00672      0.762
done in 0.013 seconds
Expected: 0.034 Actual: 0.006
violated KL constraint. shrinking step.
Expected: 0.034 Actual: 0.009
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.23       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 170         |
| TimeElapsed             | 16.9        |
| TimestepsSoFar          | 25600       |
| entloss                 | 0.0         |
| entropy                 | 2.519742    |
| explained_variance_t... | -0.116      |
| meankl                  | 0.002567171 |
| optimgain               | 0.009305323 |
| surrgain                | 0.009305323 |
-----------------------------------------
********** Iteration 25 ************
Optimizing Policy...
sampling
done in 0.557 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0298          0
         1     0.0154      0.082
         2     0.0713      0.121
         3      0.019      0.136
         4     0.0265      0.148
         5     0.0126      0.238
         6    0.00683      0.352
         7    0.00283      0.461
         8    0.00711      0.575
         9     0.0384      0.592
        10    0.00284      0.714
done in 0.013 seconds
Expected: 0.034 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.03       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 177         |
| TimeElapsed             | 17.5        |
| TimestepsSoFar          | 26624       |
| entloss                 | 0.0         |
| entropy                 | 2.5060737   |
| explained_variance_t... | 0.0939      |
| meankl                  | 0.007812542 |
| optimgain               | 0.026812168 |
| surrgain                | 0.026812168 |
-----------------------------------------
********** Iteration 26 ************
Optimizing Policy...
sampling
done in 0.577 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.139          0
         1     0.0595    0.00792
         2     0.0779     0.0718
         3    0.00821     0.0869
         4     0.0122      0.154
         5    0.00746      0.273
         6    0.00242      0.342
         7     0.0354      0.357
         8    0.00235      0.382
         9    0.00733       0.46
        10    0.00525       0.47
done in 0.012 seconds
Expected: 0.031 Actual: 0.030
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.9        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 184         |
| TimeElapsed             | 18.2        |
| TimestepsSoFar          | 27648       |
| entloss                 | 0.0         |
| entropy                 | 2.5424802   |
| explained_variance_t... | 0.00679     |
| meankl                  | 0.008993147 |
| optimgain               | 0.03047036  |
| surrgain                | 0.03047036  |
-----------------------------------------
********** Iteration 27 ************
Optimizing Policy...
sampling
done in 0.579 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0297          0
         1     0.0333     0.0123
         2     0.0339     0.0401
         3    0.00891     0.0485
         4    0.00367     0.0935
         5    0.00617       0.17
         6    0.00397      0.321
         7    0.00437      0.441
         8     0.0403      0.487
         9     0.0079       0.54
        10     0.0034       0.55
done in 0.013 seconds
Expected: 0.025 Actual: 0.023
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.24       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 191         |
| TimeElapsed             | 18.8        |
| TimestepsSoFar          | 28672       |
| entloss                 | 0.0         |
| entropy                 | 2.569653    |
| explained_variance_t... | -0.117      |
| meankl                  | 0.014532371 |
| optimgain               | 0.023432981 |
| surrgain                | 0.023432981 |
-----------------------------------------
********** Iteration 28 ************
Optimizing Policy...
sampling
done in 0.559 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.023          0
         1      0.068     0.0232
         2     0.0339      0.056
         3     0.0087      0.065
         4    0.00617      0.111
         5    0.00789      0.183
         6    0.00397       0.32
         7     0.0044      0.419
         8      0.045      0.453
         9    0.00636      0.529
        10    0.00683      0.541
done in 0.012 seconds
Expected: 0.026 Actual: 0.023
Stepsize OK!
vf
done in 0.017 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.29       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 197         |
| TimeElapsed             | 19.4        |
| TimestepsSoFar          | 29696       |
| entloss                 | 0.0         |
| entropy                 | 2.5409882   |
| explained_variance_t... | 0.0193      |
| meankl                  | 0.010614395 |
| optimgain               | 0.023177192 |
| surrgain                | 0.023177192 |
-----------------------------------------
********** Iteration 29 ************
Optimizing Policy...
sampling
Eval num_timesteps=29696, episode_reward=-13.02 +/- 7.45
Episode length: 150.00 +/- 0.00
done in 0.989 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.236          0
         1     0.0557     0.0116
         2     0.0848     0.0272
         3     0.0242     0.0745
         4     0.0124      0.153
         5     0.0102      0.236
         6     0.0141      0.361
         7      0.166      0.514
         8     0.0117      0.584
         9     0.0867      0.694
        10    0.00929      0.778
done in 0.013 seconds
Expected: 0.038 Actual: 0.039
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.58       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 204         |
| TimeElapsed             | 20.4        |
| TimestepsSoFar          | 30720       |
| entloss                 | 0.0         |
| entropy                 | 2.5494688   |
| explained_variance_t... | 0.0417      |
| meankl                  | 0.010821609 |
| optimgain               | 0.039264932 |
| surrgain                | 0.039264932 |
-----------------------------------------
********** Iteration 30 ************
Optimizing Policy...
sampling
done in 0.576 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.029          0
         1     0.0909     0.0203
         2     0.0358      0.057
         3     0.0187      0.072
         4    0.00446      0.101
         5    0.00692      0.177
         6     0.0038      0.262
         7     0.0183      0.348
         8    0.00398      0.359
         9    0.00318      0.494
        10     0.0212      0.555
done in 0.013 seconds
Expected: 0.027 Actual: 0.025
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.6        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 211         |
| TimeElapsed             | 21          |
| TimestepsSoFar          | 31744       |
| entloss                 | 0.0         |
| entropy                 | 2.5695193   |
| explained_variance_t... | 0.0211      |
| meankl                  | 0.008416299 |
| optimgain               | 0.025097515 |
| surrgain                | 0.025097515 |
-----------------------------------------
********** Iteration 31 ************
Optimizing Policy...
sampling
done in 0.589 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.139          0
         1      0.042     0.0103
         2      0.112     0.0385
         3     0.0103      0.114
         4     0.0037      0.145
         5    0.00438      0.188
         6    0.00395      0.269
         7     0.0274      0.346
         8    0.00261      0.363
         9     0.0362      0.408
        10     0.0028      0.556
done in 0.014 seconds
Expected: 0.030 Actual: 0.029
Stepsize OK!
vf
done in 0.023 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -9.39        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 218          |
| TimeElapsed             | 21.7         |
| TimestepsSoFar          | 32768        |
| entloss                 | 0.0          |
| entropy                 | 2.564352     |
| explained_variance_t... | 0.0395       |
| meankl                  | 0.0091693085 |
| optimgain               | 0.028564347  |
| surrgain                | 0.028564347  |
------------------------------------------
********** Iteration 32 ************
Optimizing Policy...
sampling
done in 0.609 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.291          0
         1     0.0195     0.0144
         2     0.0241     0.0367
         3    0.00856     0.0524
         4    0.00586     0.0797
         5    0.00416      0.151
         6    0.00653      0.461
         7      0.029      0.542
         8    0.00163      0.567
         9    0.00344      0.618
        10     0.0186      0.706
done in 0.013 seconds
Expected: 0.030 Actual: 0.030
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.67       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 225         |
| TimeElapsed             | 22.3        |
| TimestepsSoFar          | 33792       |
| entloss                 | 0.0         |
| entropy                 | 2.5579865   |
| explained_variance_t... | 0.0437      |
| meankl                  | 0.009380442 |
| optimgain               | 0.03020911  |
| surrgain                | 0.03020911  |
-----------------------------------------
********** Iteration 33 ************
Optimizing Policy...
sampling
done in 0.562 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       1.56          0
         1      0.292     0.0302
         2      0.133     0.0802
         3       0.17      0.112
         4     0.0297      0.188
         5     0.0402      0.315
         6     0.0641      0.526
         7     0.0834      0.937
         8      0.145      0.981
         9     0.0531       1.35
        10      0.111       1.81
done in 0.013 seconds
Expected: 0.077 Actual: 0.036
violated KL constraint. shrinking step.
Expected: 0.077 Actual: 0.028
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 232         |
| TimeElapsed             | 22.9        |
| TimestepsSoFar          | 34816       |
| entloss                 | 0.0         |
| entropy                 | 2.5468845   |
| explained_variance_t... | -0.0917     |
| meankl                  | 0.008172719 |
| optimgain               | 0.028081372 |
| surrgain                | 0.028081372 |
-----------------------------------------
********** Iteration 34 ************
Optimizing Policy...
sampling
done in 0.589 seconds
computegrad
done in 0.006 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.125          0
         1     0.0564     0.0215
         2      0.132     0.0475
         3     0.0198      0.103
         4     0.0176      0.157
         5     0.0181      0.225
         6    0.00418      0.329
         7    0.00541      0.402
         8     0.0176      0.477
         9    0.00748      0.489
        10    0.00564      0.633
done in 0.014 seconds
Expected: 0.036 Actual: 0.034
Stepsize OK!
vf
done in 0.019 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -10.5        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 238          |
| TimeElapsed             | 23.6         |
| TimestepsSoFar          | 35840        |
| entloss                 | 0.0          |
| entropy                 | 2.5558746    |
| explained_variance_t... | 0.0484       |
| meankl                  | 0.0082439175 |
| optimgain               | 0.03414417   |
| surrgain                | 0.03414417   |
------------------------------------------
********** Iteration 35 ************
Optimizing Policy...
sampling
done in 0.559 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0848          0
         1     0.0146     0.0087
         2     0.0291     0.0206
         3    0.00271      0.068
         4    0.00468      0.236
         5    0.00262      0.296
         6    0.00285      0.356
         7     0.0355      0.385
         8    0.00662      0.547
         9     0.0339      0.613
        10    0.00196      0.827
done in 0.013 seconds
Expected: 0.027 Actual: 0.023
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.4       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 245         |
| TimeElapsed             | 24.2        |
| TimestepsSoFar          | 36864       |
| entloss                 | 0.0         |
| entropy                 | 2.5182703   |
| explained_variance_t... | 0.0564      |
| meankl                  | 0.010692642 |
| optimgain               | 0.02269173  |
| surrgain                | 0.02269173  |
-----------------------------------------
********** Iteration 36 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.145          0
         1     0.0796     0.0201
         2     0.0885     0.0518
         3     0.0163     0.0935
         4     0.0119      0.128
         5     0.0196      0.241
         6     0.0102      0.361
         7    0.00658      0.477
         8    0.00537      0.541
         9     0.0091      0.548
        10     0.0074      0.696
done in 0.013 seconds
Expected: 0.037 Actual: 0.038
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 252         |
| TimeElapsed             | 24.8        |
| TimestepsSoFar          | 37888       |
| entloss                 | 0.0         |
| entropy                 | 2.4793088   |
| explained_variance_t... | 0.0853      |
| meankl                  | 0.011500174 |
| optimgain               | 0.037981987 |
| surrgain                | 0.037981987 |
-----------------------------------------
********** Iteration 37 ************
Optimizing Policy...
sampling
done in 0.571 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.688          0
         1      0.146     0.0198
         2       0.13     0.0568
         3      0.191      0.127
         4     0.0644      0.206
         5     0.0765      0.408
         6     0.0569      0.671
         7      0.203      0.993
         8      0.121       1.04
         9     0.0555       1.88
        10     0.0541       2.15
done in 0.013 seconds
Expected: 0.082 Actual: 0.029
violated KL constraint. shrinking step.
Expected: 0.082 Actual: 0.020
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.2        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 259          |
| TimeElapsed             | 25.4         |
| TimestepsSoFar          | 38912        |
| entloss                 | 0.0          |
| entropy                 | 2.4835327    |
| explained_variance_t... | -0.496       |
| meankl                  | 0.0070251143 |
| optimgain               | 0.019827401  |
| surrgain                | 0.019827401  |
------------------------------------------
********** Iteration 38 ************
Optimizing Policy...
sampling
done in 0.596 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.161          0
         1     0.0997     0.0117
         2      0.131     0.0516
         3     0.0144     0.0911
         4     0.0189      0.128
         5     0.0122      0.182
         6    0.00919      0.312
         7     0.0136      0.501
         8     0.0568      0.522
         9     0.0087      0.688
        10     0.0275      0.722
done in 0.013 seconds
Expected: 0.038 Actual: 0.040
Stepsize OK!
vf
done in 0.019 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -10.7        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 266          |
| TimeElapsed             | 26           |
| TimestepsSoFar          | 39936        |
| entloss                 | 0.0          |
| entropy                 | 2.4723213    |
| explained_variance_t... | 0.0638       |
| meankl                  | 0.0096233385 |
| optimgain               | 0.04044719   |
| surrgain                | 0.04044719   |
------------------------------------------
********** Iteration 39 ************
Optimizing Policy...
sampling
Eval num_timesteps=39936, episode_reward=2.56 +/- 5.64
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.019 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0488          0
         1     0.0885     0.0342
         2     0.0587     0.0621
         3     0.0113     0.0756
         4     0.0074        0.1
         5     0.0131      0.192
         6     0.0137      0.278
         7     0.0062      0.435
         8      0.017      0.503
         9    0.00895      0.515
        10    0.00521      0.689
done in 0.014 seconds
Expected: 0.032 Actual: 0.040
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.96       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 273         |
| TimeElapsed             | 27.1        |
| TimestepsSoFar          | 40960       |
| entloss                 | 0.0         |
| entropy                 | 2.45636     |
| explained_variance_t... | 0.0253      |
| meankl                  | 0.009256423 |
| optimgain               | 0.03972014  |
| surrgain                | 0.03972014  |
-----------------------------------------
********** Iteration 40 ************
Optimizing Policy...
sampling
done in 0.626 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.256          0
         1      0.238    0.00667
         2      0.217     0.0923
         3       0.12      0.128
         4       0.36      0.352
         5      0.169      0.413
         6      0.231      0.659
         7      0.423      0.682
         8      0.169       1.03
         9     0.0729       1.24
        10     0.0444       1.47
done in 0.013 seconds
Expected: 0.078 Actual: -0.003
violated KL constraint. shrinking step.
Expected: 0.078 Actual: -0.013
violated KL constraint. shrinking step.
Expected: 0.078 Actual: -0.003
surrogate didn't improve. shrinking step.
Expected: 0.078 Actual: 0.007
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.4        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 279          |
| TimeElapsed             | 27.8         |
| TimestepsSoFar          | 41984        |
| entloss                 | 0.0          |
| entropy                 | 2.4562104    |
| explained_variance_t... | 0.00376      |
| meankl                  | 0.0011228278 |
| optimgain               | 0.0069414647 |
| surrgain                | 0.0069414647 |
------------------------------------------
********** Iteration 41 ************
Optimizing Policy...
sampling
done in 0.588 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.289          0
         1       0.18     0.0103
         2      0.116     0.0343
         3      0.108     0.0711
         4     0.0396      0.106
         5     0.0349      0.191
         6     0.0201      0.258
         7      0.102      0.398
         8     0.0353      0.413
         9     0.0176      0.604
        10     0.0123      0.755
done in 0.014 seconds
Expected: 0.045 Actual: 0.026
violated KL constraint. shrinking step.
Expected: 0.045 Actual: 0.020
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13          |
| EpThisIter              | 7            |
| EpisodesSoFar           | 286          |
| TimeElapsed             | 28.4         |
| TimestepsSoFar          | 43008        |
| entloss                 | 0.0          |
| entropy                 | 2.4549966    |
| explained_variance_t... | 0.181        |
| meankl                  | 0.0039883917 |
| optimgain               | 0.019729387  |
| surrgain                | 0.019729387  |
------------------------------------------
********** Iteration 42 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.006 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.184          0
         1      0.141    0.00925
         2     0.0906      0.037
         3     0.0319     0.0632
         4     0.0234      0.112
         5     0.0094      0.127
         6    0.00935      0.153
         7     0.0132      0.192
         8     0.0113      0.195
         9    0.00617      0.238
        10    0.00807      0.307
done in 0.021 seconds
Expected: 0.029 Actual: 0.015
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.4       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 293         |
| TimeElapsed             | 29          |
| TimestepsSoFar          | 44032       |
| entloss                 | 0.0         |
| entropy                 | 2.4393003   |
| explained_variance_t... | 0.305       |
| meankl                  | 0.010989162 |
| optimgain               | 0.015335351 |
| surrgain                | 0.015335351 |
-----------------------------------------
********** Iteration 43 ************
Optimizing Policy...
sampling
done in 0.549 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.107          0
         1      0.175     0.0266
         2      0.134     0.0482
         3     0.0426     0.0636
         4     0.0444      0.085
         5     0.0158      0.181
         6     0.0141      0.217
         7     0.0121      0.296
         8     0.0197      0.353
         9    0.00851      0.358
        10     0.0135      0.499
done in 0.013 seconds
Expected: 0.035 Actual: 0.012
violated KL constraint. shrinking step.
Expected: 0.035 Actual: 0.011
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -18.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 300         |
| TimeElapsed             | 29.6        |
| TimestepsSoFar          | 45056       |
| entloss                 | 0.0         |
| entropy                 | 2.4341831   |
| explained_variance_t... | 0.422       |
| meankl                  | 0.004157096 |
| optimgain               | 0.010710588 |
| surrgain                | 0.010710588 |
-----------------------------------------
********** Iteration 44 ************
Optimizing Policy...
sampling
done in 0.566 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0721          0
         1      0.183     0.0166
         2     0.0416     0.0673
         3    0.00578     0.0745
         4    0.00534     0.0836
         5      0.007      0.123
         6     0.0138      0.302
         7    0.00499      0.534
         8      0.027      0.546
         9    0.00353      0.643
        10     0.0305      0.681
done in 0.013 seconds
Expected: 0.031 Actual: 0.050
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -19.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 307         |
| TimeElapsed             | 30.2        |
| TimestepsSoFar          | 46080       |
| entloss                 | 0.0         |
| entropy                 | 2.4435427   |
| explained_variance_t... | 0.298       |
| meankl                  | 0.011424085 |
| optimgain               | 0.049658485 |
| surrgain                | 0.049658485 |
-----------------------------------------
********** Iteration 45 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0769          0
         1      0.114     0.0144
         2       0.16     0.0351
         3     0.0695     0.0909
         4     0.0721      0.171
         5     0.0881      0.236
         6     0.0608       0.49
         7     0.0399      0.642
         8     0.0448        0.9
         9      0.377       1.07
        10     0.0307       1.13
done in 0.013 seconds
Expected: 0.054 Actual: 0.022
violated KL constraint. shrinking step.
Expected: 0.054 Actual: 0.009
violated KL constraint. shrinking step.
Expected: 0.054 Actual: -0.001
surrogate didn't improve. shrinking step.
Expected: 0.054 Actual: -0.001
surrogate didn't improve. shrinking step.
Expected: 0.054 Actual: 0.001
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -22.3        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 314          |
| TimeElapsed             | 30.9         |
| TimestepsSoFar          | 47104        |
| entloss                 | 0.0          |
| entropy                 | 2.4433687    |
| explained_variance_t... | 0.316        |
| meankl                  | 0.0003052159 |
| optimgain               | 0.001288015  |
| surrgain                | 0.001288015  |
------------------------------------------
********** Iteration 46 ************
Optimizing Policy...
sampling
done in 0.577 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.278          0
         1      0.198     0.0161
         2     0.0493     0.0313
         3      0.107     0.0584
         4     0.0474      0.115
         5     0.0346      0.232
         6     0.0445      0.337
         7     0.0357      0.505
         8      0.242      0.559
         9     0.0265      0.652
        10     0.0097      0.759
done in 0.012 seconds
Expected: 0.046 Actual: 0.006
violated KL constraint. shrinking step.
Expected: 0.046 Actual: 0.005
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -22.7       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 320         |
| TimeElapsed             | 31.5        |
| TimestepsSoFar          | 48128       |
| entloss                 | 0.0         |
| entropy                 | 2.4434996   |
| explained_variance_t... | 0.389       |
| meankl                  | 0.011845148 |
| optimgain               | 0.004524261 |
| surrgain                | 0.004524261 |
-----------------------------------------
********** Iteration 47 ************
Optimizing Policy...
sampling
done in 0.594 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.338          0
         1     0.0757    0.00712
         2      0.114      0.057
         3      0.132     0.0962
         4     0.0512       0.16
         5     0.0373      0.232
         6     0.0386      0.347
         7      0.526      0.427
         8     0.0105      0.538
         9     0.0202      0.702
        10      0.014      0.839
done in 0.013 seconds
Expected: 0.048 Actual: 0.012
violated KL constraint. shrinking step.
Expected: 0.048 Actual: 0.016
Stepsize OK!
vf
done in 0.019 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -21.6        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 327          |
| TimeElapsed             | 32.1         |
| TimestepsSoFar          | 49152        |
| entloss                 | 0.0          |
| entropy                 | 2.430194     |
| explained_variance_t... | -0.667       |
| meankl                  | 0.0045096865 |
| optimgain               | 0.015975898  |
| surrgain                | 0.015975898  |
------------------------------------------
********** Iteration 48 ************
Optimizing Policy...
sampling
Eval num_timesteps=49152, episode_reward=-4.55 +/- 4.55
Episode length: 150.00 +/- 0.00
done in 1.025 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.264          0
         1     0.0738    0.00801
         2     0.0887     0.0224
         3     0.0527     0.0667
         4     0.0117      0.131
         5     0.0193      0.176
         6    0.00932      0.295
         7     0.0726      0.307
         8     0.0112      0.461
         9     0.0155      0.591
        10     0.0432      0.621
done in 0.013 seconds
Expected: 0.036 Actual: 0.047
violated KL constraint. shrinking step.
Expected: 0.036 Actual: 0.020
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -20.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 334         |
| TimeElapsed             | 33.2        |
| TimestepsSoFar          | 50176       |
| entloss                 | 0.0         |
| entropy                 | 2.4357786   |
| explained_variance_t... | 0.264       |
| meankl                  | 0.005559928 |
| optimgain               | 0.0204386   |
| surrgain                | 0.0204386   |
-----------------------------------------
********** Iteration 49 ************
Optimizing Policy...
sampling
done in 0.598 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.267          0
         1      0.284     0.0261
         2      0.261     0.0503
         3     0.0848     0.0892
         4     0.0436      0.187
         5     0.0374       0.26
         6     0.0397       0.45
         7     0.0226      0.665
         8      0.189      0.696
         9     0.0128      0.813
        10     0.0897      0.896
done in 0.013 seconds
Expected: 0.055 Actual: 0.031
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -17.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 341         |
| TimeElapsed             | 33.8        |
| TimestepsSoFar          | 51200       |
| entloss                 | 0.0         |
| entropy                 | 2.4383757   |
| explained_variance_t... | -1.27       |
| meankl                  | 0.005844153 |
| optimgain               | 0.030888474 |
| surrgain                | 0.030888474 |
-----------------------------------------
********** Iteration 50 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.177          0
         1     0.0436    0.00897
         2      0.037      0.034
         3     0.0238     0.0502
         4    0.00936     0.0834
         5    0.00891      0.149
         6     0.0101      0.351
         7      0.105       0.43
         8     0.0102      0.486
         9    0.00646      0.744
        10     0.0222      0.768
done in 0.013 seconds
Expected: 0.033 Actual: 0.032
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 348         |
| TimeElapsed             | 34.4        |
| TimestepsSoFar          | 52224       |
| entloss                 | 0.0         |
| entropy                 | 2.4325657   |
| explained_variance_t... | 0.27        |
| meankl                  | 0.01322348  |
| optimgain               | 0.032258257 |
| surrgain                | 0.032258257 |
-----------------------------------------
********** Iteration 51 ************
Optimizing Policy...
sampling
done in 0.568 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.398          0
         1      0.508     0.0339
         2      0.974     0.0985
         3      0.178      0.237
         4      0.122      0.327
         5     0.0988      0.423
         6      0.145          1
         7      0.129       1.68
         8       1.13       1.81
         9      0.104       2.27
        10      0.315       2.52
done in 0.014 seconds
Expected: 0.106 Actual: 0.010
violated KL constraint. shrinking step.
Expected: 0.106 Actual: 0.022
violated KL constraint. shrinking step.
Expected: 0.106 Actual: 0.009
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16         |
| EpThisIter              | 6           |
| EpisodesSoFar           | 354         |
| TimeElapsed             | 35.1        |
| TimestepsSoFar          | 53248       |
| entloss                 | 0.0         |
| entropy                 | 2.433257    |
| explained_variance_t... | 0.207       |
| meankl                  | 0.008729478 |
| optimgain               | 0.008862644 |
| surrgain                | 0.008862644 |
-----------------------------------------
********** Iteration 52 ************
Optimizing Policy...
sampling
done in 0.569 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0374          0
         1     0.0767     0.0208
         2     0.0526      0.051
         3     0.0121     0.0819
         4     0.0141      0.109
         5     0.0206      0.195
         6     0.0466      0.257
         7    0.00733      0.443
         8    0.00437       0.55
         9     0.0445      0.577
        10    0.00537      0.642
done in 0.013 seconds
Expected: 0.032 Actual: 0.037
Stepsize OK!
vf
done in 0.018 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -12.8      |
| EpThisIter              | 7          |
| EpisodesSoFar           | 361        |
| TimeElapsed             | 35.7       |
| TimestepsSoFar          | 54272      |
| entloss                 | 0.0        |
| entropy                 | 2.436856   |
| explained_variance_t... | -0.235     |
| meankl                  | 0.00948384 |
| optimgain               | 0.03725359 |
| surrgain                | 0.03725359 |
----------------------------------------
********** Iteration 53 ************
Optimizing Policy...
sampling
done in 0.564 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.271          0
         1      0.393     0.0242
         2      0.044     0.0647
         3     0.0361      0.083
         4     0.0167     0.0956
         5    0.00705      0.129
         6     0.0117      0.184
         7     0.0111      0.397
         8      0.051      0.415
         9    0.00456      0.519
        10     0.0039      0.618
done in 0.013 seconds
Expected: 0.038 Actual: 0.040
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 368         |
| TimeElapsed             | 36.3        |
| TimestepsSoFar          | 55296       |
| entloss                 | 0.0         |
| entropy                 | 2.4527466   |
| explained_variance_t... | 0.227       |
| meankl                  | 0.011352003 |
| optimgain               | 0.039712142 |
| surrgain                | 0.039712142 |
-----------------------------------------
********** Iteration 54 ************
Optimizing Policy...
sampling
done in 0.595 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.177          0
         1      0.311     0.0616
         2      0.814      0.144
         3      0.193      0.253
         4      0.149      0.397
         5     0.0449      0.434
         6     0.0308      0.494
         7     0.0536      0.581
         8     0.0722      0.764
         9      0.315      0.825
        10     0.0892       1.14
done in 0.013 seconds
Expected: 0.070 Actual: 0.012
violated KL constraint. shrinking step.
Expected: 0.070 Actual: 0.010
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 375         |
| TimeElapsed             | 36.9        |
| TimestepsSoFar          | 56320       |
| entloss                 | 0.0         |
| entropy                 | 2.4528189   |
| explained_variance_t... | 0.312       |
| meankl                  | 0.008632063 |
| optimgain               | 0.009899542 |
| surrgain                | 0.009899542 |
-----------------------------------------
********** Iteration 55 ************
Optimizing Policy...
sampling
done in 0.561 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.117          0
         1      0.114     0.0208
         2       0.21      0.039
         3      0.018     0.0809
         4     0.0157      0.101
         5     0.0109      0.151
         6    0.00978      0.217
         7     0.0128      0.312
         8    0.00504      0.316
         9      0.015      0.379
        10     0.0112      0.559
done in 0.013 seconds
Expected: 0.033 Actual: 0.039
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 382         |
| TimeElapsed             | 37.5        |
| TimestepsSoFar          | 57344       |
| entloss                 | 0.0         |
| entropy                 | 2.4393308   |
| explained_variance_t... | 0.107       |
| meankl                  | 0.010823602 |
| optimgain               | 0.039007902 |
| surrgain                | 0.039007902 |
-----------------------------------------
********** Iteration 56 ************
Optimizing Policy...
sampling
done in 0.558 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.164          0
         1      0.399     0.0337
         2      0.403     0.0635
         3       0.06      0.111
         4     0.0862      0.149
         5      0.082      0.279
         6     0.0699      0.463
         7     0.0325      0.718
         8      0.511      0.786
         9     0.0204      0.889
        10     0.0495       1.14
done in 0.015 seconds
Expected: 0.061 Actual: 0.012
violated KL constraint. shrinking step.
Expected: 0.061 Actual: 0.006
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 389         |
| TimeElapsed             | 38.1        |
| TimestepsSoFar          | 58368       |
| entloss                 | 0.0         |
| entropy                 | 2.432859    |
| explained_variance_t... | 0.314       |
| meankl                  | 0.008245086 |
| optimgain               | 0.006095864 |
| surrgain                | 0.006095864 |
-----------------------------------------
********** Iteration 57 ************
Optimizing Policy...
sampling
done in 0.578 seconds
computegrad
done in 0.007 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0432          0
         1     0.0272    0.00359
         2     0.0544     0.0232
         3     0.0236     0.0633
         4    0.00826       0.11
         5    0.00808      0.196
         6     0.0154      0.373
         7      0.107      0.402
         8     0.0067      0.476
         9       0.01      0.554
        10    0.00417      0.562
done in 0.018 seconds
Expected: 0.028 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.62       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 395         |
| TimeElapsed             | 38.8        |
| TimestepsSoFar          | 59392       |
| entloss                 | 0.0         |
| entropy                 | 2.4327705   |
| explained_variance_t... | 0.0346      |
| meankl                  | 0.009771357 |
| optimgain               | 0.027081557 |
| surrgain                | 0.027081557 |
-----------------------------------------
********** Iteration 58 ************
Optimizing Policy...
sampling
Eval num_timesteps=59392, episode_reward=-2.86 +/- 6.82
Episode length: 150.00 +/- 0.00
done in 0.972 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0395          0
         1     0.0326     0.0161
         2     0.0201     0.0301
         3     0.0174     0.0545
         4      0.024     0.0999
         5    0.00708       0.14
         6      0.018      0.185
         7    0.00636      0.259
         8    0.00557      0.312
         9    0.00479      0.392
        10     0.0193      0.412
done in 0.013 seconds
Expected: 0.025 Actual: 0.024
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8          |
| EpThisIter              | 7           |
| EpisodesSoFar           | 402         |
| TimeElapsed             | 39.8        |
| TimestepsSoFar          | 60416       |
| entloss                 | 0.0         |
| entropy                 | 2.4437256   |
| explained_variance_t... | 0.162       |
| meankl                  | 0.009447122 |
| optimgain               | 0.024061497 |
| surrgain                | 0.024061497 |
-----------------------------------------
********** Iteration 59 ************
Optimizing Policy...
sampling
done in 0.549 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0666          0
         1      0.104     0.0497
         2      0.131     0.0671
         3     0.0216     0.0884
         4     0.0321      0.107
         5     0.0157      0.127
         6    0.00903      0.163
         7    0.00833      0.317
         8     0.0078      0.384
         9     0.0251      0.392
        10    0.00418      0.553
done in 0.012 seconds
Expected: 0.033 Actual: 0.039
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.34       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 409         |
| TimeElapsed             | 40.4        |
| TimestepsSoFar          | 61440       |
| entloss                 | 0.0         |
| entropy                 | 2.508679    |
| explained_variance_t... | 0.0761      |
| meankl                  | 0.011389269 |
| optimgain               | 0.03925717  |
| surrgain                | 0.03925717  |
-----------------------------------------
********** Iteration 60 ************
Optimizing Policy...
sampling
done in 0.550 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.059          0
         1     0.0515    0.00475
         2     0.0506     0.0819
         3     0.0233     0.0981
         4     0.0304       0.14
         5     0.0266      0.178
         6     0.0184      0.378
         7      0.309      0.451
         8     0.0185      0.554
         9     0.0116      0.736
        10     0.0172       1.03
done in 0.012 seconds
Expected: 0.042 Actual: 0.033
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.31       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 416         |
| TimeElapsed             | 41          |
| TimestepsSoFar          | 62464       |
| entloss                 | 0.0         |
| entropy                 | 2.5241911   |
| explained_variance_t... | 0.0336      |
| meankl                  | 0.013806106 |
| optimgain               | 0.033085126 |
| surrgain                | 0.033085126 |
-----------------------------------------
********** Iteration 61 ************
Optimizing Policy...
sampling
done in 0.551 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.319          0
         1      0.063     0.0112
         2      0.078     0.0301
         3     0.0174     0.0949
         4     0.0182      0.148
         5     0.0295      0.225
         6     0.0117      0.441
         7     0.0301      0.548
         8    0.00514      0.557
         9    0.00418      0.632
        10     0.0254      0.718
done in 0.012 seconds
Expected: 0.039 Actual: 0.042
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.75       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 423         |
| TimeElapsed             | 41.6        |
| TimestepsSoFar          | 63488       |
| entloss                 | 0.0         |
| entropy                 | 2.5019233   |
| explained_variance_t... | -0.0857     |
| meankl                  | 0.010503465 |
| optimgain               | 0.041522134 |
| surrgain                | 0.041522134 |
-----------------------------------------
********** Iteration 62 ************
Optimizing Policy...
sampling
done in 0.556 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0843          0
         1     0.0956     0.0118
         2     0.0213      0.044
         3     0.0165     0.0572
         4    0.00791     0.0693
         5     0.0113      0.173
         6     0.0173       0.24
         7    0.00778      0.429
         8     0.0874      0.496
         9    0.00582       0.55
        10    0.00411      0.704
done in 0.012 seconds
Expected: 0.032 Actual: 0.030
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.58       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 430         |
| TimeElapsed             | 42.2        |
| TimestepsSoFar          | 64512       |
| entloss                 | 0.0         |
| entropy                 | 2.4901924   |
| explained_variance_t... | 0.243       |
| meankl                  | 0.009488149 |
| optimgain               | 0.029655756 |
| surrgain                | 0.029655756 |
-----------------------------------------
********** Iteration 63 ************
Optimizing Policy...
sampling
done in 0.549 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.124          0
         1      0.123      0.016
         2     0.0302     0.0444
         3     0.0211     0.0724
         4     0.0162      0.101
         5    0.00865      0.121
         6     0.0132      0.198
         7    0.00422      0.322
         8    0.00917      0.453
         9      0.043      0.476
        10    0.00586      0.626
done in 0.013 seconds
Expected: 0.033 Actual: 0.031
Stepsize OK!
vf
done in 0.017 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.66       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 436         |
| TimeElapsed             | 42.7        |
| TimestepsSoFar          | 65536       |
| entloss                 | 0.0         |
| entropy                 | 2.4527285   |
| explained_variance_t... | -0.00541    |
| meankl                  | 0.011337159 |
| optimgain               | 0.031341255 |
| surrgain                | 0.031341255 |
-----------------------------------------
********** Iteration 64 ************
Optimizing Policy...
sampling
done in 0.545 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.127          0
         1     0.0865     0.0102
         2     0.0327     0.0265
         3     0.0131     0.0517
         4     0.0182      0.151
         5     0.0276      0.182
         6     0.0207      0.272
         7     0.0044      0.331
         8      0.051      0.346
         9     0.0115       0.41
        10    0.00898      0.488
done in 0.012 seconds
Expected: 0.030 Actual: 0.027
Stepsize OK!
vf
done in 0.019 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -7.95        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 443          |
| TimeElapsed             | 43.3         |
| TimestepsSoFar          | 66560        |
| entloss                 | 0.0          |
| entropy                 | 2.4557188    |
| explained_variance_t... | 0.0124       |
| meankl                  | 0.0086292345 |
| optimgain               | 0.027046783  |
| surrgain                | 0.027046783  |
------------------------------------------
********** Iteration 65 ************
Optimizing Policy...
sampling
done in 0.558 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.115          0
         1     0.0721    0.00881
         2     0.0503      0.043
         3     0.0186     0.0707
         4     0.0111     0.0904
         5     0.0215      0.118
         6     0.0134      0.185
         7    0.00801      0.258
         8     0.0511      0.277
         9    0.00425      0.324
        10     0.0048       0.36
done in 0.013 seconds
Expected: 0.028 Actual: 0.029
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.53       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 450         |
| TimeElapsed             | 43.9        |
| TimestepsSoFar          | 67584       |
| entloss                 | 0.0         |
| entropy                 | 2.4461057   |
| explained_variance_t... | -0.165      |
| meankl                  | 0.009533098 |
| optimgain               | 0.028515216 |
| surrgain                | 0.028515216 |
-----------------------------------------
********** Iteration 66 ************
Optimizing Policy...
sampling
done in 0.557 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0894          0
         1     0.0568     0.0112
         2     0.0252     0.0247
         3     0.0136     0.0524
         4     0.0182     0.0871
         5     0.0333       0.13
         6     0.0265      0.305
         7    0.00827      0.525
         8     0.0373      0.572
         9    0.00609      0.589
        10      0.004      0.633
done in 0.012 seconds
Expected: 0.032 Actual: 0.030
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.14       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 457         |
| TimeElapsed             | 44.5        |
| TimestepsSoFar          | 68608       |
| entloss                 | 0.0         |
| entropy                 | 2.448884    |
| explained_variance_t... | 0.0129      |
| meankl                  | 0.00908226  |
| optimgain               | 0.029967766 |
| surrgain                | 0.029967766 |
-----------------------------------------
********** Iteration 67 ************
Optimizing Policy...
sampling
done in 0.556 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.057          0
         1     0.0749       0.01
         2     0.0344     0.0835
         3      0.102      0.154
         4     0.0429       0.25
         5     0.0356      0.319
         6     0.0126      0.496
         7     0.0126      0.601
         8      0.145      0.663
         9    0.00707       0.73
        10     0.0136      0.848
done in 0.012 seconds
Expected: 0.043 Actual: 0.039
Stepsize OK!
vf
done in 0.019 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -4.72      |
| EpThisIter              | 7          |
| EpisodesSoFar           | 464        |
| TimeElapsed             | 45.1       |
| TimestepsSoFar          | 69632      |
| entloss                 | 0.0        |
| entropy                 | 2.4584076  |
| explained_variance_t... | 0.0377     |
| meankl                  | 0.00965553 |
| optimgain               | 0.03870223 |
| surrgain                | 0.03870223 |
----------------------------------------
********** Iteration 68 ************
Optimizing Policy...
sampling
Eval num_timesteps=69632, episode_reward=6.70 +/- 5.01
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 0.963 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.107          0
         1      0.134     0.0176
         2     0.0588      0.044
         3     0.0127     0.0667
         4      0.011      0.104
         5    0.00765      0.115
         6    0.00968      0.213
         7    0.00566      0.318
         8     0.0576      0.449
         9    0.00388      0.478
        10    0.00347      0.541
done in 0.013 seconds
Expected: 0.031 Actual: 0.026
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -3.22       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 471         |
| TimeElapsed             | 46.1        |
| TimestepsSoFar          | 70656       |
| entloss                 | 0.0         |
| entropy                 | 2.4430425   |
| explained_variance_t... | 0.0957      |
| meankl                  | 0.009256258 |
| optimgain               | 0.025549836 |
| surrgain                | 0.025549836 |
-----------------------------------------
********** Iteration 69 ************
Optimizing Policy...
sampling
done in 0.557 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.517          0
         1     0.0273     0.0142
         2      0.035     0.0436
         3     0.0124     0.0692
         4      0.017     0.0923
         5    0.00509      0.125
         6    0.00669      0.161
         7    0.00636      0.286
         8     0.0147      0.295
         9    0.00468      0.444
        10    0.00841      0.548
done in 0.012 seconds
Expected: 0.030 Actual: 0.026
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -3.94       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 477         |
| TimeElapsed             | 46.7        |
| TimestepsSoFar          | 71680       |
| entloss                 | 0.0         |
| entropy                 | 2.4236574   |
| explained_variance_t... | 0.0757      |
| meankl                  | 0.008821064 |
| optimgain               | 0.025963612 |
| surrgain                | 0.025963612 |
-----------------------------------------
********** Iteration 70 ************
Optimizing Policy...
sampling
done in 0.554 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0802          0
         1     0.0532     0.0102
         2     0.0392     0.0231
         3     0.0138     0.0552
         4     0.0158     0.0725
         5    0.00528      0.103
         6    0.00976      0.213
         7    0.00494      0.297
         8     0.0728      0.341
         9    0.00276      0.409
        10     0.0036      0.453
done in 0.012 seconds
Expected: 0.026 Actual: 0.024
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.3        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 484         |
| TimeElapsed             | 47.3        |
| TimestepsSoFar          | 72704       |
| entloss                 | 0.0         |
| entropy                 | 2.4473062   |
| explained_variance_t... | 0.101       |
| meankl                  | 0.008374013 |
| optimgain               | 0.024145922 |
| surrgain                | 0.024145922 |
-----------------------------------------
********** Iteration 71 ************
Optimizing Policy...
sampling
done in 0.566 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.106          0
         1     0.0893     0.0152
         2     0.0646     0.0311
         3     0.0821      0.136
         4     0.0212      0.177
         5      0.023      0.233
         6    0.00934      0.313
         7    0.00627      0.387
         8      0.184      0.554
         9     0.0134      0.633
        10    0.00574       1.17
done in 0.014 seconds
Expected: 0.045 Actual: 0.039
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.73       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 491         |
| TimeElapsed             | 47.9        |
| TimestepsSoFar          | 73728       |
| entloss                 | 0.0         |
| entropy                 | 2.4468596   |
| explained_variance_t... | -0.05       |
| meankl                  | 0.011312802 |
| optimgain               | 0.039468784 |
| surrgain                | 0.039468784 |
-----------------------------------------
********** Iteration 72 ************
Optimizing Policy...
sampling
done in 0.603 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.069          0
         1      0.133     0.0538
         2     0.0732     0.0759
         3     0.0253      0.101
         4     0.0143      0.146
         5     0.0193      0.183
         6     0.0102      0.225
         7     0.0156      0.322
         8     0.0097      0.477
         9     0.0547      0.513
        10    0.00241       0.56
done in 0.018 seconds
Expected: 0.035 Actual: 0.031
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.23       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 498         |
| TimeElapsed             | 48.6        |
| TimestepsSoFar          | 74752       |
| entloss                 | 0.0         |
| entropy                 | 2.440023    |
| explained_variance_t... | 0.0667      |
| meankl                  | 0.010638161 |
| optimgain               | 0.031287603 |
| surrgain                | 0.031287603 |
-----------------------------------------
********** Iteration 73 ************
Optimizing Policy...
sampling
done in 0.615 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0842          0
         1      0.167     0.0202
         2      0.101     0.0409
         3     0.0476     0.0816
         4     0.0508      0.119
         5    0.00298      0.165
         6    0.00627      0.196
         7      0.021      0.293
         8     0.0226      0.305
         9    0.00666      0.402
        10    0.00304      0.485
done in 0.014 seconds
Expected: 0.032 Actual: 0.027
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.75       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 505         |
| TimeElapsed             | 49.3        |
| TimestepsSoFar          | 75776       |
| entloss                 | 0.0         |
| entropy                 | 2.4400048   |
| explained_variance_t... | 0.0529      |
| meankl                  | 0.010147266 |
| optimgain               | 0.027364135 |
| surrgain                | 0.027364135 |
-----------------------------------------
********** Iteration 74 ************
Optimizing Policy...
sampling
done in 0.617 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0        1.3          0
         1      0.389     0.0196
         2      0.554     0.0633
         3      0.229       0.18
         4      0.241      0.261
         5     0.0666      0.303
         6     0.0712      0.363
         7     0.0185      0.426
         8      0.304      0.451
         9     0.0196      0.616
        10    0.00824      0.803
done in 0.014 seconds
Expected: 0.068 Actual: 0.064
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -8.06        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 512          |
| TimeElapsed             | 49.9         |
| TimestepsSoFar          | 76800        |
| entloss                 | 0.0          |
| entropy                 | 2.4308448    |
| explained_variance_t... | 0.0979       |
| meankl                  | 0.0064191306 |
| optimgain               | 0.06373991   |
| surrgain                | 0.06373991   |
------------------------------------------
********** Iteration 75 ************
Optimizing Policy...
sampling
done in 0.608 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0899          0
         1     0.0544     0.0109
         2      0.057      0.023
         3     0.0227      0.127
         4     0.0121      0.138
         5     0.0107      0.174
         6     0.0193      0.244
         7     0.0109      0.308
         8     0.0612      0.455
         9     0.0047      0.477
        10    0.00377      0.546
done in 0.014 seconds
Expected: 0.032 Actual: 0.029
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.99       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 518         |
| TimeElapsed             | 50.6        |
| TimestepsSoFar          | 77824       |
| entloss                 | 0.0         |
| entropy                 | 2.3913882   |
| explained_variance_t... | 0.0797      |
| meankl                  | 0.010602908 |
| optimgain               | 0.028576933 |
| surrgain                | 0.028576933 |
-----------------------------------------
********** Iteration 76 ************
Optimizing Policy...
sampling
done in 0.579 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.326          0
         1      0.113    0.00662
         2       0.16     0.0306
         3     0.0961     0.0813
         4     0.0411      0.145
         5     0.0527      0.214
         6     0.0656      0.261
         7     0.0225      0.309
         8      0.244        0.4
         9    0.00792      0.425
        10     0.0068      0.492
done in 0.013 seconds
Expected: 0.041 Actual: 0.032
Stepsize OK!
vf
done in 0.019 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -7.13        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 525          |
| TimeElapsed             | 51.2         |
| TimestepsSoFar          | 78848        |
| entloss                 | 0.0          |
| entropy                 | 2.409024     |
| explained_variance_t... | 0.232        |
| meankl                  | 0.0142034795 |
| optimgain               | 0.031537883  |
| surrgain                | 0.031537883  |
------------------------------------------
********** Iteration 77 ************
Optimizing Policy...
sampling
done in 0.571 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.278          0
         1     0.0984      0.021
         2     0.0725     0.0283
         3     0.0415     0.0743
         4      0.016      0.135
         5     0.0194      0.186
         6     0.0123      0.198
         7      0.016       0.29
         8     0.0296      0.487
         9     0.0368      0.504
        10    0.00615      0.659
done in 0.013 seconds
Expected: 0.038 Actual: 0.019
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.47       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 532         |
| TimeElapsed             | 51.8        |
| TimestepsSoFar          | 79872       |
| entloss                 | 0.0         |
| entropy                 | 2.4083278   |
| explained_variance_t... | 0.27        |
| meankl                  | 0.006332217 |
| optimgain               | 0.01892085  |
| surrgain                | 0.01892085  |
-----------------------------------------
********** Iteration 78 ************
Optimizing Policy...
sampling
Eval num_timesteps=79872, episode_reward=1.66 +/- 11.49
Episode length: 150.00 +/- 0.00
done in 0.981 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.145          0
         1     0.0858     0.0155
         2      0.039     0.0251
         3     0.0303     0.0484
         4     0.0282     0.0922
         5     0.0107      0.105
         6     0.0128      0.158
         7    0.00695      0.306
         8    0.00649      0.372
         9     0.0695      0.399
        10    0.00895      0.496
done in 0.013 seconds
Expected: 0.030 Actual: 0.028
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.02       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 539         |
| TimeElapsed             | 52.8        |
| TimestepsSoFar          | 80896       |
| entloss                 | 0.0         |
| entropy                 | 2.4123967   |
| explained_variance_t... | -0.168      |
| meankl                  | 0.009669207 |
| optimgain               | 0.028264351 |
| surrgain                | 0.028264351 |
-----------------------------------------
********** Iteration 79 ************
Optimizing Policy...
sampling
done in 0.568 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.549          0
         1      0.899     0.0282
         2      0.366     0.0751
         3      0.033      0.122
         4     0.0424      0.128
         5     0.0236      0.224
         6     0.0336      0.282
         7     0.0108      0.429
         8      0.203      0.462
         9    0.00865      0.545
        10     0.0128      0.654
done in 0.013 seconds
Expected: 0.052 Actual: 0.053
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.87       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 546         |
| TimeElapsed             | 53.4        |
| TimestepsSoFar          | 81920       |
| entloss                 | 0.0         |
| entropy                 | 2.412964    |
| explained_variance_t... | 0.303       |
| meankl                  | 0.010491669 |
| optimgain               | 0.052828006 |
| surrgain                | 0.052828006 |
-----------------------------------------
********** Iteration 80 ************
Optimizing Policy...
sampling
done in 0.570 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.248          0
         1      0.136    0.00985
         2      0.176     0.0472
         3     0.0533      0.102
         4     0.0359      0.147
         5      0.167       0.26
         6     0.0444       0.33
         7     0.0305      0.467
         8      0.142      0.486
         9    0.00952      0.708
        10    0.00435      0.816
done in 0.013 seconds
Expected: 0.049 Actual: 0.084
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.31       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 552         |
| TimeElapsed             | 54.1        |
| TimestepsSoFar          | 82944       |
| entloss                 | 0.0         |
| entropy                 | 2.4325283   |
| explained_variance_t... | 0.000163    |
| meankl                  | 0.01084381  |
| optimgain               | 0.083711565 |
| surrgain                | 0.083711565 |
-----------------------------------------
********** Iteration 81 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0554          0
         1     0.0852      0.012
         2     0.0572     0.0301
         3     0.0292     0.0642
         4    0.00597     0.0992
         5     0.0287      0.119
         6     0.0105      0.153
         7    0.00637      0.295
         8     0.0452      0.313
         9    0.00773      0.359
        10    0.00422      0.495
done in 0.013 seconds
Expected: 0.028 Actual: 0.028
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.8        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 559         |
| TimeElapsed             | 54.7        |
| TimestepsSoFar          | 83968       |
| entloss                 | 0.0         |
| entropy                 | 2.4008389   |
| explained_variance_t... | 0.0981      |
| meankl                  | 0.010456363 |
| optimgain               | 0.027627358 |
| surrgain                | 0.027627358 |
-----------------------------------------
********** Iteration 82 ************
Optimizing Policy...
sampling
done in 0.570 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.114          0
         1     0.0497    0.00649
         2      0.111     0.0459
         3     0.0286      0.106
         4     0.0164      0.141
         5     0.0103       0.18
         6    0.00851       0.26
         7     0.0112        0.3
         8     0.0174      0.306
         9     0.0041      0.457
        10    0.00663      0.627
done in 0.013 seconds
Expected: 0.034 Actual: 0.033
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.09       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 566         |
| TimeElapsed             | 55.3        |
| TimestepsSoFar          | 84992       |
| entloss                 | 0.0         |
| entropy                 | 2.3672004   |
| explained_variance_t... | 0.102       |
| meankl                  | 0.009565961 |
| optimgain               | 0.03291332  |
| surrgain                | 0.03291332  |
-----------------------------------------
********** Iteration 83 ************
Optimizing Policy...
sampling
done in 0.568 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.115          0
         1     0.0257    0.00382
         2       0.05      0.037
         3     0.0227     0.0642
         4      0.016     0.0783
         5     0.0025     0.0863
         6    0.00878      0.142
         7      0.136      0.187
         8    0.00832      0.267
         9      0.012      0.397
        10    0.00285      0.471
done in 0.013 seconds
Expected: 0.024 Actual: 0.024
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.48       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 573         |
| TimeElapsed             | 55.9        |
| TimestepsSoFar          | 86016       |
| entloss                 | 0.0         |
| entropy                 | 2.3452115   |
| explained_variance_t... | -0.0746     |
| meankl                  | 0.012590663 |
| optimgain               | 0.024377557 |
| surrgain                | 0.024377557 |
-----------------------------------------
********** Iteration 84 ************
Optimizing Policy...
sampling
done in 0.566 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0875          0
         1      0.121      0.017
         2       0.11     0.0395
         3     0.0386     0.0893
         4     0.0383       0.13
         5      0.168      0.225
         6     0.0161      0.312
         7     0.0285      0.479
         8     0.0483      0.646
         9     0.0124      0.658
        10      0.012        0.9
done in 0.012 seconds
Expected: 0.045 Actual: 0.043
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.26       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 580         |
| TimeElapsed             | 56.5        |
| TimestepsSoFar          | 87040       |
| entloss                 | 0.0         |
| entropy                 | 2.3359778   |
| explained_variance_t... | -0.00471    |
| meankl                  | 0.012487294 |
| optimgain               | 0.043067243 |
| surrgain                | 0.043067243 |
-----------------------------------------
********** Iteration 85 ************
Optimizing Policy...
sampling
done in 0.570 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.053          0
         1      0.152     0.0228
         2     0.0782     0.0547
         3     0.0184     0.0791
         4     0.0752      0.118
         5     0.0139      0.162
         6     0.0185      0.193
         7     0.0212      0.277
         8     0.0128      0.471
         9     0.0276      0.642
        10     0.0102      0.652
done in 0.013 seconds
Expected: 0.035 Actual: 0.038
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.57       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 587         |
| TimeElapsed             | 57.1        |
| TimestepsSoFar          | 88064       |
| entloss                 | 0.0         |
| entropy                 | 2.3510926   |
| explained_variance_t... | -0.0306     |
| meankl                  | 0.008917859 |
| optimgain               | 0.038217947 |
| surrgain                | 0.038217947 |
-----------------------------------------
********** Iteration 86 ************
Optimizing Policy...
sampling
done in 0.563 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.124          0
         1     0.0286     0.0142
         2     0.0236     0.0165
         3     0.0169     0.0475
         4     0.0354     0.0757
         5    0.00856     0.0947
         6    0.00406      0.128
         7    0.00319      0.199
         8     0.0648      0.219
         9    0.00212      0.333
        10    0.00347      0.446
done in 0.014 seconds
Expected: 0.025 Actual: 0.025
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.55       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 593         |
| TimeElapsed             | 57.7        |
| TimestepsSoFar          | 89088       |
| entloss                 | 0.0         |
| entropy                 | 2.3239756   |
| explained_variance_t... | 0.301       |
| meankl                  | 0.010289238 |
| optimgain               | 0.024801575 |
| surrgain                | 0.024801575 |
-----------------------------------------
********** Iteration 87 ************
Optimizing Policy...
sampling
Eval num_timesteps=89088, episode_reward=1.39 +/- 8.08
Episode length: 150.00 +/- 0.00
done in 0.961 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.607          0
         1      0.136     0.0124
         2       0.12     0.0313
         3     0.0301     0.0658
         4     0.0447     0.0843
         5     0.0124       0.11
         6     0.0263      0.159
         7    0.00801      0.259
         8     0.0291      0.265
         9    0.00829      0.369
        10      0.003      0.499
done in 0.014 seconds
Expected: 0.036 Actual: 0.031
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.96       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 600         |
| TimeElapsed             | 58.7        |
| TimestepsSoFar          | 90112       |
| entloss                 | 0.0         |
| entropy                 | 2.3241377   |
| explained_variance_t... | 0.102       |
| meankl                  | 0.008762386 |
| optimgain               | 0.031470302 |
| surrgain                | 0.031470302 |
-----------------------------------------
********** Iteration 88 ************
Optimizing Policy...
sampling
done in 0.562 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.129          0
         1     0.0468     0.0177
         2     0.0632      0.036
         3     0.0547     0.0478
         4     0.0294     0.0816
         5     0.0164      0.093
         6     0.0146      0.139
         7     0.0198      0.246
         8     0.0085      0.423
         9    0.00714      0.509
        10     0.0122      0.514
done in 0.013 seconds
Expected: 0.032 Actual: 0.034
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.08       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 607         |
| TimeElapsed             | 59.3        |
| TimestepsSoFar          | 91136       |
| entloss                 | 0.0         |
| entropy                 | 2.3282437   |
| explained_variance_t... | 0.169       |
| meankl                  | 0.010388812 |
| optimgain               | 0.03428375  |
| surrgain                | 0.03428375  |
-----------------------------------------
********** Iteration 89 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0603          0
         1      0.159     0.0272
         2      0.231     0.0652
         3     0.0454       0.12
         4     0.0344      0.169
         5     0.0202      0.182
         6     0.0213      0.247
         7     0.0099      0.419
         8     0.0137      0.461
         9     0.0428      0.474
        10     0.0176      0.521
done in 0.013 seconds
Expected: 0.037 Actual: 0.031
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.2        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 614         |
| TimeElapsed             | 60          |
| TimestepsSoFar          | 92160       |
| entloss                 | 0.0         |
| entropy                 | 2.3044302   |
| explained_variance_t... | 0.0819      |
| meankl                  | 0.009089628 |
| optimgain               | 0.031299517 |
| surrgain                | 0.031299517 |
-----------------------------------------
********** Iteration 90 ************
Optimizing Policy...
sampling
done in 0.574 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0973          0
         1      0.243     0.0307
         2     0.0324     0.0537
         3     0.0378     0.0748
         4     0.0254      0.093
         5     0.0377      0.128
         6     0.0136      0.147
         7     0.0141      0.224
         8    0.00997      0.371
         9     0.0199      0.378
        10    0.00814      0.475
done in 0.012 seconds
Expected: 0.033 Actual: 0.032
Stepsize OK!
vf
done in 0.017 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.25       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 621         |
| TimeElapsed             | 60.6        |
| TimestepsSoFar          | 93184       |
| entloss                 | 0.0         |
| entropy                 | 2.2846859   |
| explained_variance_t... | 0.19        |
| meankl                  | 0.010954713 |
| optimgain               | 0.032376148 |
| surrgain                | 0.032376148 |
-----------------------------------------
********** Iteration 91 ************
Optimizing Policy...
sampling
done in 0.567 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0852          0
         1      0.142     0.0117
         2     0.0819     0.0464
         3     0.0617     0.0931
         4     0.0259      0.152
         5     0.0558      0.166
         6     0.0219      0.318
         7     0.0141      0.496
         8      0.201      0.549
         9     0.0171      0.625
        10     0.0103      0.845
done in 0.012 seconds
Expected: 0.044 Actual: 0.042
violated KL constraint. shrinking step.
Expected: 0.044 Actual: 0.022
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -4.65        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 628          |
| TimeElapsed             | 61.2         |
| TimestepsSoFar          | 94208        |
| entloss                 | 0.0          |
| entropy                 | 2.270953     |
| explained_variance_t... | 0.152        |
| meankl                  | 0.0030363393 |
| optimgain               | 0.0216585    |
| surrgain                | 0.0216585    |
------------------------------------------
********** Iteration 92 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.437          0
         1     0.0733    0.00826
         2      0.106      0.023
         3     0.0607     0.0512
         4      0.022      0.114
         5     0.0182       0.17
         6     0.0111      0.302
         7      0.123      0.345
         8     0.0071       0.37
         9      0.015       0.44
        10     0.0311      0.455
done in 0.013 seconds
Expected: 0.035 Actual: 0.035
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.05       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 634         |
| TimeElapsed             | 61.8        |
| TimestepsSoFar          | 95232       |
| entloss                 | 0.0         |
| entropy                 | 2.2487454   |
| explained_variance_t... | 0.229       |
| meankl                  | 0.012351373 |
| optimgain               | 0.03460423  |
| surrgain                | 0.03460423  |
-----------------------------------------
********** Iteration 93 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0546          0
         1      0.058     0.0125
         2     0.0476     0.0233
         3     0.0439     0.0541
         4     0.0137      0.115
         5     0.0899      0.186
         6    0.00944      0.262
         7     0.0133      0.382
         8     0.0184      0.426
         9    0.00512      0.432
        10    0.00336      0.517
done in 0.013 seconds
Expected: 0.031 Actual: 0.031
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.67       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 641         |
| TimeElapsed             | 62.4        |
| TimestepsSoFar          | 96256       |
| entloss                 | 0.0         |
| entropy                 | 2.2720633   |
| explained_variance_t... | 0.0846      |
| meankl                  | 0.010184593 |
| optimgain               | 0.03083431  |
| surrgain                | 0.03083431  |
-----------------------------------------
********** Iteration 94 ************
Optimizing Policy...
sampling
done in 0.548 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0759          0
         1     0.0847     0.0162
         2       0.13     0.0318
         3     0.0612     0.0627
         4     0.0403     0.0887
         5     0.0294       0.13
         6    0.00966       0.23
         7    0.00399      0.336
         8      0.162      0.399
         9      0.003      0.455
        10    0.00693      0.531
done in 0.012 seconds
Expected: 0.034 Actual: 0.034
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.16       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 648         |
| TimeElapsed             | 63          |
| TimestepsSoFar          | 97280       |
| entloss                 | 0.0         |
| entropy                 | 2.291697    |
| explained_variance_t... | 0.127       |
| meankl                  | 0.009761792 |
| optimgain               | 0.034436952 |
| surrgain                | 0.034436952 |
-----------------------------------------
********** Iteration 95 ************
Optimizing Policy...
sampling
done in 0.561 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.186          0
         1     0.0398    0.00597
         2     0.0861     0.0326
         3     0.0502     0.0674
         4     0.0261      0.194
         5      0.049      0.233
         6     0.0425      0.416
         7      0.143      0.486
         8     0.0199      0.512
         9     0.0109      0.635
        10    0.00822      0.827
done in 0.012 seconds
Expected: 0.042 Actual: 0.029
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -3.92       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 655         |
| TimeElapsed             | 63.6        |
| TimestepsSoFar          | 98304       |
| entloss                 | 0.0         |
| entropy                 | 2.259888    |
| explained_variance_t... | 0.129       |
| meankl                  | 0.011409007 |
| optimgain               | 0.028844768 |
| surrgain                | 0.028844768 |
-----------------------------------------
********** Iteration 96 ************
Optimizing Policy...
sampling
done in 0.565 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.355          0
         1      0.372     0.0167
         2     0.0664     0.0427
         3     0.0632     0.0702
         4     0.0621     0.0879
         5     0.0091      0.137
         6    0.00673      0.241
         7     0.0202      0.295
         8      0.037      0.304
         9     0.0087      0.388
        10    0.00518      0.599
done in 0.012 seconds
Expected: 0.039 Actual: 0.037
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -4.63       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 662         |
| TimeElapsed             | 64.2        |
| TimestepsSoFar          | 99328       |
| entloss                 | 0.0         |
| entropy                 | 2.253232    |
| explained_variance_t... | 0.0848      |
| meankl                  | 0.011385054 |
| optimgain               | 0.036888536 |
| surrgain                | 0.036888536 |
-----------------------------------------
********** Iteration 97 ************
Optimizing Policy...
sampling
Eval num_timesteps=99328, episode_reward=1.57 +/- 13.10
Episode length: 150.00 +/- 0.00
done in 0.978 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.114          0
         1      0.136      0.015
         2     0.0783     0.0298
         3     0.0383     0.0515
         4     0.0358     0.0864
         5     0.0281      0.107
         6     0.0206      0.189
         7     0.0156       0.28
         8     0.0388      0.434
         9      0.027      0.445
        10     0.0207      0.679
done in 0.013 seconds
Expected: 0.037 Actual: 0.035
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -3.89       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 669         |
| TimeElapsed             | 65.2        |
| TimestepsSoFar          | 100352      |
| entloss                 | 0.0         |
| entropy                 | 2.2552052   |
| explained_variance_t... | 0.253       |
| meankl                  | 0.009456231 |
| optimgain               | 0.03485272  |
| surrgain                | 0.03485272  |
-----------------------------------------
Saving to logs/train_0.1M_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
