WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:407: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:241: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:242: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f0c7d5114a8> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f0c7d5110b8>
  "{} != {}".format(self.training_env, self.eval_env))
********** Iteration 0 ************
Optimizing Policy...
sampling
done in 0.649 seconds
computegrad
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:364: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

done in 0.099 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0637          0
         1      0.018     0.0298
         2    0.00144     0.0829
         3    0.00169      0.187
         4   0.000975      0.265
         5    0.00124        0.3
         6    0.00156       0.31
         7   0.000817      0.494
         8   0.000153      0.585
         9   0.000125      0.737
        10   0.000212      0.825
done in 0.157 seconds
Expected: 0.026 Actual: 0.026
Stepsize OK!
vf
done in 0.054 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13.2        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 6            |
| TimeElapsed             | 1.03         |
| TimestepsSoFar          | 1024         |
| entloss                 | 0.0          |
| entropy                 | 2.8582757    |
| explained_variance_t... | 0.00628      |
| meankl                  | 0.0082490705 |
| optimgain               | 0.025877208  |
| surrgain                | 0.025877208  |
------------------------------------------
********** Iteration 1 ************
Optimizing Policy...
sampling
done in 0.580 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0183          0
         1     0.0375     0.0654
         2    0.00334     0.0891
         3      0.015      0.104
         4    0.00218      0.165
         5    0.00292      0.285
         6    0.00224      0.484
         7   0.000978      0.578
         8    0.00913      0.606
         9   0.000721      0.671
        10    0.00287      0.704
done in 0.013 seconds
Expected: 0.026 Actual: 0.026
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -15.1        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 13           |
| TimeElapsed             | 1.66         |
| TimestepsSoFar          | 2048         |
| entloss                 | 0.0          |
| entropy                 | 2.8209925    |
| explained_variance_t... | -0.0201      |
| meankl                  | 0.0149935605 |
| optimgain               | 0.02568912   |
| surrgain                | 0.02568912   |
------------------------------------------
********** Iteration 2 ************
Optimizing Policy...
sampling
done in 0.588 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.126          0
         1     0.0213     0.0165
         2     0.0429     0.0413
         3    0.00424     0.0898
         4    0.00352      0.178
         5     0.0018      0.237
         6    0.00207      0.322
         7     0.0203      0.352
         8    0.00139      0.456
         9    0.00246      0.464
        10   0.000645      0.522
done in 0.014 seconds
Expected: 0.027 Actual: 0.026
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -17.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 2.29        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 2.797446    |
| explained_variance_t... | 0.0367      |
| meankl                  | 0.010072967 |
| optimgain               | 0.02608918  |
| surrgain                | 0.02608918  |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
sampling
done in 0.587 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0307          0
         1     0.0171     0.0112
         2    0.00779      0.108
         3     0.0174      0.114
         4    0.00254      0.224
         5     0.0042      0.315
         6    0.00425      0.416
         7    0.00384      0.547
         8     0.0187      0.573
         9      0.029      0.666
        10    0.00242       0.71
done in 0.013 seconds
Expected: 0.028 Actual: 0.016
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 27          |
| TimeElapsed             | 2.92        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 2.797036    |
| explained_variance_t... | -0.0367     |
| meankl                  | 0.012988325 |
| optimgain               | 0.015964556 |
| surrgain                | 0.015964556 |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
sampling
done in 0.575 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.068          0
         1     0.0191     0.0116
         2     0.0737     0.0535
         3    0.00849      0.108
         4    0.00952      0.304
         5    0.00586      0.435
         6    0.00267       0.52
         7     0.0143       0.58
         8    0.00256      0.593
         9     0.0168      0.632
        10    0.00104       0.66
done in 0.013 seconds
Expected: 0.032 Actual: 0.016
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 34          |
| TimeElapsed             | 3.54        |
| TimestepsSoFar          | 5120        |
| entloss                 | 0.0         |
| entropy                 | 2.8080418   |
| explained_variance_t... | -0.0252     |
| meankl                  | 0.008381998 |
| optimgain               | 0.016121332 |
| surrgain                | 0.016121332 |
-----------------------------------------
********** Iteration 5 ************
Optimizing Policy...
sampling
done in 0.582 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.195          0
         1     0.0331     0.0193
         2      0.117     0.0573
         3    0.00538      0.146
         4    0.00406      0.215
         5    0.00294      0.336
         6    0.00396      0.503
         7     0.0254      0.612
         8     0.0044      0.648
         9     0.0212      0.689
        10    0.00161      0.784
done in 0.012 seconds
Expected: 0.035 Actual: 0.027
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.4       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 4.16        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 2.8275754   |
| explained_variance_t... | 0.0194      |
| meankl                  | 0.010738538 |
| optimgain               | 0.027354382 |
| surrgain                | 0.027354382 |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
sampling
done in 0.578 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.108          0
         1     0.0308     0.0203
         2    0.00635        0.1
         3     0.0319      0.113
         4    0.00686      0.188
         5    0.00512      0.287
         6    0.00312      0.429
         7    0.00148      0.512
         8     0.0243      0.575
         9    0.00526      0.632
        10     0.0132       0.66
done in 0.014 seconds
Expected: 0.032 Actual: 0.028
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 47          |
| TimeElapsed             | 4.79        |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 2.8254976   |
| explained_variance_t... | 0.0129      |
| meankl                  | 0.008822693 |
| optimgain               | 0.027723448 |
| surrgain                | 0.027723448 |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
sampling
done in 0.583 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.111          0
         1      0.149     0.0619
         2     0.0118      0.134
         3     0.0107      0.138
         4    0.00661      0.181
         5     0.0032      0.322
         6      0.001      0.385
         7    0.00316       0.43
         8    0.00347      0.625
         9    0.00765      0.653
        10    0.00339      0.741
done in 0.013 seconds
Expected: 0.038 Actual: 0.034
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 54          |
| TimeElapsed             | 5.41        |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 2.8238804   |
| explained_variance_t... | 0.0493      |
| meankl                  | 0.009785575 |
| optimgain               | 0.03369589  |
| surrgain                | 0.03369589  |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
sampling
done in 0.580 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0173          0
         1     0.0342     0.0156
         2    0.00789      0.103
         3     0.0597      0.175
         4    0.00588       0.25
         5    0.00411      0.402
         6    0.00248      0.513
         7    0.00573      0.635
         8    0.00707      0.648
         9    0.00246       0.81
        10     0.0165      0.872
done in 0.013 seconds
Expected: 0.032 Actual: 0.046
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 6.03        |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 2.8132405   |
| explained_variance_t... | 0.0288      |
| meankl                  | 0.010250864 |
| optimgain               | 0.04577987  |
| surrgain                | 0.04577987  |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
sampling
Eval num_timesteps=9216, episode_reward=-4.35 +/- 9.59
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.074 seconds
computegrad
done in 0.003 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0122          0
         1     0.0285     0.0221
         2     0.0111     0.0514
         3    0.00143     0.0576
         4    0.00144      0.131
         5    0.00142      0.191
         6    0.00126      0.283
         7    0.00126      0.349
         8    0.00266      0.356
         9    0.00198      0.396
        10   0.000875      0.405
done in 0.012 seconds
Expected: 0.018 Actual: 0.016
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 68          |
| TimeElapsed             | 7.15        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 2.8052285   |
| explained_variance_t... | -0.0297     |
| meankl                  | 0.009134547 |
| optimgain               | 0.015988475 |
| surrgain                | 0.015988475 |
-----------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
