WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 0
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=100000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:407: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:241: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:242: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_0.1M_Reacher2Dof-v0/trpo/Reacher2Dof-v0_1
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7fec86b676a0> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fec86b67400>
  "{} != {}".format(self.training_env, self.eval_env))
********** Iteration 0 ************
Optimizing Policy...
sampling
done in 0.720 seconds
computegrad
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:364: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

done in 0.141 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0213          0
         1     0.0309     0.0266
         2    0.00412      0.115
         3    0.00316      0.186
         4    0.00505      0.336
         5     0.0311      0.411
         6   0.000914      0.607
         7   0.000293      0.762
         8   0.000437      0.835
         9   0.000479      0.927
        10    0.00135      0.933
done in 0.218 seconds
Expected: 0.031 Actual: 0.033
Stepsize OK!
vf
done in 0.064 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.5       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 6           |
| TimeElapsed             | 1.25        |
| TimestepsSoFar          | 1024        |
| entloss                 | 0.0         |
| entropy                 | 2.8400354   |
| explained_variance_t... | 0.00628     |
| meankl                  | 0.008124568 |
| optimgain               | 0.032928392 |
| surrgain                | 0.032928392 |
-----------------------------------------
********** Iteration 1 ************
Optimizing Policy...
sampling
done in 0.627 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0981          0
         1     0.0223     0.0337
         2    0.00695      0.122
         3     0.0159      0.136
         4    0.00222        0.2
         5    0.00292      0.297
         6    0.00163      0.399
         7    0.00208      0.526
         8    0.00128      0.615
         9    0.00532      0.684
        10   0.000653      0.704
done in 0.015 seconds
Expected: 0.032 Actual: 0.031
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.1        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 13           |
| TimeElapsed             | 1.92         |
| TimestepsSoFar          | 2048         |
| entloss                 | 0.0          |
| entropy                 | 2.8579001    |
| explained_variance_t... | -0.0362      |
| meankl                  | 0.0074477037 |
| optimgain               | 0.030769061  |
| surrgain                | 0.030769061  |
------------------------------------------
********** Iteration 2 ************
Optimizing Policy...
sampling
done in 0.645 seconds
computegrad
done in 0.006 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0543          0
         1     0.0325     0.0257
         2     0.0214     0.0954
         3    0.00418      0.108
         4    0.00369      0.194
         5    0.00284      0.314
         6    0.00244      0.436
         7    0.00196       0.55
         8     0.0162      0.599
         9    0.00245      0.696
        10     0.0111       0.75
done in 0.014 seconds
Expected: 0.030 Actual: 0.030
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 2.62        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 2.8243105   |
| explained_variance_t... | -0.000174   |
| meankl                  | 0.010881704 |
| optimgain               | 0.029977534 |
| surrgain                | 0.029977534 |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
sampling
done in 0.671 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0506          0
         1     0.0176     0.0261
         2    0.00352     0.0855
         3    0.00504      0.125
         4    0.00429       0.14
         5    0.00304      0.204
         6    0.00259      0.431
         7    0.00172      0.641
         8   0.000897      0.697
         9    0.00798      0.739
        10    0.00174      0.823
done in 0.014 seconds
Expected: 0.028 Actual: 0.026
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 27          |
| TimeElapsed             | 3.34        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 2.814606    |
| explained_variance_t... | 0.0132      |
| meankl                  | 0.008991376 |
| optimgain               | 0.02580373  |
| surrgain                | 0.02580373  |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
sampling
done in 0.680 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0391          0
         1      0.033     0.0326
         2    0.00461     0.0663
         3    0.00337     0.0717
         4     0.0065       0.17
         5    0.00393      0.394
         6    0.00245      0.545
         7   0.000703      0.613
         8    0.00191       0.66
         9    0.00307      0.672
        10    0.00155      0.791
done in 0.016 seconds
Expected: 0.028 Actual: 0.026
Stepsize OK!
vf
done in 0.025 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13.6        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 34           |
| TimeElapsed             | 4.07         |
| TimestepsSoFar          | 5120         |
| entloss                 | 0.0          |
| entropy                 | 2.8143399    |
| explained_variance_t... | 0.000208     |
| meankl                  | 0.0066558793 |
| optimgain               | 0.025655864  |
| surrgain                | 0.025655864  |
------------------------------------------
********** Iteration 5 ************
Optimizing Policy...
sampling
done in 0.694 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.038          0
         1     0.0136     0.0212
         2    0.00332     0.0559
         3    0.00428       0.13
         4     0.0122       0.17
         5    0.00404      0.271
         6    0.00365      0.452
         7    0.00228      0.557
         8   0.000813      0.631
         9    0.00697      0.654
        10    0.00404      0.811
done in 0.017 seconds
Expected: 0.027 Actual: 0.025
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12         |
| EpThisIter              | 6           |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 4.82        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 2.8265772   |
| explained_variance_t... | 0.0178      |
| meankl                  | 0.009130114 |
| optimgain               | 0.02547949  |
| surrgain                | 0.02547949  |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
sampling
done in 0.656 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.012          0
         1     0.0168     0.0225
         2    0.00467     0.0544
         3     0.0232     0.0848
         4    0.00351      0.152
         5     0.0048       0.26
         6    0.00397      0.478
         7    0.00117      0.547
         8    0.00405       0.64
         9    0.00289       0.78
        10    0.00618      0.803
done in 0.014 seconds
Expected: 0.026 Actual: 0.023
Stepsize OK!
vf
done in 0.022 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -12.4      |
| EpThisIter              | 7          |
| EpisodesSoFar           | 47         |
| TimeElapsed             | 5.53       |
| TimestepsSoFar          | 7168       |
| entloss                 | 0.0        |
| entropy                 | 2.8389914  |
| explained_variance_t... | -0.0327    |
| meankl                  | 0.01109085 |
| optimgain               | 0.02327318 |
| surrgain                | 0.02327318 |
----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
sampling
done in 0.653 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0756          0
         1     0.0267     0.0319
         2     0.0125      0.079
         3     0.0335      0.111
         4     0.0107      0.262
         5     0.0043      0.372
         6    0.00613      0.436
         7    0.00554       0.55
         8    0.00432      0.715
         9    0.00113       0.81
        10    0.00743      0.832
done in 0.015 seconds
Expected: 0.036 Actual: 0.034
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.4       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 54          |
| TimeElapsed             | 6.23        |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 2.854228    |
| explained_variance_t... | 0.0278      |
| meankl                  | 0.009148272 |
| optimgain               | 0.0343536   |
| surrgain                | 0.0343536   |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
sampling
done in 0.622 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0398          0
         1     0.0176     0.0225
         2    0.00748     0.0776
         3    0.00392      0.086
         4    0.00549      0.171
         5    0.00219      0.265
         6    0.00237      0.339
         7    0.00138      0.409
         8    0.00161      0.455
         9    0.00921      0.563
        10    0.00252      0.609
done in 0.014 seconds
Expected: 0.025 Actual: 0.020
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 6.9         |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 2.8756993   |
| explained_variance_t... | 0.0567      |
| meankl                  | 0.007912262 |
| optimgain               | 0.019674867 |
| surrgain                | 0.019674867 |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
sampling
Eval num_timesteps=9216, episode_reward=5.78 +/- 6.20
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.209 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0214          0
         1     0.0262     0.0158
         2    0.00487      0.079
         3     0.0062     0.0851
         4    0.00291      0.133
         5    0.00323      0.223
         6    0.00305      0.353
         7    0.00237      0.513
         8    0.00785      0.531
         9    0.00219      0.605
        10    0.00211      0.786
done in 0.015 seconds
Expected: 0.026 Actual: 0.026
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 68          |
| TimeElapsed             | 8.16        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 2.8621514   |
| explained_variance_t... | -0.0445     |
| meankl                  | 0.009939874 |
| optimgain               | 0.025507543 |
| surrgain                | 0.025507543 |
-----------------------------------------
********** Iteration 10 ************
Optimizing Policy...
sampling
done in 0.700 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0444          0
         1      0.137     0.0554
         2     0.0041      0.129
         3    0.00766      0.195
         4     0.0398      0.321
         5    0.00803      0.392
         6    0.00398      0.494
         7    0.00506      0.614
         8      0.024      0.651
         9    0.00349      0.776
        10    0.00156      0.898
done in 0.016 seconds
Expected: 0.036 Actual: 0.033
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 75          |
| TimeElapsed             | 8.91        |
| TimestepsSoFar          | 11264       |
| entloss                 | 0.0         |
| entropy                 | 2.8550084   |
| explained_variance_t... | -0.0456     |
| meankl                  | 0.010046399 |
| optimgain               | 0.032737352 |
| surrgain                | 0.032737352 |
-----------------------------------------
********** Iteration 11 ************
Optimizing Policy...
sampling
done in 0.693 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0293          0
         1     0.0338     0.0174
         2     0.0126     0.0683
         3    0.00927     0.0798
         4    0.00457      0.145
         5    0.00377      0.246
         6    0.00305      0.394
         7    0.00296      0.501
         8    0.00996      0.517
         9     0.0018      0.629
        10    0.00163      0.712
done in 0.016 seconds
Expected: 0.028 Actual: 0.026
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.2       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 81          |
| TimeElapsed             | 9.66        |
| TimestepsSoFar          | 12288       |
| entloss                 | 0.0         |
| entropy                 | 2.8381956   |
| explained_variance_t... | -0.0137     |
| meankl                  | 0.00925394  |
| optimgain               | 0.026273603 |
| surrgain                | 0.026273603 |
-----------------------------------------
********** Iteration 12 ************
Optimizing Policy...
sampling
done in 0.696 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0765          0
         1      0.197     0.0503
         2     0.0352      0.118
         3     0.0101      0.127
         4     0.0114      0.201
         5     0.0063      0.562
         6    0.00155      0.661
         7     0.0356      0.731
         8    0.00402      0.767
         9     0.0183      0.829
        10    0.00148      0.862
done in 0.015 seconds
Expected: 0.041 Actual: 0.036
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.9       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 88          |
| TimeElapsed             | 10.4        |
| TimestepsSoFar          | 13312       |
| entloss                 | 0.0         |
| entropy                 | 2.8616233   |
| explained_variance_t... | -0.0173     |
| meankl                  | 0.009298705 |
| optimgain               | 0.03569104  |
| surrgain                | 0.03569104  |
-----------------------------------------
********** Iteration 13 ************
Optimizing Policy...
sampling
done in 0.651 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.103          0
         1     0.0247     0.0282
         2     0.0513      0.102
         3    0.00883      0.128
         4    0.00437      0.174
         5     0.0053      0.228
         6    0.00346      0.329
         7    0.00418      0.475
         8     0.0032      0.619
         9    0.00414      0.631
        10     0.0133      0.693
done in 0.015 seconds
Expected: 0.033 Actual: 0.030
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 95          |
| TimeElapsed             | 11.1        |
| TimestepsSoFar          | 14336       |
| entloss                 | 0.0         |
| entropy                 | 2.8484087   |
| explained_variance_t... | -0.037      |
| meankl                  | 0.00962076  |
| optimgain               | 0.030202795 |
| surrgain                | 0.030202795 |
-----------------------------------------
********** Iteration 14 ************
Optimizing Policy...
sampling
done in 0.648 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.272          0
         1     0.0295     0.0203
         2     0.0581     0.0381
         3    0.00437     0.0849
         4    0.00312       0.12
         5    0.00361       0.19
         6    0.00398      0.332
         7    0.00398      0.479
         8      0.009      0.493
         9    0.00209      0.564
        10    0.00073      0.568
done in 0.015 seconds
Expected: 0.029 Actual: 0.028
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 102         |
| TimeElapsed             | 11.8        |
| TimestepsSoFar          | 15360       |
| entloss                 | 0.0         |
| entropy                 | 2.855161    |
| explained_variance_t... | 0.0211      |
| meankl                  | 0.009846478 |
| optimgain               | 0.028104741 |
| surrgain                | 0.028104741 |
-----------------------------------------
********** Iteration 15 ************
Optimizing Policy...
sampling
done in 0.651 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0886          0
         1     0.0888     0.0247
         2      0.082      0.113
         3    0.00728      0.131
         4    0.00629      0.192
         5    0.00431      0.262
         6    0.00434      0.407
         7    0.00621      0.505
         8     0.0047      0.514
         9    0.00377      0.599
        10     0.0016      0.605
done in 0.016 seconds
Expected: 0.035 Actual: 0.030
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 109         |
| TimeElapsed             | 12.5        |
| TimestepsSoFar          | 16384       |
| entloss                 | 0.0         |
| entropy                 | 2.8011277   |
| explained_variance_t... | -0.0362     |
| meankl                  | 0.010322746 |
| optimgain               | 0.030143052 |
| surrgain                | 0.030143052 |
-----------------------------------------
********** Iteration 16 ************
Optimizing Policy...
sampling
done in 0.691 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0721          0
         1     0.0378      0.012
         2      0.059     0.0742
         3     0.0108     0.0907
         4     0.0038      0.148
         5    0.00268      0.211
         6    0.00264        0.3
         7    0.00268      0.371
         8     0.0255      0.403
         9    0.00384      0.481
        10    0.00336      0.489
done in 0.016 seconds
Expected: 0.028 Actual: 0.029
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.73       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 116         |
| TimeElapsed             | 13.2        |
| TimestepsSoFar          | 17408       |
| entloss                 | 0.0         |
| entropy                 | 2.8032753   |
| explained_variance_t... | 0.0323      |
| meankl                  | 0.008625276 |
| optimgain               | 0.029342016 |
| surrgain                | 0.029342016 |
-----------------------------------------
********** Iteration 17 ************
Optimizing Policy...
sampling
done in 0.647 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.121          0
         1     0.0272     0.0117
         2     0.0958      0.087
         3    0.00811      0.107
         4    0.00588      0.178
         5    0.00291      0.264
         6    0.00373      0.334
         7     0.0214      0.439
         8    0.00335      0.458
         9     0.0278      0.484
        10    0.00157      0.566
done in 0.016 seconds
Expected: 0.030 Actual: 0.026
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.81       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 122         |
| TimeElapsed             | 13.9        |
| TimestepsSoFar          | 18432       |
| entloss                 | 0.0         |
| entropy                 | 2.8034976   |
| explained_variance_t... | 0.0562      |
| meankl                  | 0.009571113 |
| optimgain               | 0.025860932 |
| surrgain                | 0.025860932 |
-----------------------------------------
********** Iteration 18 ************
Optimizing Policy...
sampling
done in 0.655 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.171          0
         1     0.0899     0.0205
         2     0.0452      0.138
         3     0.0223      0.148
         4     0.0188      0.288
         5     0.0132      0.527
         6    0.00855      0.719
         7     0.0109      0.959
         8     0.0653       1.01
         9     0.0038       1.12
        10     0.0026       1.27
done in 0.015 seconds
Expected: 0.052 Actual: 0.038
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.4       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 129         |
| TimeElapsed             | 14.6        |
| TimestepsSoFar          | 19456       |
| entloss                 | 0.0         |
| entropy                 | 2.775632    |
| explained_variance_t... | -0.181      |
| meankl                  | 0.009343585 |
| optimgain               | 0.038084634 |
| surrgain                | 0.038084634 |
-----------------------------------------
********** Iteration 19 ************
Optimizing Policy...
sampling
Eval num_timesteps=19456, episode_reward=-0.72 +/- 11.38
Episode length: 150.00 +/- 0.00
done in 1.098 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0518          0
         1     0.0723     0.0183
         2     0.0131      0.112
         3      0.025       0.12
         4    0.00423      0.165
         5    0.00226      0.199
         6    0.00357      0.261
         7    0.00436      0.405
         8    0.00917      0.516
         9    0.00614      0.532
        10    0.00462      0.631
done in 0.016 seconds
Expected: 0.031 Actual: 0.024
Stepsize OK!
vf
done in 0.022 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -11.5        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 136          |
| TimeElapsed             | 15.8         |
| TimestepsSoFar          | 20480        |
| entloss                 | 0.0          |
| entropy                 | 2.7720253    |
| explained_variance_t... | 0.0116       |
| meankl                  | 0.0069309967 |
| optimgain               | 0.024420485  |
| surrgain                | 0.024420485  |
------------------------------------------
********** Iteration 20 ************
Optimizing Policy...
sampling
done in 0.675 seconds
computegrad
done in 0.006 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0304          0
         1     0.0447      0.019
         2     0.0185     0.0873
         3     0.0128     0.0978
         4    0.00615      0.153
         5     0.0046      0.289
         6    0.00558      0.421
         7    0.00302      0.501
         8    0.00758      0.559
         9    0.00204      0.569
        10     0.0129      0.649
done in 0.023 seconds
Expected: 0.030 Actual: 0.029
Stepsize OK!
vf
done in 0.022 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.5        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 143          |
| TimeElapsed             | 16.5         |
| TimestepsSoFar          | 21504        |
| entloss                 | 0.0          |
| entropy                 | 2.7871506    |
| explained_variance_t... | 0.0482       |
| meankl                  | 0.0103119835 |
| optimgain               | 0.029408962  |
| surrgain                | 0.029408962  |
------------------------------------------
********** Iteration 21 ************
Optimizing Policy...
sampling
done in 0.644 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0565          0
         1     0.0786      0.016
         2     0.0126     0.0931
         3     0.0558      0.129
         4    0.00493      0.154
         5    0.00444      0.261
         6    0.00569      0.424
         7     0.0134      0.626
         8     0.0249      0.652
         9    0.00496      0.851
        10     0.0265      0.887
done in 0.018 seconds
Expected: 0.035 Actual: 0.030
Stepsize OK!
vf
done in 0.025 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 150         |
| TimeElapsed             | 17.2        |
| TimestepsSoFar          | 22528       |
| entloss                 | 0.0         |
| entropy                 | 2.7969668   |
| explained_variance_t... | -0.0676     |
| meankl                  | 0.009482002 |
| optimgain               | 0.030102763 |
| surrgain                | 0.030102763 |
-----------------------------------------
********** Iteration 22 ************
Optimizing Policy...
sampling
done in 0.741 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.11          0
         1      0.052     0.0136
         2     0.0419     0.0689
         3    0.00718     0.0798
         4    0.00552      0.136
         5    0.00553      0.265
         6    0.00579      0.387
         7    0.00567      0.496
         8    0.00308      0.502
         9    0.00804      0.607
        10    0.00575      0.622
done in 0.016 seconds
Expected: 0.031 Actual: 0.034
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 157         |
| TimeElapsed             | 18          |
| TimestepsSoFar          | 23552       |
| entloss                 | 0.0         |
| entropy                 | 2.7823093   |
| explained_variance_t... | 0.0879      |
| meankl                  | 0.011819439 |
| optimgain               | 0.03446175  |
| surrgain                | 0.03446175  |
-----------------------------------------
********** Iteration 23 ************
Optimizing Policy...
sampling
done in 0.651 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0688          0
         1     0.0233    0.00789
         2     0.0212       0.11
         3     0.0428      0.127
         4     0.0106      0.204
         5     0.0064      0.336
         6     0.0113      0.489
         7     0.0479      0.564
         8    0.00609      0.593
         9    0.00433      0.721
        10     0.0108       0.73
done in 0.015 seconds
Expected: 0.035 Actual: 0.033
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.5       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 163         |
| TimeElapsed             | 18.7        |
| TimestepsSoFar          | 24576       |
| entloss                 | 0.0         |
| entropy                 | 2.788083    |
| explained_variance_t... | 0.0877      |
| meankl                  | 0.009062642 |
| optimgain               | 0.03315091  |
| surrgain                | 0.03315091  |
-----------------------------------------
********** Iteration 24 ************
Optimizing Policy...
sampling
done in 0.650 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.177          0
         1     0.0297     0.0171
         2     0.0228     0.0927
         3     0.0686      0.175
         4     0.0151      0.217
         5     0.0105      0.396
         6     0.0104      0.513
         7    0.00392        0.6
         8     0.0193      0.617
         9    0.00376       0.66
        10    0.00292      0.739
done in 0.014 seconds
Expected: 0.039 Actual: 0.034
Stepsize OK!
vf
done in 0.025 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 170         |
| TimeElapsed             | 19.4        |
| TimestepsSoFar          | 25600       |
| entloss                 | 0.0         |
| entropy                 | 2.80663     |
| explained_variance_t... | 0.0539      |
| meankl                  | 0.010428723 |
| optimgain               | 0.03435973  |
| surrgain                | 0.03435973  |
-----------------------------------------
********** Iteration 25 ************
Optimizing Policy...
sampling
done in 0.667 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.105          0
         1     0.0537     0.0157
         2      0.107     0.0518
         3     0.0265      0.098
         4     0.0125      0.194
         5    0.00892      0.234
         6    0.00729      0.333
         7    0.00546      0.516
         8     0.0627       0.58
         9    0.00944      0.652
        10      0.011      0.669
done in 0.015 seconds
Expected: 0.036 Actual: 0.030
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 177         |
| TimeElapsed             | 20.1        |
| TimestepsSoFar          | 26624       |
| entloss                 | 0.0         |
| entropy                 | 2.815145    |
| explained_variance_t... | 0.13        |
| meankl                  | 0.007937133 |
| optimgain               | 0.029674098 |
| surrgain                | 0.029674098 |
-----------------------------------------
********** Iteration 26 ************
Optimizing Policy...
sampling
done in 0.661 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.153          0
         1     0.0516     0.0153
         2      0.131      0.051
         3     0.0188     0.0932
         4    0.00768      0.189
         5     0.0145      0.334
         6     0.0101      0.419
         7     0.0132      0.635
         8     0.0146      0.766
         9     0.0476      0.815
        10     0.0078      0.955
done in 0.015 seconds
Expected: 0.041 Actual: 0.054
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 184         |
| TimeElapsed             | 20.9        |
| TimestepsSoFar          | 27648       |
| entloss                 | 0.0         |
| entropy                 | 2.814658    |
| explained_variance_t... | 0.104       |
| meankl                  | 0.011235135 |
| optimgain               | 0.053636912 |
| surrgain                | 0.053636912 |
-----------------------------------------
********** Iteration 27 ************
Optimizing Policy...
sampling
done in 0.636 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.148          0
         1     0.0333      0.011
         2     0.0793     0.0196
         3      0.012     0.0709
         4    0.00897      0.123
         5    0.00485      0.177
         6    0.00486      0.254
         7     0.0681      0.336
         8    0.00839      0.368
         9     0.0394      0.399
        10    0.00523      0.596
done in 0.014 seconds
Expected: 0.030 Actual: 0.022
Stepsize OK!
vf
done in 0.025 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 191         |
| TimeElapsed             | 21.5        |
| TimestepsSoFar          | 28672       |
| entloss                 | 0.0         |
| entropy                 | 2.7871096   |
| explained_variance_t... | 0.101       |
| meankl                  | 0.008380958 |
| optimgain               | 0.02218981  |
| surrgain                | 0.02218981  |
-----------------------------------------
********** Iteration 28 ************
Optimizing Policy...
sampling
done in 0.672 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0568          0
         1     0.0642    0.00977
         2     0.0673      0.068
         3     0.0233     0.0932
         4      0.007      0.152
         5    0.00922      0.213
         6     0.0051      0.274
         7     0.0185       0.31
         8     0.0116       0.32
         9    0.00394      0.402
        10     0.0083      0.684
done in 0.014 seconds
Expected: 0.033 Actual: 0.032
violated KL constraint. shrinking step.
Expected: 0.033 Actual: 0.017
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.4        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 197          |
| TimeElapsed             | 22.3         |
| TimestepsSoFar          | 29696        |
| entloss                 | 0.0          |
| entropy                 | 2.7763562    |
| explained_variance_t... | 0.12         |
| meankl                  | 0.0036785875 |
| optimgain               | 0.017205857  |
| surrgain                | 0.017205857  |
------------------------------------------
********** Iteration 29 ************
Optimizing Policy...
sampling
Eval num_timesteps=29696, episode_reward=-6.09 +/- 10.44
Episode length: 150.00 +/- 0.00
done in 1.159 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.329          0
         1     0.0905    0.00915
         2      0.318     0.0621
         3     0.0138      0.135
         4     0.0119       0.22
         5     0.0131      0.261
         6    0.00964      0.325
         7      0.207      0.401
         8     0.0105      0.477
         9     0.0248      0.552
        10    0.00682      0.568
done in 0.015 seconds
Expected: 0.040 Actual: 0.009
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -11.8        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 204          |
| TimeElapsed             | 23.5         |
| TimestepsSoFar          | 30720        |
| entloss                 | 0.0          |
| entropy                 | 2.7785256    |
| explained_variance_t... | -0.177       |
| meankl                  | 0.0134179145 |
| optimgain               | 0.009188866  |
| surrgain                | 0.009188866  |
------------------------------------------
********** Iteration 30 ************
Optimizing Policy...
sampling
done in 0.618 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.145          0
         1      0.101      0.024
         2        0.3     0.0754
         3     0.0229      0.172
         4     0.0246      0.241
         5    0.00831       0.31
         6     0.0079      0.352
         7     0.0122      0.452
         8     0.0127      0.461
         9    0.00889      0.567
        10     0.0232      0.592
done in 0.013 seconds
Expected: 0.042 Actual: 0.036
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 211         |
| TimeElapsed             | 24.1        |
| TimestepsSoFar          | 31744       |
| entloss                 | 0.0         |
| entropy                 | 2.7608366   |
| explained_variance_t... | 0.0352      |
| meankl                  | 0.011784517 |
| optimgain               | 0.035522714 |
| surrgain                | 0.035522714 |
-----------------------------------------
********** Iteration 31 ************
Optimizing Policy...
sampling
done in 0.640 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0868          0
         1     0.0397    0.00949
         2      0.116     0.0958
         3     0.0155      0.134
         4      0.012      0.217
         5     0.0166      0.272
         6    0.00646      0.328
         7    0.00855      0.413
         8     0.0219      0.486
         9     0.0144      0.501
        10    0.00504      0.717
done in 0.016 seconds
Expected: 0.036 Actual: 0.034
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 218         |
| TimeElapsed             | 24.8        |
| TimestepsSoFar          | 32768       |
| entloss                 | 0.0         |
| entropy                 | 2.7657144   |
| explained_variance_t... | 0.0653      |
| meankl                  | 0.011327381 |
| optimgain               | 0.03377561  |
| surrgain                | 0.03377561  |
-----------------------------------------
********** Iteration 32 ************
Optimizing Policy...
sampling
done in 0.640 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0622          0
         1     0.0407     0.0089
         2     0.0235     0.0837
         3      0.021     0.0971
         4    0.00891      0.136
         5    0.00863      0.206
         6    0.00518      0.281
         7     0.0107      0.399
         8     0.0556      0.435
         9    0.00414       0.55
        10    0.00625      0.719
done in 0.015 seconds
Expected: 0.032 Actual: 0.028
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 225         |
| TimeElapsed             | 25.5        |
| TimestepsSoFar          | 33792       |
| entloss                 | 0.0         |
| entropy                 | 2.782565    |
| explained_variance_t... | 0.0048      |
| meankl                  | 0.007790867 |
| optimgain               | 0.027989611 |
| surrgain                | 0.027989611 |
-----------------------------------------
********** Iteration 33 ************
Optimizing Policy...
sampling
done in 0.641 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.125          0
         1     0.0446    0.00921
         2     0.0382     0.0153
         3     0.0113     0.0648
         4    0.00347        0.1
         5    0.00295      0.161
         6    0.00354      0.222
         7     0.0657      0.252
         8    0.00621       0.35
         9    0.00604      0.361
        10    0.00226       0.45
done in 0.014 seconds
Expected: 0.025 Actual: 0.024
Stepsize OK!
vf
done in 0.024 seconds
----------------------------------------
| EpLenMean               | 150        |
| EpRewMean               | -11.8      |
| EpThisIter              | 7          |
| EpisodesSoFar           | 232        |
| TimeElapsed             | 26.2       |
| TimestepsSoFar          | 34816      |
| entloss                 | 0.0        |
| entropy                 | 2.8005702  |
| explained_variance_t... | 0.0596     |
| meankl                  | 0.01067576 |
| optimgain               | 0.02360322 |
| surrgain                | 0.02360322 |
----------------------------------------
********** Iteration 34 ************
Optimizing Policy...
sampling
done in 0.647 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.206          0
         1     0.0847     0.0127
         2      0.134     0.0328
         3     0.0297       0.12
         4     0.0206      0.171
         5    0.00721      0.303
         6    0.00458      0.387
         7     0.0619      0.403
         8     0.0044      0.506
         9     0.0369       0.54
        10    0.00416      0.607
done in 0.016 seconds
Expected: 0.039 Actual: 0.029
violated KL constraint. shrinking step.
Expected: 0.039 Actual: 0.021
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.6       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 238         |
| TimeElapsed             | 26.9        |
| TimestepsSoFar          | 35840       |
| entloss                 | 0.0         |
| entropy                 | 2.809295    |
| explained_variance_t... | 0.0707      |
| meankl                  | 0.006191183 |
| optimgain               | 0.021393081 |
| surrgain                | 0.021393081 |
-----------------------------------------
********** Iteration 35 ************
Optimizing Policy...
sampling
done in 0.702 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.524          0
         1     0.0717     0.0165
         2     0.0122     0.0201
         3     0.0166     0.0809
         4    0.00868      0.119
         5    0.00397      0.182
         6    0.00286      0.263
         7    0.00754      0.267
         8    0.00282      0.318
         9     0.0064      0.325
        10    0.00128      0.448
done in 0.020 seconds
Expected: 0.029 Actual: 0.025
violated KL constraint. shrinking step.
Expected: 0.029 Actual: 0.015
Stepsize OK!
vf
done in 0.025 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -10.9        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 245          |
| TimeElapsed             | 27.7         |
| TimestepsSoFar          | 36864        |
| entloss                 | 0.0          |
| entropy                 | 2.8080142    |
| explained_variance_t... | 0.0974       |
| meankl                  | 0.0034973323 |
| optimgain               | 0.014635722  |
| surrgain                | 0.014635722  |
------------------------------------------
********** Iteration 36 ************
Optimizing Policy...
sampling
done in 0.663 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.183          0
         1     0.0563     0.0147
         2     0.0484     0.0227
         3     0.0197     0.0486
         4    0.00505     0.0865
         5    0.00759      0.234
         6    0.00478      0.404
         7     0.0685      0.438
         8    0.00295      0.528
         9    0.00948      0.633
        10    0.00882      0.649
done in 0.014 seconds
Expected: 0.031 Actual: 0.019
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -10.5        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 252          |
| TimeElapsed             | 28.4         |
| TimestepsSoFar          | 37888        |
| entloss                 | 0.0          |
| entropy                 | 2.7977684    |
| explained_variance_t... | -0.0394      |
| meankl                  | 0.0135182375 |
| optimgain               | 0.018836278  |
| surrgain                | 0.018836278  |
------------------------------------------
********** Iteration 37 ************
Optimizing Policy...
sampling
done in 0.634 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0903          0
         1     0.0791      0.024
         2     0.0583     0.0598
         3     0.0211     0.0773
         4    0.00796      0.139
         5     0.0097      0.223
         6    0.00635      0.317
         7     0.0139      0.494
         8     0.0042      0.689
         9       0.04      0.741
        10     0.0193      0.851
done in 0.016 seconds
Expected: 0.037 Actual: 0.024
Stepsize OK!
vf
done in 0.023 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.1        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 259          |
| TimeElapsed             | 29.1         |
| TimestepsSoFar          | 38912        |
| entloss                 | 0.0          |
| entropy                 | 2.798096     |
| explained_variance_t... | 0.197        |
| meankl                  | 0.0063823024 |
| optimgain               | 0.024077084  |
| surrgain                | 0.024077084  |
------------------------------------------
********** Iteration 38 ************
Optimizing Policy...
sampling
done in 0.652 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.116          0
         1     0.0542      0.017
         2      0.175     0.0448
         3     0.0288        0.2
         4     0.0398      0.287
         5     0.0171      0.419
         6    0.00827      0.491
         7    0.00443      0.616
         8     0.0331      0.657
         9    0.00728      0.673
        10     0.0349      0.753
done in 0.016 seconds
Expected: 0.044 Actual: 0.020
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 266         |
| TimeElapsed             | 29.8        |
| TimestepsSoFar          | 39936       |
| entloss                 | 0.0         |
| entropy                 | 2.8026145   |
| explained_variance_t... | -0.23       |
| meankl                  | 0.010275454 |
| optimgain               | 0.019777538 |
| surrgain                | 0.019777538 |
-----------------------------------------
********** Iteration 39 ************
Optimizing Policy...
sampling
Eval num_timesteps=39936, episode_reward=-2.75 +/- 9.80
Episode length: 150.00 +/- 0.00
done in 1.131 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.18          0
         1     0.0442      0.015
         2     0.0145     0.0709
         3     0.0395      0.118
         4     0.0222      0.147
         5      0.011      0.282
         6    0.00361      0.359
         7    0.00736      0.422
         8    0.00924       0.43
         9    0.00254        0.5
        10    0.00241       0.55
done in 0.015 seconds
Expected: 0.034 Actual: 0.022
Stepsize OK!
vf
done in 0.026 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 273         |
| TimeElapsed             | 31          |
| TimestepsSoFar          | 40960       |
| entloss                 | 0.0         |
| entropy                 | 2.817045    |
| explained_variance_t... | 0.376       |
| meankl                  | 0.010346245 |
| optimgain               | 0.022063378 |
| surrgain                | 0.022063378 |
-----------------------------------------
********** Iteration 40 ************
Optimizing Policy...
sampling
done in 0.661 seconds
computegrad
done in 0.006 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0973          0
         1     0.0725     0.0252
         2     0.0218     0.0704
         3      0.021     0.0823
         4    0.00726      0.113
         5     0.0081      0.179
         6     0.0064      0.246
         7    0.00169      0.298
         8    0.00116      0.348
         9     0.0253      0.381
        10    0.00181      0.543
done in 0.019 seconds
Expected: 0.030 Actual: 0.028
Stepsize OK!
vf
done in 0.023 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13.7        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 279          |
| TimeElapsed             | 31.7         |
| TimestepsSoFar          | 41984        |
| entloss                 | 0.0          |
| entropy                 | 2.8184536    |
| explained_variance_t... | 0.0708       |
| meankl                  | 0.0074625392 |
| optimgain               | 0.027599774  |
| surrgain                | 0.027599774  |
------------------------------------------
********** Iteration 41 ************
Optimizing Policy...
sampling
done in 0.729 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0294          0
         1     0.0251    0.00773
         2     0.0251     0.0863
         3     0.0198      0.101
         4     0.0114      0.156
         5      0.015       0.41
         6     0.0128      0.623
         7    0.00716      0.818
         8       0.08      0.872
         9    0.00979      0.993
        10     0.0347       1.09
done in 0.015 seconds
Expected: 0.038 Actual: 0.026
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 286         |
| TimeElapsed             | 32.5        |
| TimestepsSoFar          | 43008       |
| entloss                 | 0.0         |
| entropy                 | 2.824857    |
| explained_variance_t... | 0.0465      |
| meankl                  | 0.010832166 |
| optimgain               | 0.026318958 |
| surrgain                | 0.026318958 |
-----------------------------------------
********** Iteration 42 ************
Optimizing Policy...
sampling
done in 0.675 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.492          0
         1     0.0373     0.0234
         2      0.106     0.0466
         3      0.011     0.0946
         4    0.00486      0.135
         5    0.00647      0.218
         6      0.011      0.346
         7    0.00745      0.629
         8    0.00568      0.637
         9     0.0221      0.755
        10    0.00441      0.781
done in 0.014 seconds
Expected: 0.037 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -15.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 293         |
| TimeElapsed             | 33.2        |
| TimestepsSoFar          | 44032       |
| entloss                 | 0.0         |
| entropy                 | 2.7892048   |
| explained_variance_t... | 0.0239      |
| meankl                  | 0.011838192 |
| optimgain               | 0.027315188 |
| surrgain                | 0.027315188 |
-----------------------------------------
********** Iteration 43 ************
Optimizing Policy...
sampling
done in 0.664 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0259          0
         1     0.0219     0.0551
         2     0.0198     0.0633
         3     0.0102      0.113
         4    0.00614      0.119
         5    0.00441      0.168
         6     0.0052      0.241
         7    0.00375      0.522
         8    0.00658      0.589
         9    0.00631      0.599
        10    0.00298      0.691
done in 0.015 seconds
Expected: 0.028 Actual: 0.020
violated KL constraint. shrinking step.
Expected: 0.028 Actual: 0.012
Stepsize OK!
vf
done in 0.023 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -13.2        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 300          |
| TimeElapsed             | 33.9         |
| TimestepsSoFar          | 45056        |
| entloss                 | 0.0          |
| entropy                 | 2.7762344    |
| explained_variance_t... | 0.041        |
| meankl                  | 0.0025384591 |
| optimgain               | 0.012171253  |
| surrgain                | 0.012171253  |
------------------------------------------
********** Iteration 44 ************
Optimizing Policy...
sampling
done in 0.718 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.199          0
         1     0.0712     0.0171
         2      0.075     0.0591
         3     0.0396     0.0832
         4    0.00594      0.138
         5    0.00726      0.206
         6     0.0025      0.235
         7    0.00299       0.29
         8     0.0132      0.368
         9    0.00407      0.381
        10     0.0346       0.48
done in 0.015 seconds
Expected: 0.032 Actual: 0.034
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 307         |
| TimeElapsed             | 34.7        |
| TimestepsSoFar          | 46080       |
| entloss                 | 0.0         |
| entropy                 | 2.8135478   |
| explained_variance_t... | 0.114       |
| meankl                  | 0.009782154 |
| optimgain               | 0.03354071  |
| surrgain                | 0.03354071  |
-----------------------------------------
********** Iteration 45 ************
Optimizing Policy...
sampling
done in 0.650 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.164          0
         1      0.104     0.0132
         2      0.187     0.0347
         3     0.0143     0.0981
         4     0.0193      0.192
         5     0.0143       0.26
         6     0.0051      0.369
         7      0.109      0.395
         8     0.0086      0.539
         9     0.0403      0.639
        10    0.00507      0.668
done in 0.013 seconds
Expected: 0.039 Actual: 0.031
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 314         |
| TimeElapsed             | 35.4        |
| TimestepsSoFar          | 47104       |
| entloss                 | 0.0         |
| entropy                 | 2.7759397   |
| explained_variance_t... | 0.0896      |
| meankl                  | 0.011242645 |
| optimgain               | 0.030744012 |
| surrgain                | 0.030744012 |
-----------------------------------------
********** Iteration 46 ************
Optimizing Policy...
sampling
done in 0.651 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0917          0
         1     0.0737    0.00985
         2     0.0195      0.128
         3     0.0465      0.144
         4      0.014      0.171
         5    0.00686      0.236
         6    0.00907      0.339
         7     0.0174      0.502
         8    0.00698       0.51
         9    0.00423      0.624
        10    0.00446      0.814
done in 0.014 seconds
Expected: 0.038 Actual: 0.031
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.8       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 320         |
| TimeElapsed             | 36.1        |
| TimestepsSoFar          | 48128       |
| entloss                 | 0.0         |
| entropy                 | 2.7638447   |
| explained_variance_t... | 0.0637      |
| meankl                  | 0.011103401 |
| optimgain               | 0.03134563  |
| surrgain                | 0.03134563  |
-----------------------------------------
********** Iteration 47 ************
Optimizing Policy...
sampling
done in 0.662 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0815          0
         1     0.0906     0.0143
         2      0.121      0.059
         3     0.0291     0.0955
         4    0.00802      0.138
         5    0.00762      0.208
         6    0.00294      0.265
         7     0.0353      0.413
         8    0.00436      0.431
         9    0.00939      0.493
        10    0.00672      0.508
done in 0.015 seconds
Expected: 0.032 Actual: 0.023
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.2       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 327         |
| TimeElapsed             | 36.8        |
| TimestepsSoFar          | 49152       |
| entloss                 | 0.0         |
| entropy                 | 2.720032    |
| explained_variance_t... | 0.13        |
| meankl                  | 0.013271208 |
| optimgain               | 0.022658354 |
| surrgain                | 0.022658354 |
-----------------------------------------
********** Iteration 48 ************
Optimizing Policy...
sampling
Eval num_timesteps=49152, episode_reward=4.47 +/- 5.08
Episode length: 150.00 +/- 0.00
done in 1.076 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.415          0
         1     0.0363     0.0125
         2       0.03       0.12
         3     0.0818      0.146
         4     0.0258      0.208
         5      0.011      0.321
         6     0.0115      0.463
         7     0.0477      0.479
         8    0.00371      0.532
         9    0.00717      0.715
        10     0.0399      0.762
done in 0.015 seconds
Expected: 0.042 Actual: 0.037
Stepsize OK!
vf
done in 0.020 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -11.3        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 334          |
| TimeElapsed             | 37.9         |
| TimestepsSoFar          | 50176        |
| entloss                 | 0.0          |
| entropy                 | 2.717154     |
| explained_variance_t... | 0.0655       |
| meankl                  | 0.0084423255 |
| optimgain               | 0.03705344   |
| surrgain                | 0.03705344   |
------------------------------------------
********** Iteration 49 ************
Optimizing Policy...
sampling
done in 0.605 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.153          0
         1     0.0405    0.00572
         2     0.0848     0.0323
         3     0.0584     0.0626
         4     0.0162       0.16
         5    0.00942      0.352
         6      0.045      0.399
         7    0.00542      0.406
         8    0.00525      0.542
         9     0.0179      0.643
        10    0.00622      0.655
done in 0.013 seconds
Expected: 0.037 Actual: 0.033
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 341         |
| TimeElapsed             | 38.5        |
| TimestepsSoFar          | 51200       |
| entloss                 | 0.0         |
| entropy                 | 2.7015374   |
| explained_variance_t... | -0.135      |
| meankl                  | 0.010899576 |
| optimgain               | 0.03307573  |
| surrgain                | 0.03307573  |
-----------------------------------------
********** Iteration 50 ************
Optimizing Policy...
sampling
done in 0.679 seconds
computegrad
done in 0.007 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.151          0
         1     0.0499    0.00674
         2     0.0733      0.016
         3     0.0454      0.089
         4     0.0102      0.164
         5    0.00637       0.25
         6    0.00687      0.311
         7      0.139      0.359
         8    0.00316       0.41
         9     0.0264      0.427
        10    0.00339       0.46
done in 0.016 seconds
Expected: 0.032 Actual: 0.020
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 348         |
| TimeElapsed             | 39.3        |
| TimestepsSoFar          | 52224       |
| entloss                 | 0.0         |
| entropy                 | 2.7320883   |
| explained_variance_t... | 0.107       |
| meankl                  | 0.010215571 |
| optimgain               | 0.020413741 |
| surrgain                | 0.020413741 |
-----------------------------------------
********** Iteration 51 ************
Optimizing Policy...
sampling
done in 0.697 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.194          0
         1     0.0701     0.0104
         2     0.0999     0.0291
         3     0.0478      0.054
         4     0.0221      0.105
         5    0.00795      0.218
         6    0.00992      0.339
         7      0.076      0.511
         8     0.0108      0.534
         9     0.0158      0.651
        10    0.00865      0.661
done in 0.014 seconds
Expected: 0.037 Actual: 0.016
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.7       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 354         |
| TimeElapsed             | 40          |
| TimestepsSoFar          | 53248       |
| entloss                 | 0.0         |
| entropy                 | 2.7479272   |
| explained_variance_t... | -0.184      |
| meankl                  | 0.009525398 |
| optimgain               | 0.01643766  |
| surrgain                | 0.01643766  |
-----------------------------------------
********** Iteration 52 ************
Optimizing Policy...
sampling
done in 0.658 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.217          0
         1     0.0239     0.0104
         2     0.0624     0.0226
         3     0.0112     0.0665
         4     0.0223      0.121
         5    0.00946      0.183
         6     0.0119      0.368
         7     0.0455      0.564
         8      0.017      0.587
         9    0.00387      0.781
        10     0.0174      0.792
done in 0.015 seconds
Expected: 0.034 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 361         |
| TimeElapsed             | 40.7        |
| TimestepsSoFar          | 54272       |
| entloss                 | 0.0         |
| entropy                 | 2.7679338   |
| explained_variance_t... | 0.00749     |
| meankl                  | 0.008639349 |
| optimgain               | 0.026713159 |
| surrgain                | 0.026713159 |
-----------------------------------------
********** Iteration 53 ************
Optimizing Policy...
sampling
done in 0.622 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.297          0
         1     0.0513     0.0118
         2      0.034     0.0775
         3      0.181      0.106
         4     0.0187      0.137
         5     0.0157      0.217
         6     0.0141       0.33
         7     0.0205      0.418
         8     0.0322      0.432
         9    0.00963      0.593
        10    0.00603      0.596
done in 0.015 seconds
Expected: 0.038 Actual: 0.028
Stepsize OK!
vf
done in 0.018 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -12.8        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 368          |
| TimeElapsed             | 41.4         |
| TimestepsSoFar          | 55296        |
| entloss                 | 0.0          |
| entropy                 | 2.7509458    |
| explained_variance_t... | 0.118        |
| meankl                  | 0.0108326115 |
| optimgain               | 0.028285325  |
| surrgain                | 0.028285325  |
------------------------------------------
********** Iteration 54 ************
Optimizing Policy...
sampling
done in 0.638 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.233          0
         1      0.106    0.00989
         2      0.413      0.145
         3     0.0538       0.19
         4     0.0128      0.264
         5    0.00885      0.323
         6     0.0122      0.453
         7     0.0473      0.464
         8    0.00993      0.589
         9    0.00757      0.594
        10    0.00491      0.781
done in 0.015 seconds
Expected: 0.048 Actual: 0.043
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 375         |
| TimeElapsed             | 42.1        |
| TimestepsSoFar          | 56320       |
| entloss                 | 0.0         |
| entropy                 | 2.7725437   |
| explained_variance_t... | 0.103       |
| meankl                  | 0.011322342 |
| optimgain               | 0.04334505  |
| surrgain                | 0.04334505  |
-----------------------------------------
********** Iteration 55 ************
Optimizing Policy...
sampling
done in 0.647 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.258          0
         1      0.239     0.0136
         2     0.0213     0.0468
         3      0.115     0.0595
         4    0.00891      0.144
         5    0.00764      0.253
         6    0.00559      0.317
         7     0.0764       0.35
         8    0.00301      0.377
         9    0.00554      0.435
        10      0.014      0.444
done in 0.014 seconds
Expected: 0.034 Actual: 0.035
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 382         |
| TimeElapsed             | 42.8        |
| TimestepsSoFar          | 57344       |
| entloss                 | 0.0         |
| entropy                 | 2.802346    |
| explained_variance_t... | 0.0407      |
| meankl                  | 0.009488223 |
| optimgain               | 0.035071682 |
| surrgain                | 0.035071682 |
-----------------------------------------
********** Iteration 56 ************
Optimizing Policy...
sampling
done in 0.728 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0806          0
         1     0.0384    0.00779
         2      0.088     0.0298
         3    0.00522     0.0589
         4    0.00667      0.124
         5     0.0102      0.165
         6    0.00598      0.256
         7     0.0066      0.412
         8     0.0561      0.451
         9    0.00995      0.516
        10    0.00469      0.525
done in 0.016 seconds
Expected: 0.027 Actual: 0.010
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 389         |
| TimeElapsed             | 43.6        |
| TimestepsSoFar          | 58368       |
| entloss                 | 0.0         |
| entropy                 | 2.8009236   |
| explained_variance_t... | 0.00803     |
| meankl                  | 0.014145592 |
| optimgain               | 0.010011559 |
| surrgain                | 0.010011559 |
-----------------------------------------
********** Iteration 57 ************
Optimizing Policy...
sampling
done in 0.637 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.13          0
         1     0.0579     0.0112
         2      0.104     0.0279
         3     0.0516     0.0567
         4    0.00573      0.116
         5     0.0104      0.179
         6     0.0088      0.316
         7     0.0128      0.642
         8     0.0138      0.652
         9     0.0725      0.701
        10    0.00417      0.806
done in 0.016 seconds
Expected: 0.036 Actual: 0.006
violated KL constraint. shrinking step.
Expected: 0.036 Actual: 0.015
Stepsize OK!
vf
done in 0.022 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -14.1        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 395          |
| TimeElapsed             | 44.2         |
| TimestepsSoFar          | 59392        |
| entloss                 | 0.0          |
| entropy                 | 2.7822573    |
| explained_variance_t... | -0.0233      |
| meankl                  | 0.0068432325 |
| optimgain               | 0.015041195  |
| surrgain                | 0.015041195  |
------------------------------------------
********** Iteration 58 ************
Optimizing Policy...
sampling
Eval num_timesteps=59392, episode_reward=2.32 +/- 13.42
Episode length: 150.00 +/- 0.00
done in 1.172 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0826          0
         1     0.0405    0.00931
         2      0.147     0.0339
         3     0.0209     0.0541
         4    0.00512     0.0941
         5    0.00725      0.152
         6    0.00401      0.265
         7      0.103      0.297
         8    0.00807      0.409
         9     0.0357      0.434
        10    0.00355      0.574
done in 0.015 seconds
Expected: 0.028 Actual: 0.022
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 402         |
| TimeElapsed             | 45.5        |
| TimestepsSoFar          | 60416       |
| entloss                 | 0.0         |
| entropy                 | 2.750224    |
| explained_variance_t... | -0.0151     |
| meankl                  | 0.008118274 |
| optimgain               | 0.02204401  |
| surrgain                | 0.02204401  |
-----------------------------------------
********** Iteration 59 ************
Optimizing Policy...
sampling
done in 0.637 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.301          0
         1     0.0695     0.0121
         2      0.116     0.0208
         3     0.0355      0.111
         4     0.0314      0.186
         5     0.0163      0.326
         6     0.0116      0.482
         7      0.222       0.53
         8     0.0121      0.646
         9      0.126      0.725
        10    0.00665      0.808
done in 0.016 seconds
Expected: 0.045 Actual: 0.043
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14         |
| EpThisIter              | 7           |
| EpisodesSoFar           | 409         |
| TimeElapsed             | 46.2        |
| TimestepsSoFar          | 61440       |
| entloss                 | 0.0         |
| entropy                 | 2.726046    |
| explained_variance_t... | 0.0584      |
| meankl                  | 0.012411704 |
| optimgain               | 0.042515926 |
| surrgain                | 0.042515926 |
-----------------------------------------
********** Iteration 60 ************
Optimizing Policy...
sampling
done in 0.668 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0987          0
         1     0.0319    0.00657
         2     0.0752     0.0179
         3     0.0166     0.0706
         4     0.0139      0.114
         5     0.0129      0.196
         6    0.00776      0.443
         7      0.041      0.587
         8     0.0114      0.603
         9     0.0257      0.614
        10     0.0144      0.826
done in 0.015 seconds
Expected: 0.035 Actual: 0.036
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 416         |
| TimeElapsed             | 46.9        |
| TimestepsSoFar          | 62464       |
| entloss                 | 0.0         |
| entropy                 | 2.695263    |
| explained_variance_t... | -0.00993    |
| meankl                  | 0.012301387 |
| optimgain               | 0.035638228 |
| surrgain                | 0.035638228 |
-----------------------------------------
********** Iteration 61 ************
Optimizing Policy...
sampling
done in 0.638 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0477          0
         1     0.0366     0.0122
         2     0.0665     0.0365
         3    0.00993     0.0516
         4     0.0039     0.0825
         5    0.00692      0.134
         6    0.00482      0.329
         7    0.00697      0.387
         8     0.0108      0.395
         9    0.00262      0.444
        10    0.00354      0.449
done in 0.014 seconds
Expected: 0.024 Actual: 0.023
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.7       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 423         |
| TimeElapsed             | 47.6        |
| TimestepsSoFar          | 63488       |
| entloss                 | 0.0         |
| entropy                 | 2.6900656   |
| explained_variance_t... | 0.167       |
| meankl                  | 0.009635546 |
| optimgain               | 0.023431398 |
| surrgain                | 0.023431398 |
-----------------------------------------
********** Iteration 62 ************
Optimizing Policy...
sampling
done in 0.662 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.273          0
         1      0.169     0.0141
         2      0.393     0.0371
         3     0.0409      0.129
         4     0.0645       0.16
         5    0.00845      0.207
         6     0.0053      0.256
         7     0.0105       0.31
         8      0.017      0.314
         9      0.106      0.483
        10    0.00446      0.541
done in 0.014 seconds
Expected: 0.041 Actual: 0.037
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 430         |
| TimeElapsed             | 48.3        |
| TimestepsSoFar          | 64512       |
| entloss                 | 0.0         |
| entropy                 | 2.6643786   |
| explained_variance_t... | -0.103      |
| meankl                  | 0.009794876 |
| optimgain               | 0.037081845 |
| surrgain                | 0.037081845 |
-----------------------------------------
********** Iteration 63 ************
Optimizing Policy...
sampling
done in 0.683 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.433          0
         1      0.147    0.00906
         2      0.447     0.0409
         3     0.0762      0.235
         4      0.112      0.286
         5      0.036      0.355
         6     0.0399      0.428
         7      0.255      0.498
         8     0.0181      0.522
         9     0.0308      0.663
        10     0.0319      0.675
done in 0.016 seconds
Expected: 0.055 Actual: 0.013
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -14.4       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 436         |
| TimeElapsed             | 49          |
| TimestepsSoFar          | 65536       |
| entloss                 | 0.0         |
| entropy                 | 2.6599007   |
| explained_variance_t... | -0.0792     |
| meankl                  | 0.012003603 |
| optimgain               | 0.01332835  |
| surrgain                | 0.01332835  |
-----------------------------------------
********** Iteration 64 ************
Optimizing Policy...
sampling
done in 0.643 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.25          0
         1     0.0524      0.012
         2     0.0613     0.0169
         3      0.017     0.0357
         4    0.00545     0.0516
         5    0.00828      0.106
         6    0.00401      0.157
         7     0.0126      0.252
         8    0.00508      0.256
         9    0.00382      0.479
        10     0.0151      0.493
done in 0.015 seconds
Expected: 0.026 Actual: 0.025
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 443         |
| TimeElapsed             | 49.7        |
| TimestepsSoFar          | 66560       |
| entloss                 | 0.0         |
| entropy                 | 2.6411135   |
| explained_variance_t... | 0.0876      |
| meankl                  | 0.012991228 |
| optimgain               | 0.025104348 |
| surrgain                | 0.025104348 |
-----------------------------------------
********** Iteration 65 ************
Optimizing Policy...
sampling
done in 0.629 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.133          0
         1     0.0429    0.00968
         2      0.204     0.0372
         3     0.0466     0.0696
         4     0.0181      0.138
         5     0.0145      0.219
         6     0.0085      0.313
         7     0.0619      0.418
         8    0.00868      0.432
         9      0.102      0.504
        10    0.00704      0.572
done in 0.016 seconds
Expected: 0.035 Actual: 0.033
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -11.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 450         |
| TimeElapsed             | 50.4        |
| TimestepsSoFar          | 67584       |
| entloss                 | 0.0         |
| entropy                 | 2.6542351   |
| explained_variance_t... | 0.156       |
| meankl                  | 0.009959444 |
| optimgain               | 0.033297807 |
| surrgain                | 0.033297807 |
-----------------------------------------
********** Iteration 66 ************
Optimizing Policy...
sampling
done in 0.645 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.184          0
         1     0.0429     0.0075
         2      0.246      0.069
         3     0.0164      0.129
         4     0.0102      0.182
         5    0.00373      0.259
         6     0.0204      0.337
         7    0.00511      0.343
         8       0.02      0.418
         9    0.00335       0.43
        10    0.00869      0.614
done in 0.015 seconds
Expected: 0.035 Actual: 0.036
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.83       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 457         |
| TimeElapsed             | 51.1        |
| TimestepsSoFar          | 68608       |
| entloss                 | 0.0         |
| entropy                 | 2.676553    |
| explained_variance_t... | 0.00828     |
| meankl                  | 0.011475669 |
| optimgain               | 0.03604446  |
| surrgain                | 0.03604446  |
-----------------------------------------
********** Iteration 67 ************
Optimizing Policy...
sampling
done in 0.679 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0958          0
         1     0.0527    0.00798
         2      0.195     0.0348
         3       0.02      0.106
         4     0.0156      0.156
         5      0.017      0.282
         6    0.00575      0.345
         7    0.00576      0.402
         8     0.0943      0.455
         9     0.0236      0.532
        10    0.00808      0.541
done in 0.014 seconds
Expected: 0.034 Actual: 0.016
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.92       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 464         |
| TimeElapsed             | 51.8        |
| TimestepsSoFar          | 69632       |
| entloss                 | 0.0         |
| entropy                 | 2.6514304   |
| explained_variance_t... | 0.0866      |
| meankl                  | 0.014772175 |
| optimgain               | 0.015525712 |
| surrgain                | 0.015525712 |
-----------------------------------------
********** Iteration 68 ************
Optimizing Policy...
sampling
Eval num_timesteps=69632, episode_reward=9.68 +/- 2.90
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.131 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.121          0
         1     0.0252    0.00507
         2     0.0632     0.0137
         3     0.0101     0.0647
         4    0.00792      0.142
         5    0.00591      0.229
         6    0.00959      0.283
         7    0.00514      0.286
         8    0.00311      0.389
         9     0.0349      0.411
        10    0.00186      0.463
done in 0.016 seconds
Expected: 0.026 Actual: 0.024
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -6.16       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 471         |
| TimeElapsed             | 53          |
| TimestepsSoFar          | 70656       |
| entloss                 | 0.0         |
| entropy                 | 2.6736138   |
| explained_variance_t... | -0.035      |
| meankl                  | 0.012669951 |
| optimgain               | 0.024048183 |
| surrgain                | 0.024048183 |
-----------------------------------------
********** Iteration 69 ************
Optimizing Policy...
sampling
done in 0.692 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0361          0
         1      0.137     0.0285
         2     0.0841     0.0789
         3     0.0598     0.0953
         4     0.0108      0.152
         5     0.0101      0.223
         6     0.0036      0.271
         7    0.00313      0.369
         8     0.0276      0.379
         9    0.00372      0.439
        10     0.0184      0.451
done in 0.015 seconds
Expected: 0.031 Actual: 0.022
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.38       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 477         |
| TimeElapsed             | 53.7        |
| TimestepsSoFar          | 71680       |
| entloss                 | 0.0         |
| entropy                 | 2.6525688   |
| explained_variance_t... | 0.00852     |
| meankl                  | 0.01010288  |
| optimgain               | 0.022445604 |
| surrgain                | 0.022445604 |
-----------------------------------------
********** Iteration 70 ************
Optimizing Policy...
sampling
done in 0.659 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.023          0
         1     0.0208    0.00743
         2      0.081     0.0385
         3    0.00578     0.0686
         4    0.00494      0.107
         5    0.00511      0.149
         6     0.0035      0.215
         7    0.00487      0.419
         8      0.025      0.436
         9     0.0366      0.613
        10      0.011      0.661
done in 0.014 seconds
Expected: 0.025 Actual: 0.027
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.07       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 484         |
| TimeElapsed             | 54.4        |
| TimestepsSoFar          | 72704       |
| entloss                 | 0.0         |
| entropy                 | 2.6351957   |
| explained_variance_t... | 0.0957      |
| meankl                  | 0.011360139 |
| optimgain               | 0.026502464 |
| surrgain                | 0.026502464 |
-----------------------------------------
********** Iteration 71 ************
Optimizing Policy...
sampling
done in 0.637 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0974          0
         1     0.0347    0.00921
         2       0.12      0.026
         3     0.0316      0.049
         4     0.0135     0.0914
         5    0.00986      0.131
         6    0.00427      0.244
         7    0.00826      0.308
         8    0.00817      0.311
         9     0.0958      0.429
        10    0.00644       0.51
done in 0.015 seconds
Expected: 0.029 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -5.87       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 491         |
| TimeElapsed             | 55.1        |
| TimestepsSoFar          | 73728       |
| entloss                 | 0.0         |
| entropy                 | 2.6387846   |
| explained_variance_t... | 0.0935      |
| meankl                  | 0.010696201 |
| optimgain               | 0.027294107 |
| surrgain                | 0.027294107 |
-----------------------------------------
********** Iteration 72 ************
Optimizing Policy...
sampling
done in 0.628 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.178          0
         1      0.172     0.0125
         2      0.394     0.0635
         3      0.065       0.15
         4     0.0226      0.182
         5     0.0299      0.277
         6     0.0176      0.422
         7     0.0558      0.507
         8     0.0576      0.523
         9     0.0488      0.804
        10      0.365       1.07
done in 0.013 seconds
Expected: 0.053 Actual: 0.044
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.37       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 498         |
| TimeElapsed             | 55.8        |
| TimestepsSoFar          | 74752       |
| entloss                 | 0.0         |
| entropy                 | 2.641887    |
| explained_variance_t... | 0.0296      |
| meankl                  | 0.011037737 |
| optimgain               | 0.044299796 |
| surrgain                | 0.044299796 |
-----------------------------------------
********** Iteration 73 ************
Optimizing Policy...
sampling
done in 0.596 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0714          0
         1      0.141     0.0126
         2      0.085       0.04
         3     0.0742      0.064
         4     0.0236      0.109
         5     0.0219       0.19
         6     0.0124      0.285
         7     0.0176      0.355
         8     0.0655      0.424
         9     0.0121      0.439
        10     0.0111      0.688
done in 0.013 seconds
Expected: 0.038 Actual: 0.033
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.38       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 505         |
| TimeElapsed             | 56.4        |
| TimestepsSoFar          | 75776       |
| entloss                 | 0.0         |
| entropy                 | 2.6241732   |
| explained_variance_t... | 0.132       |
| meankl                  | 0.009093195 |
| optimgain               | 0.033203203 |
| surrgain                | 0.033203203 |
-----------------------------------------
********** Iteration 74 ************
Optimizing Policy...
sampling
done in 0.602 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.327          0
         1      0.102    0.00845
         2     0.0673     0.0174
         3     0.0118      0.043
         4      0.021     0.0812
         5    0.00798      0.168
         6     0.0141      0.323
         7       0.18      0.412
         8     0.0174       0.46
         9     0.0262      0.756
        10     0.0127      0.774
done in 0.013 seconds
Expected: 0.035 Actual: 0.037
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.61       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 512         |
| TimeElapsed             | 57.1        |
| TimestepsSoFar          | 76800       |
| entloss                 | 0.0         |
| entropy                 | 2.6055932   |
| explained_variance_t... | 0.114       |
| meankl                  | 0.011622593 |
| optimgain               | 0.037208706 |
| surrgain                | 0.037208706 |
-----------------------------------------
********** Iteration 75 ************
Optimizing Policy...
sampling
done in 0.601 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0826          0
         1     0.0951     0.0107
         2      0.104     0.0284
         3     0.0397     0.0725
         4     0.0214      0.156
         5     0.0189       0.27
         6     0.0223      0.325
         7     0.0294      0.453
         8     0.0143      0.459
         9     0.0129      0.657
        10     0.0298      0.735
done in 0.013 seconds
Expected: 0.039 Actual: 0.045
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.35       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 518         |
| TimeElapsed             | 57.7        |
| TimestepsSoFar          | 77824       |
| entloss                 | 0.0         |
| entropy                 | 2.618702    |
| explained_variance_t... | -0.0886     |
| meankl                  | 0.009753678 |
| optimgain               | 0.045402687 |
| surrgain                | 0.045402687 |
-----------------------------------------
********** Iteration 76 ************
Optimizing Policy...
sampling
done in 0.585 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.349          0
         1      0.104     0.0126
         2     0.0219     0.0159
         3     0.0208     0.0586
         4     0.0173     0.0906
         5     0.0115      0.129
         6     0.0117      0.328
         7     0.0189      0.443
         8      0.043      0.453
         9    0.00877      0.577
        10     0.0518      0.647
done in 0.013 seconds
Expected: 0.033 Actual: 0.031
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -10.7        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 525          |
| TimeElapsed             | 58.4         |
| TimestepsSoFar          | 78848        |
| entloss                 | 0.0          |
| entropy                 | 2.614627     |
| explained_variance_t... | 0.123        |
| meankl                  | 0.0098962765 |
| optimgain               | 0.031240951  |
| surrgain                | 0.031240951  |
------------------------------------------
********** Iteration 77 ************
Optimizing Policy...
sampling
done in 0.588 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.12          0
         1     0.0794     0.0074
         2     0.0625     0.0244
         3     0.0574     0.0486
         4     0.0102     0.0959
         5    0.00601      0.117
         6     0.0101      0.188
         7     0.0108       0.26
         8     0.0052      0.263
         9    0.00795      0.368
        10     0.0582       0.47
done in 0.013 seconds
Expected: 0.028 Actual: 0.028
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.99       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 532         |
| TimeElapsed             | 59          |
| TimestepsSoFar          | 79872       |
| entloss                 | 0.0         |
| entropy                 | 2.6052132   |
| explained_variance_t... | 0.0798      |
| meankl                  | 0.009024931 |
| optimgain               | 0.027874183 |
| surrgain                | 0.027874183 |
-----------------------------------------
********** Iteration 78 ************
Optimizing Policy...
sampling
Eval num_timesteps=79872, episode_reward=-10.91 +/- 14.48
Episode length: 150.00 +/- 0.00
done in 1.013 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.132          0
         1     0.0739     0.0101
         2      0.414     0.0364
         3     0.0163      0.101
         4     0.0178      0.122
         5     0.0131      0.192
         6     0.0134       0.27
         7      0.203      0.489
         8     0.0217      0.528
         9     0.0659      0.558
        10    0.00652      0.661
done in 0.013 seconds
Expected: 0.037 Actual: 0.036
Stepsize OK!
vf
done in 0.018 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.6        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 539         |
| TimeElapsed             | 60          |
| TimestepsSoFar          | 80896       |
| entloss                 | 0.0         |
| entropy                 | 2.6022336   |
| explained_variance_t... | 0.152       |
| meankl                  | 0.01080992  |
| optimgain               | 0.035776906 |
| surrgain                | 0.035776906 |
-----------------------------------------
********** Iteration 79 ************
Optimizing Policy...
sampling
done in 0.586 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.643          0
         1      0.111    0.00974
         2      0.244     0.0257
         3     0.0218      0.106
         4    0.00628      0.142
         5     0.0207      0.185
         6     0.0434      0.257
         7       0.21        0.3
         8    0.00861      0.449
         9     0.0629      0.586
        10     0.0112      0.612
done in 0.013 seconds
Expected: 0.039 Actual: 0.037
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.29       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 546         |
| TimeElapsed             | 60.7        |
| TimestepsSoFar          | 81920       |
| entloss                 | 0.0         |
| entropy                 | 2.6097388   |
| explained_variance_t... | 0.0763      |
| meankl                  | 0.008778296 |
| optimgain               | 0.036841504 |
| surrgain                | 0.036841504 |
-----------------------------------------
********** Iteration 80 ************
Optimizing Policy...
sampling
done in 0.603 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.16          0
         1      0.091    0.00862
         2      0.247     0.0275
         3     0.0372     0.0747
         4     0.0453      0.121
         5     0.0185      0.183
         6     0.0265      0.291
         7    0.00677      0.412
         8     0.0313      0.417
         9      0.054      0.492
        10     0.0114      0.509
done in 0.012 seconds
Expected: 0.037 Actual: 0.038
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.35       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 552         |
| TimeElapsed             | 61.3        |
| TimestepsSoFar          | 82944       |
| entloss                 | 0.0         |
| entropy                 | 2.5778527   |
| explained_variance_t... | 0.176       |
| meankl                  | 0.009156011 |
| optimgain               | 0.03804304  |
| surrgain                | 0.03804304  |
-----------------------------------------
********** Iteration 81 ************
Optimizing Policy...
sampling
done in 0.571 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0994          0
         1     0.0426    0.00609
         2     0.0747     0.0164
         3     0.0394     0.0435
         4     0.0127      0.083
         5     0.0157      0.175
         6    0.00989       0.24
         7    0.00609      0.317
         8     0.0353      0.325
         9     0.0204      0.381
        10    0.00647       0.39
done in 0.013 seconds
Expected: 0.027 Actual: 0.027
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.12       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 559         |
| TimeElapsed             | 61.9        |
| TimestepsSoFar          | 83968       |
| entloss                 | 0.0         |
| entropy                 | 2.570425    |
| explained_variance_t... | 0.218       |
| meankl                  | 0.009573167 |
| optimgain               | 0.026619371 |
| surrgain                | 0.026619371 |
-----------------------------------------
********** Iteration 82 ************
Optimizing Policy...
sampling
done in 0.582 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0801          0
         1      0.188     0.0151
         2      0.211     0.0434
         3      0.148     0.0814
         4     0.0112      0.132
         5     0.0261      0.191
         6     0.0126      0.337
         7      0.015      0.426
         8     0.0251      0.495
         9      0.023      0.504
        10     0.0861       0.53
done in 0.012 seconds
Expected: 0.037 Actual: 0.039
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.58       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 566         |
| TimeElapsed             | 62.6        |
| TimestepsSoFar          | 84992       |
| entloss                 | 0.0         |
| entropy                 | 2.5823252   |
| explained_variance_t... | 0.157       |
| meankl                  | 0.009730827 |
| optimgain               | 0.0391214   |
| surrgain                | 0.0391214   |
-----------------------------------------
********** Iteration 83 ************
Optimizing Policy...
sampling
done in 0.573 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.223          0
         1     0.0549    0.00635
         2      0.111     0.0171
         3      0.014     0.0699
         4      0.017      0.112
         5      0.012      0.212
         6     0.0125      0.305
         7     0.0249       0.36
         8    0.00325      0.365
         9     0.0276      0.373
        10    0.00367      0.463
done in 0.013 seconds
Expected: 0.031 Actual: 0.028
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.16       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 573         |
| TimeElapsed             | 63.2        |
| TimestepsSoFar          | 86016       |
| entloss                 | 0.0         |
| entropy                 | 2.6030774   |
| explained_variance_t... | 0.0946      |
| meankl                  | 0.009733773 |
| optimgain               | 0.027521722 |
| surrgain                | 0.027521722 |
-----------------------------------------
********** Iteration 84 ************
Optimizing Policy...
sampling
done in 0.580 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.142          0
         1     0.0727    0.00643
         2      0.128     0.0244
         3     0.0392     0.0443
         4     0.0164      0.114
         5    0.00744      0.226
         6    0.00812      0.317
         7      0.232      0.371
         8     0.0192      0.471
         9        0.2      0.562
        10     0.0106      0.723
done in 0.013 seconds
Expected: 0.036 Actual: 0.032
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.16       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 580         |
| TimeElapsed             | 63.8        |
| TimestepsSoFar          | 87040       |
| entloss                 | 0.0         |
| entropy                 | 2.6038184   |
| explained_variance_t... | 0.163       |
| meankl                  | 0.009814515 |
| optimgain               | 0.03224466  |
| surrgain                | 0.03224466  |
-----------------------------------------
********** Iteration 85 ************
Optimizing Policy...
sampling
done in 0.588 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.304          0
         1     0.0482    0.00741
         2     0.0831     0.0149
         3     0.0189     0.0602
         4     0.0293      0.145
         5     0.0166      0.308
         6    0.00599      0.493
         7     0.0214      0.496
         8      0.046      0.586
         9    0.00221        0.6
        10    0.00389      0.686
done in 0.013 seconds
Expected: 0.037 Actual: 0.031
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.81       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 587         |
| TimeElapsed             | 64.4        |
| TimestepsSoFar          | 88064       |
| entloss                 | 0.0         |
| entropy                 | 2.5945733   |
| explained_variance_t... | 0.106       |
| meankl                  | 0.009164488 |
| optimgain               | 0.031098805 |
| surrgain                | 0.031098805 |
-----------------------------------------
********** Iteration 86 ************
Optimizing Policy...
sampling
done in 0.755 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.373          0
         1      0.166     0.0116
         2     0.0877     0.0173
         3      0.225       0.04
         4     0.0275      0.118
         5     0.0133      0.155
         6     0.0128      0.208
         7     0.0968        0.3
         8    0.00821      0.312
         9     0.0417      0.419
        10     0.0162      0.434
done in 0.016 seconds
Expected: 0.036 Actual: 0.027
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.29       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 593         |
| TimeElapsed             | 65.2        |
| TimestepsSoFar          | 89088       |
| entloss                 | 0.0         |
| entropy                 | 2.6260266   |
| explained_variance_t... | 0.225       |
| meankl                  | 0.010285088 |
| optimgain               | 0.02736085  |
| surrgain                | 0.02736085  |
-----------------------------------------
********** Iteration 87 ************
Optimizing Policy...
sampling
Eval num_timesteps=89088, episode_reward=1.50 +/- 9.63
Episode length: 150.00 +/- 0.00
done in 1.177 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.661          0
         1     0.0969    0.00508
         2       0.17     0.0327
         3      0.198     0.0523
         4     0.0572     0.0885
         5     0.0344      0.159
         6     0.0238       0.22
         7      0.363      0.237
         8      0.017      0.409
         9     0.0289      0.539
        10     0.0162      0.545
done in 0.015 seconds
Expected: 0.041 Actual: 0.038
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.95       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 600         |
| TimeElapsed             | 66.5        |
| TimestepsSoFar          | 90112       |
| entloss                 | 0.0         |
| entropy                 | 2.6347542   |
| explained_variance_t... | 0.179       |
| meankl                  | 0.009894294 |
| optimgain               | 0.037649117 |
| surrgain                | 0.037649117 |
-----------------------------------------
********** Iteration 88 ************
Optimizing Policy...
sampling
done in 0.653 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.317          0
         1     0.0651    0.00634
         2      0.125     0.0166
         3     0.0452     0.0493
         4     0.0366     0.0861
         5     0.0161      0.139
         6     0.0208      0.279
         7      0.121      0.481
         8     0.0102      0.496
         9      0.138      0.553
        10     0.0107      0.608
done in 0.015 seconds
Expected: 0.037 Actual: 0.032
violated KL constraint. shrinking step.
Expected: 0.037 Actual: 0.017
Stepsize OK!
vf
done in 0.022 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -9.79        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 607          |
| TimeElapsed             | 67.2         |
| TimestepsSoFar          | 91136        |
| entloss                 | 0.0          |
| entropy                 | 2.6205132    |
| explained_variance_t... | -0.0312      |
| meankl                  | 0.0032867924 |
| optimgain               | 0.017493336  |
| surrgain                | 0.017493336  |
------------------------------------------
********** Iteration 89 ************
Optimizing Policy...
sampling
done in 0.667 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.157          0
         1       0.15    0.00951
         2      0.495     0.0466
         3     0.0745      0.126
         4     0.0832      0.162
         5     0.0277      0.206
         6     0.0213      0.252
         7     0.0116      0.402
         8      0.235      0.432
         9      0.132      0.611
        10      0.024      0.645
done in 0.015 seconds
Expected: 0.045 Actual: 0.041
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.06       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 614         |
| TimeElapsed             | 67.9        |
| TimestepsSoFar          | 92160       |
| entloss                 | 0.0         |
| entropy                 | 2.573609    |
| explained_variance_t... | 0.0777      |
| meankl                  | 0.011396959 |
| optimgain               | 0.040542632 |
| surrgain                | 0.040542632 |
-----------------------------------------
********** Iteration 90 ************
Optimizing Policy...
sampling
done in 0.623 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.244          0
         1      0.234     0.0125
         2      0.179     0.0193
         3      0.211     0.0353
         4      0.061      0.143
         5     0.0254      0.219
         6     0.0228      0.285
         7      0.175      0.361
         8     0.0201      0.371
         9     0.0413      0.429
        10      0.151      0.486
done in 0.014 seconds
Expected: 0.042 Actual: 0.044
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.85       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 621         |
| TimeElapsed             | 68.6        |
| TimestepsSoFar          | 93184       |
| entloss                 | 0.0         |
| entropy                 | 2.5598724   |
| explained_variance_t... | 0.0628      |
| meankl                  | 0.011599394 |
| optimgain               | 0.044491306 |
| surrgain                | 0.044491306 |
-----------------------------------------
********** Iteration 91 ************
Optimizing Policy...
sampling
done in 0.623 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.257          0
         1     0.0783    0.00858
         2      0.172     0.0188
         3     0.0504     0.0435
         4     0.0154      0.112
         5     0.0193      0.146
         6    0.00965       0.23
         7      0.036       0.34
         8     0.0162      0.347
         9       0.11      0.387
        10    0.00661      0.449
done in 0.014 seconds
Expected: 0.033 Actual: 0.035
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -7.1        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 628         |
| TimeElapsed             | 69.2        |
| TimestepsSoFar          | 94208       |
| entloss                 | 0.0         |
| entropy                 | 2.5649934   |
| explained_variance_t... | 0.0368      |
| meankl                  | 0.009546273 |
| optimgain               | 0.035313748 |
| surrgain                | 0.035313748 |
-----------------------------------------
********** Iteration 92 ************
Optimizing Policy...
sampling
done in 0.622 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.787          0
         1     0.0729    0.00363
         2      0.118     0.0158
         3      0.113     0.0343
         4     0.0471     0.0497
         5     0.0303      0.108
         6     0.0246      0.165
         7      0.041      0.167
         8     0.0293      0.242
         9     0.0197      0.379
        10      0.249      0.682
done in 0.016 seconds
Expected: 0.038 Actual: 0.049
violated KL constraint. shrinking step.
Expected: 0.038 Actual: 0.021
Stepsize OK!
vf
done in 0.024 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -6.79        |
| EpThisIter              | 6            |
| EpisodesSoFar           | 634          |
| TimeElapsed             | 69.9         |
| TimestepsSoFar          | 95232        |
| entloss                 | 0.0          |
| entropy                 | 2.5651968    |
| explained_variance_t... | 0.148        |
| meankl                  | 0.0048929485 |
| optimgain               | 0.02095828   |
| surrgain                | 0.02095828   |
------------------------------------------
********** Iteration 93 ************
Optimizing Policy...
sampling
done in 0.671 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       1.89          0
         1     0.0974    0.00805
         2      0.293     0.0341
         3     0.0927     0.0567
         4     0.0672      0.125
         5     0.0358      0.139
         6     0.0473      0.214
         7      0.171      0.224
         8     0.0337      0.356
         9     0.0265      0.506
        10     0.0201      0.596
done in 0.015 seconds
Expected: 0.045 Actual: 0.034
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.03       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 641         |
| TimeElapsed             | 70.6        |
| TimestepsSoFar          | 96256       |
| entloss                 | 0.0         |
| entropy                 | 2.5450416   |
| explained_variance_t... | 0.136       |
| meankl                  | 0.010525463 |
| optimgain               | 0.033858366 |
| surrgain                | 0.033858366 |
-----------------------------------------
********** Iteration 94 ************
Optimizing Policy...
sampling
done in 0.680 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.28          0
         1       0.23    0.00721
         2      0.141     0.0388
         3     0.0804     0.0507
         4     0.0625      0.104
         5     0.0348      0.119
         6     0.0101      0.175
         7    0.00823      0.194
         8     0.0102      0.195
         9    0.00657       0.22
        10    0.00318       0.27
done in 0.014 seconds
Expected: 0.032 Actual: 0.028
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.1        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 648         |
| TimeElapsed             | 71.4        |
| TimestepsSoFar          | 97280       |
| entloss                 | 0.0         |
| entropy                 | 2.5423918   |
| explained_variance_t... | 0.217       |
| meankl                  | 0.010074278 |
| optimgain               | 0.028150756 |
| surrgain                | 0.028150756 |
-----------------------------------------
********** Iteration 95 ************
Optimizing Policy...
sampling
done in 0.666 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.156          0
         1      0.311     0.0283
         2      0.733     0.0713
         3      0.539      0.109
         4     0.0553      0.138
         5     0.0482      0.203
         6     0.0254      0.243
         7     0.0264      0.312
         8      0.185      0.507
         9      0.011      0.519
        10      0.169      0.549
done in 0.014 seconds
Expected: 0.046 Actual: 0.044
Stepsize OK!
vf
done in 0.024 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -9.25        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 655          |
| TimeElapsed             | 72.1         |
| TimestepsSoFar          | 98304        |
| entloss                 | 0.0          |
| entropy                 | 2.5447297    |
| explained_variance_t... | 0.211        |
| meankl                  | 0.0083136475 |
| optimgain               | 0.043592174  |
| surrgain                | 0.043592174  |
------------------------------------------
********** Iteration 96 ************
Optimizing Policy...
sampling
done in 0.665 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.15          0
         1      0.203     0.0152
         2     0.0742     0.0745
         3      0.295     0.0866
         4      0.027       0.14
         5     0.0356      0.186
         6     0.0246      0.227
         7     0.0177      0.313
         8      0.133      0.438
         9     0.0282      0.472
        10      0.271      0.581
done in 0.016 seconds
Expected: 0.041 Actual: 0.038
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.84       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 662         |
| TimeElapsed             | 72.8        |
| TimestepsSoFar          | 99328       |
| entloss                 | 0.0         |
| entropy                 | 2.551373    |
| explained_variance_t... | 0.123       |
| meankl                  | 0.010245344 |
| optimgain               | 0.037532937 |
| surrgain                | 0.037532937 |
-----------------------------------------
********** Iteration 97 ************
Optimizing Policy...
sampling
Eval num_timesteps=99328, episode_reward=-1.40 +/- 7.92
Episode length: 150.00 +/- 0.00
done in 1.247 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0       0.17          0
         1      0.158    0.00854
         2      0.369     0.0178
         3     0.0835     0.0706
         4     0.0633      0.149
         5      0.048      0.188
         6     0.0354       0.28
         7      0.069       0.52
         8       0.24      0.534
         9      0.128      0.691
        10       0.03      0.712
done in 0.015 seconds
Expected: 0.047 Actual: 0.056
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.63       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 669         |
| TimeElapsed             | 74.1        |
| TimestepsSoFar          | 100352      |
| entloss                 | 0.0         |
| entropy                 | 2.560139    |
| explained_variance_t... | 0.215       |
| meankl                  | 0.012748822 |
| optimgain               | 0.05626858  |
| surrgain                | 0.05626858  |
-----------------------------------------
Saving to logs/train_0.1M_Reacher2Dof-v0/trpo/Reacher2Dof-v0_1
pybullet build time: Sep  9 2020 17:03:46
