WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/misc_util.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

========== Reacher2Dof-v0 ==========
Seed: 1
OrderedDict([('n_timesteps', 1000000.0), ('policy', 'MlpPolicy')])
Using 1 environments
Overwriting n_timesteps with n=10000
Creating test environment
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:200: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/policies.py:561: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_layers.py:123: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/distributions.py:418: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:449: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:407: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:192: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:241: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:242: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:266: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

Log path: logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
/home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/common/callbacks.py:287: UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7f15c4f362e8> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f15c4f36278>
  "{} != {}".format(self.training_env, self.eval_env))
********** Iteration 0 ************
Optimizing Policy...
sampling
done in 0.683 seconds
computegrad
WARNING:tensorflow:From /home/pierre/bin/anaconda3/envs/reacher_link/lib/python3.7/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py:364: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

done in 0.105 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0565          0
         1     0.0127     0.0218
         2    0.00659      0.119
         3    0.00613        0.3
         4    0.00432       0.48
         5     0.0152      0.556
         6    0.00265      0.594
         7   0.000916      0.764
         8   0.000666      0.848
         9   0.000169       1.21
        10   0.000525       1.22
done in 0.178 seconds
Expected: 0.036 Actual: 0.038
Stepsize OK!
vf
done in 0.055 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -18         |
| EpThisIter              | 6           |
| EpisodesSoFar           | 6           |
| TimeElapsed             | 1.1         |
| TimestepsSoFar          | 1024        |
| entloss                 | 0.0         |
| entropy                 | 2.8537595   |
| explained_variance_t... | -0.000578   |
| meankl                  | 0.007863039 |
| optimgain               | 0.038255677 |
| surrgain                | 0.038255677 |
-----------------------------------------
********** Iteration 1 ************
Optimizing Policy...
sampling
done in 0.597 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0893          0
         1     0.0297     0.0228
         2     0.0208      0.105
         3    0.00445      0.117
         4    0.00271      0.162
         5     0.0041      0.388
         6     0.0028       0.52
         7    0.00152      0.618
         8     0.0124      0.791
         9    0.00215      0.824
        10     0.0043      0.892
done in 0.017 seconds
Expected: 0.033 Actual: 0.027
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -19.5       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 13          |
| TimeElapsed             | 1.75        |
| TimestepsSoFar          | 2048        |
| entloss                 | 0.0         |
| entropy                 | 2.875081    |
| explained_variance_t... | -0.0202     |
| meankl                  | 0.011983184 |
| optimgain               | 0.027124383 |
| surrgain                | 0.027124383 |
-----------------------------------------
********** Iteration 2 ************
Optimizing Policy...
sampling
done in 0.659 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0645          0
         1     0.0114     0.0294
         2    0.00959      0.064
         3    0.00391     0.0783
         4    0.00268      0.156
         5    0.00208      0.214
         6    0.00197      0.303
         7    0.00303      0.409
         8     0.0021      0.709
         9    0.00551      0.815
        10    0.00111      0.847
done in 0.015 seconds
Expected: 0.027 Actual: 0.021
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -18.1       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 20          |
| TimeElapsed             | 2.45        |
| TimestepsSoFar          | 3072        |
| entloss                 | 0.0         |
| entropy                 | 2.8496313   |
| explained_variance_t... | -0.00407    |
| meankl                  | 0.005889199 |
| optimgain               | 0.020586163 |
| surrgain                | 0.020586163 |
-----------------------------------------
********** Iteration 3 ************
Optimizing Policy...
sampling
done in 0.630 seconds
computegrad
done in 0.005 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.017          0
         1     0.0138     0.0628
         2    0.00214     0.0774
         3    0.00517      0.101
         4    0.00297      0.122
         5    0.00319       0.28
         6    0.00151       0.39
         7    0.00146      0.459
         8   0.000744      0.521
         9   0.000436      0.558
        10    0.00475      0.616
done in 0.016 seconds
Expected: 0.023 Actual: 0.023
Stepsize OK!
vf
done in 0.024 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -16.3       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 27          |
| TimeElapsed             | 3.13        |
| TimestepsSoFar          | 4096        |
| entloss                 | 0.0         |
| entropy                 | 2.8169637   |
| explained_variance_t... | -0.00252    |
| meankl                  | 0.009486989 |
| optimgain               | 0.023486163 |
| surrgain                | 0.023486163 |
-----------------------------------------
********** Iteration 4 ************
Optimizing Policy...
sampling
done in 0.636 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0379          0
         1     0.0172     0.0188
         2    0.00223     0.0695
         3    0.00322     0.0726
         4    0.00306      0.143
         5    0.00252      0.264
         6    0.00337      0.445
         7   0.000959      0.555
         8    0.00147      0.633
         9    0.00469      0.654
        10   0.000824      0.698
done in 0.014 seconds
Expected: 0.024 Actual: 0.016
Stepsize OK!
vf
done in 0.021 seconds
------------------------------------------
| EpLenMean               | 150          |
| EpRewMean               | -14.9        |
| EpThisIter              | 7            |
| EpisodesSoFar           | 34           |
| TimeElapsed             | 3.82         |
| TimestepsSoFar          | 5120         |
| entloss                 | 0.0          |
| entropy                 | 2.8011272    |
| explained_variance_t... | -0.039       |
| meankl                  | 0.0115748495 |
| optimgain               | 0.016438529  |
| surrgain                | 0.016438529  |
------------------------------------------
********** Iteration 5 ************
Optimizing Policy...
sampling
done in 0.575 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0265          0
         1     0.0156     0.0117
         2     0.0332     0.0869
         3    0.00271      0.104
         4    0.00246      0.158
         5    0.00172      0.277
         6    0.00348      0.547
         7     0.0128      0.794
         8    0.00105      0.821
         9    0.00277      0.934
        10   0.000207      0.939
done in 0.013 seconds
Expected: 0.028 Actual: 0.027
Stepsize OK!
vf
done in 0.023 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -13.9       |
| EpThisIter              | 6           |
| EpisodesSoFar           | 40          |
| TimeElapsed             | 4.44        |
| TimestepsSoFar          | 6144        |
| entloss                 | 0.0         |
| entropy                 | 2.82029     |
| explained_variance_t... | 0.00312     |
| meankl                  | 0.009332495 |
| optimgain               | 0.026857309 |
| surrgain                | 0.026857309 |
-----------------------------------------
********** Iteration 6 ************
Optimizing Policy...
sampling
done in 0.598 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0517          0
         1     0.0172     0.0128
         2     0.0212     0.0584
         3    0.00185     0.0685
         4    0.00193      0.118
         5    0.00144      0.168
         6    0.00164      0.294
         7    0.00105      0.354
         8    0.00729      0.371
         9    0.00162       0.45
        10    0.00152      0.457
done in 0.014 seconds
Expected: 0.021 Actual: 0.021
Stepsize OK!
vf
done in 0.022 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -12.8       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 47          |
| TimeElapsed             | 5.08        |
| TimestepsSoFar          | 7168        |
| entloss                 | 0.0         |
| entropy                 | 2.7931206   |
| explained_variance_t... | 0.012       |
| meankl                  | 0.009822154 |
| optimgain               | 0.020886816 |
| surrgain                | 0.020886816 |
-----------------------------------------
********** Iteration 7 ************
Optimizing Policy...
sampling
done in 0.575 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0337          0
         1     0.0724     0.0344
         2    0.00968     0.0984
         3     0.0162      0.106
         4    0.00548      0.187
         5    0.00254      0.263
         6    0.00343      0.394
         7    0.00211      0.538
         8     0.0151      0.571
         9    0.00154      0.609
        10     0.0158      0.652
done in 0.014 seconds
Expected: 0.030 Actual: 0.027
Stepsize OK!
vf
done in 0.020 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -10.6       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 54          |
| TimeElapsed             | 5.71        |
| TimestepsSoFar          | 8192        |
| entloss                 | 0.0         |
| entropy                 | 2.8047702   |
| explained_variance_t... | -0.0327     |
| meankl                  | 0.00910468  |
| optimgain               | 0.027325671 |
| surrgain                | 0.027325671 |
-----------------------------------------
********** Iteration 8 ************
Optimizing Policy...
sampling
done in 0.583 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0     0.0333          0
         1     0.0325     0.0141
         2     0.0437     0.0918
         3    0.00403      0.111
         4    0.00288      0.158
         5    0.00419      0.251
         6    0.00403      0.436
         7    0.00593      0.675
         8    0.00451      0.688
         9    0.00893      0.755
        10    0.00111      0.773
done in 0.013 seconds
Expected: 0.029 Actual: 0.024
Stepsize OK!
vf
done in 0.019 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -9.92       |
| EpThisIter              | 7           |
| EpisodesSoFar           | 61          |
| TimeElapsed             | 6.33        |
| TimestepsSoFar          | 9216        |
| entloss                 | 0.0         |
| entropy                 | 2.8057353   |
| explained_variance_t... | 0.0201      |
| meankl                  | 0.007980948 |
| optimgain               | 0.023582328 |
| surrgain                | 0.023582328 |
-----------------------------------------
********** Iteration 9 ************
Optimizing Policy...
sampling
Eval num_timesteps=9216, episode_reward=-0.53 +/- 8.76
Episode length: 150.00 +/- 0.00
New best mean reward!
done in 1.147 seconds
computegrad
done in 0.004 seconds
conjugate_gradient
      iter residual norm  soln norm
         0      0.185          0
         1     0.0713     0.0213
         2     0.0105      0.117
         3     0.0492      0.145
         4    0.00555      0.183
         5    0.00312      0.239
         6    0.00321      0.456
         7     0.0027      0.512
         8    0.00323      0.518
         9    0.00534      0.627
        10     0.0219      0.742
done in 0.013 seconds
Expected: 0.037 Actual: 0.037
Stepsize OK!
vf
done in 0.021 seconds
-----------------------------------------
| EpLenMean               | 150         |
| EpRewMean               | -8.1        |
| EpThisIter              | 7           |
| EpisodesSoFar           | 68          |
| TimeElapsed             | 7.52        |
| TimestepsSoFar          | 10240       |
| entloss                 | 0.0         |
| entropy                 | 2.8322423   |
| explained_variance_t... | -0.0728     |
| meankl                  | 0.008743992 |
| optimgain               | 0.036760755 |
| surrgain                | 0.036760755 |
-----------------------------------------
Saving to logs/train_10K_Reacher2Dof-v0/trpo/Reacher2Dof-v0_2
pybullet build time: Sep  9 2020 17:03:46
